---
sidebar: sidebar 
permalink: rhhc/rhhc-pm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= 采用托管Red Hat OpenShift容器平台工作负载的NetApp解决方案
:allow-uri-read: 




== 采用托管Red Hat OpenShift容器平台工作负载的NetApp解决方案

[role="lead"]
客户可能"生于云"、也可能正处于现代化之旅的某一时刻、准备将部分选定工作负载或所有工作负载从数据中心迁移到云。他们可以选择在云中使用提供商管理的OpenShift容器和提供商管理的NetApp存储来运行工作负载。他们应在云中规划和部署托管Red Hat OpenShift容器集群、以便为其容器工作负载打造一个成功的生产就绪环境。。NetApp为所有三种领先公有云中的Red Hat托管解决方案提供完全托管的存储产品。

*Amazon FSx for NetApp ONTAP (FSX ONTAP)*

FSx ONTAP可为AWS中的容器部署提供数据保护、可靠性和灵活性。Trident充当动态存储配置程序、用于为客户的有状态应用程序使用永久性FSx ONTAP存储。

由于可以在HA模式下部署ROSA、并且控制平台节点分布在多个可用性区域中、因此FSx ONTAP 还可以配置Multi-AZ选项、以提供高可用性并防止出现AZ故障。

*Google Cloud NetApp Volumes*

Red Hat OpenShift Dicinated是一款完全托管的应用程序平台、支持您在混合云中快速构建、部署和扩展应用程序。Google Cloud NetApp Volumes提供永久性卷、可将全套ONTAP企业级数据管理功能引入Google Cloud中的OpenShift部署。
