---
sidebar: sidebar 
permalink: rhhc/rhhc-value-prop.html 
keywords: NetApp Solutions, hybrid cloud, container workloads, containers, Red Hat OpenShift, RedHat OpenShift, VMware, ROSA, ACC, Astra Control Center, Advanced Cluster Management, ACM, Hub Cluster 
summary:  
---
= 适用于Red Hat OpenShift容器工作负载的NetApp混合云解决方案的价值主张
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
大多数客户并不只是在没有任何现有基础架构的情况下开始构建基于Kubennet的环境。他们可能是一家传统的IT公司、在虚拟机(例如、在大型VMware环境中)上运行大多数企业级应用程序。然后、他们开始构建基于容器的小型环境、以满足现代应用程序开发团队的需求。这些计划通常从小规模入手、随着团队学习这些新技术和技能、并开始认识到采用这些新技术和技能的诸多优势、这些计划开始变得越来越普及。对客户来说、好消息是NetApp可以满足这两种环境的需求。这套采用Red Hat OpenShift的混合多云解决方案将赋予NetApp客户采用现代云技术和服务的能力、而无需全面革新整个基础架构和组织。无论客户应用程序和数据托管在内部环境、云中、虚拟机上还是容器上、NetApp都可以提供一致的数据管理、保护、安全性和可移动性。借助这些新解决方案、NetApp数十年来在内部数据中心环境中提供的相同价值将在整个企业数据范围内实现、而无需投入大量资金来重新利用、获得新技能或组建新团队。无论客户处于云之旅的哪个阶段、NetApp都能很好地帮助他们解决这些业务挑战。

采用Red Hat OpenShift的NetApp混合多云：

* 为客户提供经验证的设计和实践、展示在将Red Hat OpenShift与基于NetApp的存储解决方案结合使用时、客户管理、保护、保护和迁移其数据和应用程序的最佳方式。
* 为在VMware环境、裸机基础架构或这两者的组合中使用NetApp存储运行Red Hat OpenShift的客户提供最佳实践。
* 演示内部环境和云环境以及同时使用这两者的混合环境的策略和选项。

