---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: 本节介绍了用于dremio认证的硬件和软件。此信息适用于使用NetApp存储进行dremio部署。 
---
= 解决方案概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
混合式iceberg湖畔解决方案具有独特的优势、可帮助客户应对数据湖客户面临的挑战。通过利用多雷米奥统一湖屋平台以及NetApp ONTAP、StorageGRID和NetApp云解决方案、企业可以为其业务运营带来显著价值。该解决方案不仅提供对多个数据源(包括NetApp源)的访问、而且还增强了整体分析性能、并帮助公司获得业务洞察力、从而促进业务增长。



== NetApp 概述

* NetApp的产品(例如ONTAP和StorageGRID)可以将存储和计算分离、从而根据特定需求实现最佳资源利用率。这种灵活性使客户能够使用NetApp存储解决方案独立扩展其存储
* 通过利用NetApp的存储控制器、客户可以使用NFS和S3协议高效地向其矢量数据库提供数据。这些协议有助于客户存储数据并管理向量数据库索引、从而无需通过文件和对象方法访问多个数据副本。
* NetApp ONTAP为AWS、Azure和Google Cloud等领先云服务提供商的NAS和对象存储提供本机支持。这种广泛的兼容性可确保无缝集成、从而实现客户数据移动性、全局可访问性、灾难恢复、动态可扩展性和高性能。




=== StorageGRID

我们行业领先的对象存储StorageGRID通过分层纠删编码为自动化数据放置提供了强大的策略引擎、灵活的部署选项以及无与伦比的持久性。它具有一个可扩展的架构、可在一个命名空间中支持数十亿个对象和PB级数据。该解决方案支持混合云集成、支持将数据分层到主要云平台。在2019年IDC MarketScape全球基于对象的供应商评估中、该公司被公认为领导者。

此外、StorageGRID还凭借软件定义的对象存储、地区冗余和多站点功能、在大规模管理非结构化数据方面表现出色。它整合了基于策略的信息生命周期管理、并提供镜像和搜索等云集成功能。它拥有各种认证、包括通用标准、NF203数字安全组件、ISO/IEC 25051、KPMG和Cohasset合规性评估。

总之、NetApp StorageGRID提供了强大的功能、可扩展性、混合云集成和合规性认证、可用于大规模高效管理非结构化数据。



=== NetApp ONTAP

NetApp ONTAP是一款功能强大的存储解决方案、可提供广泛的企业级功能。它包括Snapshot、可提供应用程序一致且防篡改的即时备份。SnapRestore支持近乎即时地按需还原备份、而SnapMirror则提供集成的远程备份和灾难恢复功能。该解决方案还整合了自动防兰软件保护(ARP)、通过多管理员验证、采用FIPS认证的空闲数据加密、传输中数据加密、多因素身份验证(MFA)和基于角色的访问控制(RBAC)等功能确保数据安全。全面的日志记录、审核、板载和外部密钥管理、安全清除以及多个租户的安全管理、进一步增强了数据安全性和合规性。

NetApp ONTAP还采用SnapLock、它可以提供符合法规的数据保留、并以较低的总拥有成本实现高级别的完整性、性能和保留。它与NetApp ONTAP®9完全集成，可防止恶意行为、恶意管理员和勒索软件。

该解决方案包括用于传输中和空闲数据加密的NSE/NVE加密、多因素管理员访问和多管理员验证。Active IQ提供基于AI的预测性分析和更正操作、而QoS则确保控制服务质量工作负载。管理和自动化集成可通过SysMgr/GUI/CLI/CAPI直观地实现。FabricPool支持自动数据分层、该解决方案可通过实时数据压缩、重复数据删除和数据缩减提高效率。NetApp保证客户可以免费实现工作负载效率目标。

NetApp ONTAP支持各种协议、包括NVMe/FC、FC、NVMe/TCP、iSCSI、NFS、SMB和S3、是一款统一的存储解决方案。总之、NetApp ONTAP提供广泛的企业级功能、强大的安全性、合规性、效率和多功能性、可满足各种存储需求。



== d不良 概述

d雷 米奥是一款用于自助分析和AI的统一湖屋平台。与传统数据仓库解决方案相比、凭借其出色的灵活性、可扩展性和性能、多米奥统一分析平台可让用户更接近数据。利用"DLEMIO "实现"左移"分析、消除复杂且成本高昂的数据集成和ETL、在不移动数据的情况下提供无缝的企业级分析。此外、还有以下功能：

* 通过通用的语法层和紧密集成的高性能SQL查询引擎实现易于使用的自助式分析、使云端和内部环境中的所有数据都能更轻松地进行连接、监管和分析。
* 德雷米奥的Apache iceberg原生数据库管理功能可简化数据发现并自动进行数据优化、从而利用Git激发的数据版本控制功能提供高性能分析。
* 凭借基于开源和开放标准的基础架构、德鲁米奥公司可以避免受制于供应商、并保持创新定位。企业公司相信、在所有工作负载中、都能以最佳的性价比获得最易于使用的Lakhouse平台。




== 德雷米奥和NetApp混合式冰山一角湖解决方案为客户带来了哪些价值？

* *改进的数据管理和可访问性*：DREMIO因其数据湖平台而闻名、该平台使企业能够高速直接从数据湖中查询数据。另一方面、NetApp是领先的云数据服务和数据存储解决方案提供商。联合产品为客户提供了一个全面的解决方案、用于高效地存储、管理、访问和分析其企业数据。
* *性能优化*：凭借NetApp在数据存储方面的专业知识以及DREMIO在Data Processing和数据优化方面的能力，这一合作伙伴关系提供了一个可提高数据运行性能、减少延迟并加快获得业务洞察力的解决方案。在NetApp内部IT分析基础架构中、d不良 甚至可以带来性能优势。
* *可扩展性*：DREMIO和NetApp都提供了一个可扩展的解决方案。该联合解决方案可为客户提供高度可扩展的数据存储、数据管理和分析环境。在混合式iceberg湖屋环境中、与NetApp StorageGRID配合使用的德雷米奥SQL查询引擎可提供无与伦比的可扩展性、并发性和查询性能、能够满足任何企业的分析需求。
* *数据安全和监管*：两家公司都非常重视数据安全和监管。它们共同提供强大的安全性和数据监管功能、确保数据受到保护并满足数据监管要求。基于角色的精细访问控制、全面审计、端到端数据分析、统一身份管理以及具有广泛合规性和安全框架的SSO等功能可确保企业的分析数据环境安全且受监管。
* *成本效益*：通过将DREMIO的数据湖引擎与NetApp的存储解决方案相集成、客户可以降低与数据管理和数据移动相关的成本。企业还可以从传统的数据湖环境迁移到由NetApp和dlemio组成的更现代化的湖屋解决方案。此混合式iceberg湖屋解决方案可提供高速查询性能和市场领先的查询并发性、从而降低TCO并缩短获得业务洞察力的时间。

