---
sidebar: sidebar 
permalink: data-analytics/hdcs-sh-conclusion.html 
keywords: conclusion, summary, data protection, hadoop, more information, Acknowledgements, version history 
summary: 本节概述了 NetApp 为满足各种 Hadoop 数据保护要求而提供的使用情形和解决方案。 
---
= 结论
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:hdcs-sh-use-case-5--accelerate-analytic-workloads.html["先前：用例 5 —加快分析工作负载的速度。"]

[role="lead"]
本节概述了 NetApp 为满足各种 Hadoop 数据保护要求而提供的使用情形和解决方案。通过使用 NetApp 提供支持的 Data Fabric ，客户可以：

* 利用 NetApp 丰富的数据管理功能并与 Hadoop 原生工作流集成，灵活选择合适的数据保护解决方案。
* 将 Hadoop 集群备份窗口时间缩短近 70% 。
* 消除 Hadoop 集群备份所带来的任何性能影响。
* 同时提供从不同云提供商到单个分析数据源的多云数据保护和数据访问。
* 使用 FlexClone 技术快速创建节省空间的 Hadoop 集群副本。




== 从何处查找追加信息

要了解有关本文档中所述信息的更多信息，请参见以下文档和 / 或网站：

* NetApp 大数据分析解决方案
+
https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx["https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx"^]

* 采用 NetApp 存储的 Apache Spark 工作负载
+
https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf["https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf"^]

* 适用于 Apache Spark 的 NetApp 存储解决方案
+
https://www.netapp.com/media/16864-tr-4570.pdf["https://www.netapp.com/media/16864-tr-4570.pdf"^]

* NetApp 支持的 Data Fabric 上的 Apache Hadoop
+
https://www.netapp.com/media/16877-tr-4529.pdf["https://www.netapp.com/media/16877-tr-4529.pdf"^]





== 致谢

* NetApp ANZ 维多利亚地区销售代表 Paul Burland
* NetApp 业务开发经理 Hoseb Dermanilian
* NetApp MPSG 总监 Lee Dorrier
* NetApp ANZ 维多利亚区 SE 系统工程师 David Thiessen




== 版本历史记录

|===
| version | Date | 文档版本历史记录 


| 版本 1.0 | 2018 年 1 月 | 初始版本。 


| 版本 2.0 | 2021年10月 | 更新了用例 5 ：加快分析工作负载的速度 


| 版本 3.0 | 2023年11月 | 已删除NIPAM详细信息 
|===