---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization, overview 
summary: 解决方案提供了在NetApp存储上部署Hyper-V所需的步骤 
---
= 在NetApp存储上部署Microsoft Hyper-V
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Windows Server平台使用Hyper-V角色提供虚拟化技术。Hyper-V是Windows Server提供的许多可选角色之一。



== 概述

通过Hyper-V角色、我们可以使用Windows Server中内置的虚拟化技术创建和管理虚拟化计算环境。Hyper-V技术可对硬件进行虚拟化、从而提供一个环境、在此环境中、您可以在一台物理计算机上同时运行多个操作系统。通过Hyper-V、您可以创建和管理虚拟机及其资源。每个虚拟机都是一个独立的虚拟化计算机系统、可以运行自己的操作系统。Hyper-V提供的基础架构可对应用程序和工作负载进行虚拟化，这些应用程序和工作负载支持旨在提高效率和降低成本的各种业务目标，这是VMware®vSphere的完美替代方案，特别是当企业希望在当前市场条件下共存多个虚拟机管理程序时。



== audience

本文档介绍了使用NetApp ONTAP系统的Hyper-V集群配置的架构和部署过程。本文档的目标受众包括销售工程师、现场顾问、专业服务人员、IT经理、合作伙伴工程师、 以及希望将Hyper-V部署为主虚拟机管理程序或备用虚拟机管理程序的客户。



== 架构

本文档中介绍的架构专门包括Microsoft®Windows Server®2022和Hyper-V®虚拟化。NetApp强烈建议在每次部署中都使用虚拟化软件和基础架构管理软件。此配置会根据每个组件的最佳实践来实现可靠的企业级基础架构。



== 使用情形摘要

本文档介绍了在使用NetApp纯闪存FAS和ASA阵列型号的Microsoft Windows Server 2022上设置Hyper-V集群以使其作为工作负载以最佳方式运行的部署过程和最佳实践。服务器操作系统/虚拟机管理程序为Microsoft Windows Server 2022。本指南涵盖了通过存储区域网络(SAN)和网络连接存储(NAS)协议提供数据的NetApp存储系统。
