---
sidebar: sidebar 
permalink: ent-apps-db/db_protection_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: 此页面介绍了在 NetApp ONTAP 存储上部署 Oracle19c 的自动化方法。 
---
= 解决方案概述
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== 为 Oracle 数据库提供自动化数据保护

企业正在对其环境进行自动化，以提高效率，加快部署速度并减少手动操作。Ansible 等配置管理工具正在用于简化企业数据库操作。在本解决方案中，我们演示了如何使用 Ansible 通过 NetApp ONTAP 自动保护 Oracle 数据。通过使存储管理员，系统管理员和 DBA 能够一致快速地将数据复制到异地数据中心或公有云，您可以获得以下优势：

* 消除设计复杂性和人为错误，并实施可重复的一致部署和最佳实践
* 缩短配置集群间复制， CVO 实例化和恢复 Oracle 数据库的时间
* 提高数据库管理员，系统和存储管理员的工作效率
* 提供数据库恢复工作流，以便于测试灾难恢复场景。


NetApp 为客户提供经过验证的 Ansible 模块和角色，以加快 Oracle 数据库环境的部署，配置和生命周期管理。此解决方案提供了相关说明和 Ansible 攻略手册代码，可帮助您：



=== 在内部复制到内部复制

* 在源和目标上创建集群间 LIF
* 建立集群和 SVM 对等关系
* 创建并初始化 Oracle 卷的 SnapMirror
* 通过 AWX/Tower 为 Oracle 二进制文件，数据库和日志创建复制计划
* 还原目标上的 Oracle 数据库，并使数据库联机




=== 在内部迁移到 AWS 中的 CVO

* 创建 AWS 连接器
* 在 AWS 中创建 CVO 实例
* 将内部集群添加到 Cloud Manager
* 在源上创建集群间 LIF
* 建立集群和 SVM 对等关系
* 创建并初始化 Oracle 卷的 SnapMirror
* 通过 AWX/Tower 为 Oracle 二进制文件，数据库和日志创建复制计划
* 还原目标上的 Oracle 数据库，并使数据库联机


有关更多详细信息或要开始，请参见下面的概述视频。



=== AWX/ 塔式部署

* 第 1 部分：待定
+
视频::


* 第 2 部分：待定
+
视频::



