---
sidebar: sidebar 
permalink: ent-apps-db/saphana_aff_nfs_i_o_stack_configuration_for_sap_hana.html 
keywords: stack, configuration, io, i/o, optimal values 
summary: 从 SAP HANA 1.0 SPS10 开始， SAP 引入了一些参数来调整 I/O 行为并针对所使用的文件和存储系统优化数据库。 
---
= SAP HANA 的 I/O 堆栈配置
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana_aff_nfs_sap_hana_installation_preparations_for_nfsv4.html["先前版本： NFSv4 的 SAP HANA 安装准备。"]

从 SAP HANA 1.0 SPS10 开始， SAP 引入了一些参数来调整 I/O 行为并针对所使用的文件和存储系统优化数据库。

NetApp 进行了性能测试以定义理想值。下表列出了从性能测试中推断的最佳值。

|===
| 参数 | 价值 


| max_parlated_io_requests. | 128. 


| 异步读取提交 | 开启 


| 异步写入提交活动 | 开启 


| 异步写入提交块 | 全部 
|===
对于 SPS12 之前的 SAP HANA 1.0 版本，可以在安装 SAP HANA 数据库期间设置这些参数，如 SAP 注释所述 https://launchpad.support.sap.com/["2267798 ：使用 hdbparam 在安装期间配置 SAP HANA 数据库"^]。

或者，也可以在安装 SAP HANA 数据库后使用 `hdbparam` framework 设置这些参数。

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_read_submit=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
从 SAP HANA 2.0 开始， `hdbparam` 已弃用，并且参数已移至 `global.ini` 。可以使用 SQL 命令或 SAP HANA Studio 设置这些参数。有关详细信息，请参见 SAP 注释 https://launchpad.support.sap.com/["2399079 ：在 HANA 2 中消除了 hdbparam"^]。这些参数也可以在 global.ini 中进行设置，如下所示：

....
nf2adm@stlrx300s8-6: /usr/sap/NF2/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
从 SAP HANA 2.0 SPS5 开始，您可以使用 `setParameter.py` 脚本设置正确的参数：

....
nf2adm@sapcc-hana-tst-03:/usr/sap/NF2/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....
link:saphana_aff_nfs_sap_hana_data_volume_size.html["接下来： SAP HANA 数据卷大小。"]
