---
sidebar:
  entries:
  - title: NetApp 解决方案文档
    url: "/index.html"
  - section: ai
  - section: data-analytics
  - section: hybrid-cloud
  - section: vdi-vds
  - section: containers
  - section: ent-apps-db
  - section: dp-sec
  - section: infra
  - section: automation
  - title: FlexPod 解决方案
    url: https://docs.netapp.com/us-en/flexpod/
  - title: 更改日志
    url: "/change-log-display.html"
  - title: 关于 NetApp 解决方案
    url: "/about.html"
  - title: 法律声明
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: AI 现代数据分析
    links:
    - title: 新增功能
      url: aimda-whatsnew.html
    - title: NetApp DataOps 工具包
      url: https://github.com/NetApp/netapp-data-science-toolkit
    - title: 视频和演示
      url: aimda-videos.html
    - title: 博客
      url: aimda-blogs.html
  - title: 混合云，虚拟化容器
    links:
    - title: 新增功能
      url: hc-whatsnew.html
    - title: 视频和演示
      url: hc-videos.html
    - title: 博客
      url: hc-blogs.html
  - title: 企业应用程序数据库
    links:
    - title: 新增功能
      url: appsdb-whatsnew.html
    - title: 视频和演示
      url: appsdb-videos.html
  - title: 数据保护和安全
    links:
    - title: 新增功能
      url: dpsec-whatsnew.html
  - title: 解决方案自动化
    links:
    - title: 新增功能
      url: automation-whatsnew.html
    - title: 视频和演示
      url: automation-videos.html
    - title: 请求自动化
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
  - title: FlexPod — NetApp Cisco 解决方案
    links:
    - title: FlexPod 解决方案技术内容
      url: https://docs.netapp.com/us-en/flexpod/
    - title: FlexPod 销售页面
      url: https://flexpod.com
    - title: 视频和演示
      url: https://tv.netapp.com/search?q=flexpod
    - title: 博客
      url: https://blog.netapp.com/tag/FlexPod/
  - title: 反馈
    links:
    - title: 建议新的解决方案
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
    - title: 提供解决方案反馈
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
