---
sidebar: sidebar 
permalink: videos.html 
summary: 一系列视频和演示、讨论NetApp的许多解决方案的功能 
keywords: netapp, solutions, videos, demos 
---
= NetApp解决方案：视频和演示
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
视频和演示概述、重点介绍NetApp的许多解决方案的具体功能。

.人工智能(AI)和现代数据分析
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["NetApp AI 解决方案"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOps"^]


====
.企业级应用程序和数据库
[#db%collapsible]
====
【下划线】#*开源数据库视频*

.PostgreSQL自动部署、HA/DR复制设置、故障转移、重新同步
video::c381b887-8c8b-4d7d-8b0f-b0c0010c5c04[panopto,width=360]
[Underline]#*适用于Oracle数据库的视频*#

.借助iSCSI在NetApp ASA上简化和自动化Oracle部署
video::79095731-6b02-41d5-9fa1-b0c00100d055[panopto,width=360]
.第1部分—在AWS和FSx中使用混合云打造Oracle现代化
video::b1a7bb05-caea-44a0-bd9a-b01200f372e9[panopto,width=360]
.第2a部分—使用具有最大可用性的自动PDB重新定位将数据库从内部迁移到AWS
video::bb088a3e-bbfb-4927-bf44-b01200f38b17[panopto,width=360]
.第2b部分—使用BlueXP控制台通过SnapMirror将数据库从内部迁移到AWS
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto,width=360]
.第3部分—自动化数据库HA/DR复制设置、故障转移、重新同步
video::5fd03759-a691-4007-9748-b01200f3b79c[panopto,width=360]
.第4a部分—从复制的备用副本中使用SnapCenter UI进行开发/测试的数据库克隆
video::2f731d7c-0873-4a4d-8491-b01200f90a82[panopto,width=360]
.第4b部分—使用SnapCenter UI备份、还原和克隆数据库
video::97790d62-ff19-40e0-9784-b01200f920ed[panopto,width=360]
.第4c部分—数据库备份、使用BlueXP SaaS应用程序进行还原的备份和恢复
video::4b0fd212-7641-46b8-9e55-b01200f9383a[panopto,width=360]
【下划线】#* SQL Server数据库视频*

.使用适用于NetApp ONTAP 的Amazon FSX在AWS EC2上部署SQL Server
video::27f28284-433d-4273-8748-b01200fb3cd7[panopto,width=360]
.使用存储快照克隆Oracle多租户可插拔数据库
video::krzMWjrrMb0[youtube,width=360]
.借助 Ansible 在 FlexPod 上自动部署 Oracle 19c RAC
video::VcQMJIRzhoY[youtube,width=360]
*案例研究*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["基于 Azure NetApp Files 的 SAP"^]


====
.混合多云(HMC)
[#hmc%collapsible]
====
【下划线】#*适用于AWS/VMC*的视频#

.使用iSCSI使用FSX ONTAP 的Windows子系统连接存储
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.使用NFS使用FSX ONTAP 的Linux子系统连接存储
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
. 借助适用于NetApp ONTAP 的Amazon FSX、基于AWS的VMware Cloud可节省TCO
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.AWS上的VMware Cloud补充数据存储库、使用适用于NetApp ONTAP 的Amazon FSX
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.适用于VMC的VMware HCX部署和配置设置
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.使用VMware HCX for VMC和FSxN进行VMotion迁移演示
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.使用适用于VMC和FSxN的VMware HCX进行冷迁移演示
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
.使用iSCSI使用FSX ONTAP 的Windows子系统连接存储
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.使用NFS使用FSX ONTAP 的Linux子系统连接存储
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
. 借助适用于NetApp ONTAP 的Amazon FSX、基于AWS的VMware Cloud可节省TCO
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.AWS上的VMware Cloud补充数据存储库、使用适用于NetApp ONTAP 的Amazon FSX
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.适用于VMC的VMware HCX部署和配置设置
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.使用VMware HCX for VMC和FSxN进行VMotion迁移演示
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.使用适用于VMC和FSxN的VMware HCX进行冷迁移演示
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
【下划线】#*适用于Azure/AVS*的视频#

.Azure NetApp Files 中的Azure VMware解决方案 补充数据存储库概述
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
. 采用Cloud Volumes ONTAP 、SnapCenter 和Jetstream的Azure VMware解决方案 灾难恢复
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.使用适用于AVS和ANF的VMware HCX进行冷迁移演示
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.使用适用于AVS和ANF的VMware HCX进行VMotion演示
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.使用适用于AVS和ANF的VMware HCX进行批量迁移演示
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.采用Red Hat OpenShift的混合多云
[#rhhc%collapsible]
====
.使用A作用 力控制服务进行罗莎灾难恢复
video::01dd455e-7f5a-421c-b501-b01200fa91fd[panopto,width=360]
.将FSxN与Asta Trdent集成在一起
video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto,width=360]
.使用FSxN对ROSA上的应用程序进行故障转移和故障恢复
video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto,width=360]
[下划线]#*使用Astra Control Center*#进行灾难恢复

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["在NetApp TV上观看"]

.在Google Cloud Platform上安装OpenShift集群
video::4efc68f1-d37f-4cdd-874a-b09700e71da9[panopto,width=360]
.将OpenShift集群导入Astra Control Center
video::57b63822-6bf0-4d7b-b844-b09700eac6ac[panopto,width=360]
.使用Astra Control Center保护数据
video::0cec0c90-4c6f-4018-9e4f-b09700eefb3a[panopto,width=360]
.使用Asta Control Center执行故障转移故障恢复
video::1546191b-bc46-42eb-ac34-b0d60142c58d[panopto,width=360]
====
.虚拟化
[#virtualization%collapsible]
====
* link:virtualization/vsphere_demos_videos.html["VMware视频集"]


====
.容器/Kubernetes
[#containers%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html["NetApp与Google Anthos视频"]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html["NetApp与VMware Tanzu视频"]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html["NetApp for DevOps视频"]
* link:containers/rh-os-n_videos_and_demos.html["NetApp与Red Hat OpenShift视频"]


====
.解决方案自动化
[#automation%collapsible]
====
.借助 Ansible 在 FlexPod 上自动部署 Oracle 19c RAC
video::VcQMJIRzhoY[youtube,width=360]
====