---
sidebar: sidebar 
permalink: ehc/aws-storage-options.html 
keywords: aws, netapp, fsxn, storage, options, nfs, supplemental, cvo 
summary: NetApp存储可以作为子系统连接存储或补充存储连接到Azure VMware服务。 
---
= Amazon Web Services：用于使用NetApp存储的选项
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp存储可以作为子系统连接存储或补充存储连接到Amazon Web Services。



== Amazon FSx for NetApp ONTAP (FSx ONTAP)作为补充NFS数据存储库

Amazon FSx ONTAP为部署和管理应用程序工作负载以及文件服务提供了出色的选项、同时通过无缝满足应用程序层的数据要求来降低TCO。无论何种使用情形、都可以选择基于AWS的VMware Cloud以及Amazon FSx ONTAP、以快速实现云优势、一致的基础架构、从内部环境到AWS的运营、工作负载的双向可移植性以及企业级容量和性能。这是用于连接存储的熟悉过程。

有关详细信息、请访问：

* link:aws-native-overview.html["FSX ONTAP 作为补充NFS数据存储库：概述"]
* link:aws-native-nfs-datastore-option.html["Amazon FSx for ONTAP作为补充数据存储库"]




== Amazon FSx for NetApp ONTAP作为子系统连接存储

Amazon FSx ONTAP是一项完全托管的服务、可提供基于NetApp常用ONTAP文件系统构建的高度可靠、可扩展、高性能和功能丰富的文件存储。FSx ONTAP将NetApp文件系统的熟悉特性、性能、功能和API操作与完全托管的AWS服务的敏捷性、可扩展性和精简性相结合。

FSx ONTAP提供功能丰富、快速且灵活的共享文件存储、可从AWS或内部运行的Linux、Windows和macOS计算实例广泛访问。FSx ONTAP提供了高性能固态驱动器(Solid State Drive、SSD)存储、并且具有亚几级亚微型缓存。借助FSx ONTAP、您可以为工作负载实现SSD级别的性能、同时只需为一小部分数据购买SSD存储即可。

使用FSx ONTAP管理数据更加轻松、因为只需单击一个按钮、即可创建文件快照、克隆和复制。此外、FSx ONTAP会自动将数据分层到成本更低的弹性存储中、从而减少配置或管理容量的需求。

FSx ONTAP还提供高度可用且持久的存储、并具有完全托管的备份和跨区域灾难恢复支持。为了更轻松地保护和保障数据安全、FSx ONTAP支持常见的数据安全和防病毒应用程序。

有关详细信息、请访问link:aws-guest.html#fsx-ontap["FSX ONTAP 作为子系统连接存储"]



== Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储

Cloud Volumes ONTAP 是行业领先的云数据管理解决方案 、基于NetApp的ONTAP 存储软件构建、可在Amazon Web Services (AWS)、Microsoft Azure和Google Cloud Platform (GCP)上本机获得。

它是ONTAP 的软件定义版本、使用云原生存储、可以在云端和内部环境中使用相同的存储软件、从而减少了对IT员工进行全新数据管理方法培训的需求。

借助CVO、客户可以无缝地将数据从边缘、数据中心、云和云端来回移动、从而将混合云整合在一起—所有这些都通过一个单一窗格管理控制台NetApp Cloud Manager进行管理。

按照设计、CVO可提供极致性能和高级数据管理功能、即使在云中要求最苛刻的应用程序也能满足其需求。

有关详细信息，请访问link:aws-guest.html#aws-cvo["CVO作为来宾连接存储"]。
