---
sidebar: sidebar 
permalink: ehc/azure-avs.html 
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= 适用于 Azure AVS 的 NetApp 功能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
详细了解 NetApp 为 Azure VMware 解决方案（ AVS ）提供的功能—从作为子系统连接存储设备或原生数据存储库的 NetApp 到迁移工作流，扩展 / 突发到云，备份 / 还原和灾难恢复。

从以下选项中选择，跳至所需内容部分：

* link:#config["超大规模部署中的 VMware"]
* link:#datastore["NetApp 存储选项"]




== 在 Azure 中配置 AVS

与内部部署一样，规划基于云的虚拟化环境对于成功创建 VM 和迁移生产就绪环境至关重要。

与内部部署一样，规划 Azure VMware 解决方案对于成功创建 VM 和迁移生产就绪环境至关重要。

本节介绍如何设置和管理 Azure VMware 解决方案并将其与连接 NetApp 存储的可用选项结合使用。


NOTE: 将 Azure NetApp Files 和 Cloud Volumes ONTAP 连接到 Azure VMware 解决方案的唯一受支持方法是子系统内存储。

设置过程可细分为以下步骤：

* link:azure-setup.html#register["注册资源提供商并创建私有云"]
* link:azure-setup.html#connect["连接到新的或现有的 ExpressRoute 虚拟网络网关"]
* link:azure-setup.html#validate["验证网络连接并访问私有云"]




== 适用于 AVS 的 NetApp 存储选项

NetApp 存储可以通过多种方式在 Azure AVS 中用作 guess connected 或原生数据存储库。

请访问 link:ehc-support-configs.html["支持的 NetApp 存储选项"] 有关详细信息 ...

Azure 支持以下配置中的 NetApp 存储：

* 来宾连接存储 *

* link:azure-guest.html#anf["Azure NetApp Files （ ANF ）作为子系统连接的存储"]
* link:azure-guest.html#cvo["Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储"]


* 原生数据存储库 *

* link:https://azure.microsoft.com/en-us/updates/azure-netapp-files-datastores-for-azure-vmware-solution-is-coming-soon/["Azure NetApp Files （ ANF ）作为原生数据存储库^1."^]



NOTE: 1 —当前处于私有预览模式
