---
sidebar: sidebar 
permalink: ehc/ehc-summary.html 
keywords: NetApp Solutions, hybrid, multi-cloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= 总结和结论：为什么选择NetApp混合多云与VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp Cloud Volumes 以及适用于主要超大规模企业的 VMware 解决方案为希望利用混合云的企业提供了巨大的潜力。本节其余部分将介绍有关集成 NetApp Cloud Volumes 实现真正混合多云功能的用例。



== 用例 1 ：优化存储

在使用 RVtools 输出执行规模估算练习时，显而易见，功率（ vCPU/vMem ）与存储是并行的。企业往往会发现自己处于存储空间所需的驱动器大小远远超出所需的容量的情况。

通过集成 NetApp Cloud Volumes ，企业可以通过简单的迁移方法实现基于 vSphere 的 Cloud 解决方案，无需重新整合，无需 IP 更改，也无需架构更改。此外，通过这种优化，您可以扩展存储占用空间，同时将主机数量保持在 vSphere 所需的最低水平，但不会更改可用的存储层次结构，安全性或文件。这样，您可以优化部署并将总 TCO 降低 35 – 45% 。通过这种集成，您还可以在几秒钟内将存储从热存储扩展到生产级性能。



== 用例 2 ：云迁移

企业面临着将应用程序从内部数据中心迁移到公有云的压力，原因有多种：即将到期的租约；从资本支出（ capex ）支出迁移到运营支出（ opex ）支出的财务指令；或者只是自上而下的要求，将所有内容迁移到云。

速度至关重要时，只有简化的迁移方法才可行，因为要适应云的特定 IaaS 平台，重新整合和重构应用程序的速度缓慢且成本高昂，通常需要数月时间。将 NetApp Cloud Volumes 与为子系统连接的存储（包括 RDM 以及应用程序一致的 Snapshot 副本和 HCX ）提供的高效带宽 SnapMirror 复制相结合，从而实现云特定的迁移（例如 Azure Migrate ）或用于复制 VM 的第三方产品），这种过渡比依赖耗时的 I/O 筛选器机制更容易。



== 用例 3 ：数据中心扩展

当数据中心因季节性需求峰值或仅仅是稳定的有机增长而达到容量限制时，迁移到云托管的 VMware 以及 NetApp Cloud Volumes 是一项轻松的解决方案。利用 NetApp Cloud Volumes ，可以跨可用性区域提供高可用性并提供动态扩展功能，从而轻松创建，复制和扩展存储。利用 NetApp Cloud Volumes 可以消除对延伸型集群的需求，从而最大限度地减少主机集群容量。



== 用例 4 ：灾难恢复到云

在传统方法中，如果发生灾难，则复制到云的 VM 需要先转换到云自己的虚拟机管理程序平台，然后才能还原，而不是在危机期间处理的任务。

通过使用内部 SnapCenter 和 SnapMirror 复制以及公有云虚拟化解决方案将 NetApp Cloud Volumes 用于子系统连接的存储，可以设计一种更好的灾难恢复方法，以便在完全一致的 VMware SDDC 基础架构上恢复 VM 副本以及云专用恢复工具（例如 Azure Site Recovery ）或 Veeam 等第三方工具。此外，您还可以通过此方法快速执行灾难恢复演练并从勒索软件中恢复。这样，您还可以通过按需添加主机来扩展到完全生产环境，以供测试或在灾难期间使用。



== 用例 5 ：应用程序现代化

应用程序进入公有云后，企业将希望利用数百种功能强大的云服务来实现现代化和扩展。借助 NetApp Cloud Volumes ，现代化过程非常简单，因为应用程序数据不会锁定在 vSAN 中，并允许数据在包括 Kubernetes 在内的各种用例中移动。



== 结论

无论您是以全云还是混合云为目标， NetApp Cloud Volumes 都可以提供出色的选项来部署和管理应用程序工作负载以及文件服务和块协议，同时通过将数据需求无缝地迁移到应用程序层来降低 TCO 。

无论使用何种情形，都可以选择您最喜欢的云 / 超大规模云提供商以及 NetApp Cloud Volumes ，快速实现云优势，跨内部和多个云实现一致的基础架构和运营，工作负载的双向可移植性以及企业级容量和性能。

这是用于连接存储的熟悉过程。请记住，这只是数据位置随新名称而变化；工具和流程都保持不变， NetApp Cloud Volumes 有助于优化整体部署。
