---
sidebar: sidebar 
permalink: ehc/ehc-config-vmware-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration 
summary:  
---
= 在云提供商中配置虚拟化环境
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
此处详细介绍了如何在每个受支持的超大规模主机中配置虚拟化环境。



=== 适用于 AWS 的虚拟化环境配置（ VMC ）

本节介绍如何在 AWS SDDC 上设置和管理 VMware Cloud ，并将其与连接 NetApp 存储的可用选项结合使用。


NOTE: 只支持使用来宾存储将 FSX ONTAP 和 Cloud Volumes ONTAP 连接到 AWS VMC 。

设置过程可细分为以下步骤：

* link:aws/aws-setup.html#deploy["部署和配置适用于 AWS 的 VMware Cloud"]
* link:aws/aws-setup.html#connect["将 VMware Cloud 连接到 FSX ONTAP"]




=== 适用于 Azure 的虚拟化环境配置（ AVS ）

本节介绍如何设置和管理 Azure VMware 解决方案并将其与连接 NetApp 存储的可用选项结合使用。


NOTE: 将 Azure NetApp Files 和 Cloud Volumes ONTAP 连接到 Azure VMware 解决方案的唯一受支持方法是子系统内存储。

设置过程可细分为以下步骤：

* link:azure/azure-setup.html#register["注册资源提供商并创建私有云"]
* link:azure/azure-setup.html#connect["连接到新的或现有的 ExpressRoute 虚拟网络网关"]
* link:azure/azure-setup.html#validate["验证网络连接并访问私有云"]




=== GCP 虚拟化环境配置（ GCVE ）

本节介绍如何设置和管理 GCVE ，并将其与连接 NetApp 存储的可用选项结合使用。


NOTE: 来宾存储是将 Cloud Volumes ONTAP 和云卷服务连接到 GCVE 的唯一受支持方法。

设置过程可细分为以下步骤：

* link:gcp/gcp-setup.html#deploy["部署和配置 GCVE"]
* link:gcp/gcp-setup.html#enable-access["启用对 GCVE 的私有访问"]

