---
sidebar: sidebar 
permalink: ehc/ehc-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= 采用VMware的NetApp混合多云的用例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
概述在规划混合云或云优先部署时对 IT 组织至关重要的使用情形。



== 常见使用情形

使用情形包括：

* 灾难恢复，
* 在数据中心维护期间托管工作负载， * 快速激增，需要额外的资源，但不能满足本地数据中心的配置要求。
* VMware 站点扩展，
* 快速迁移到云，
* 开发 / 测试，和
* 利用 Cloud 原生技术实现应用程序现代化。


在本文档中、我们将使用VMware用例详细介绍云工作负载参考。这些用例包括：

* 保护(包括灾难恢复和备份/还原)
* 迁移
* 扩展




=== IT 发展历程中的一个过程

大多数企业都在经历转型和现代化之旅。在这一过程中，各家公司正在尝试利用现有的 VMware 投资，同时利用云优势并探索尽可能无缝地迁移过程的方法。这种方法将使他们的现代化工作变得非常简单，因为数据已经在云中。

在这种情况下，最简单的问题解答是每个超大规模提供商中的 VMware 产品。与 NetApp ® Cloud Volumes 一样， VMware 提供了一种将内部 VMware 环境迁移或扩展到任何云的方法，使您可以在云中本机运行工作负载的同时保留现有内部资产，技能和工具。这样可以降低风险，因为不会发生服务中断或需要更改 IP ，并使 IT 团队能够使用现有技能和工具在内部执行操作。这样可以加快云迁移速度，并更平稳地过渡到混合多云架构。



=== 了解原生存储选项的重要性

尽管 VMware 在任何云中都能为每个客户提供独特的混合功能，但有限的原生存储选项限制了它对存储繁重的工作负载企业的有用性。由于存储与主机直接相关，因此扩展存储的唯一方法是添加更多主机，这样对于存储密集型工作负载，成本可能会增加 35% – 40% 或更多。这些工作负载只需要额外的存储，而不是额外的功率。但这意味着需要为额外的主机付费。

我们来考虑一下这种情况：

客户只需要五台主机来满足 CPU 和内存需求，但需要大量存储需求，并需要 12 台主机来满足存储需求。这一要求最终确实会让财务规模大得多，因为他们只需要增加存储即可购买额外的动力。

在规划云采用和迁移时，始终需要评估最佳方法并采取最简单的方法来减少总投资。对于任何应用程序迁移，最常见且最简单的方法是重新托管（也称为提升和移动），在这种情况下不会进行虚拟机（ VM ）或数据转换。在将 NetApp Cloud Volumes 与 VMware 软件定义的数据中心（ SDDC ）结合使用的同时，还可以作为 vSAN 的补充，从而提供一个轻松的升降和移动选项。
