---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= 适用于公有云提供商的 NetApp 存储选项
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
了解 NetApp 在三大超大规模提供商中作为存储的各种选项。

[role="tabbed-block"]
====
.AWS/VMC
--
AWS 支持以下配置中的 NetApp 存储：

* FSX ONTAP 作为子系统连接的存储
* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* FSX ONTAP 作为补充NFS数据存储库


查看详细信息 link:aws/aws-guest.html["VMC的子系统连接存储选项"]。查看详细信息 link:aws/aws-native-nfs-datastore-option.html["VMC的补充NFS数据存储库选项"]。

--
.Azure / AVS
--
Azure 支持以下配置中的 NetApp 存储：

* Azure NetApp Files （ ANF ）作为子系统连接的存储
* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* Azure NetApp Files (ANF)作为补充NFS数据存储库


查看详细信息 link:azure/azure-guest.html["AVS的子系统连接存储选项"]。查看详细信息 link:azure/azure-native-nfs-datastore-option.html["AVS的补充NFS数据存储库选项"]。

--
.GCP / GCVE
--
Google Cloud 支持以下配置中的 NetApp 存储：

* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* Cloud Volumes Service （ CVS ）作为子系统连接的存储
* Cloud Volumes Service (CVS)作为补充NFS数据存储库


查看详细信息 link:gcp/gcp-guest.html["GCVE的子系统连接存储选项"]。

了解更多信息 link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["适用于Google Cloud VMware Engine的NetApp Cloud Volumes Service 数据存储库支持(NetApp博客)"^] 或 link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["如何使用NetApp CVS作为Google Cloud VMware Engine的数据存储库(Google博客)"^]

--
====