---
sidebar: sidebar 
permalink: ehc/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= 适用于 Google Cloud Platform GCVE 的 NetApp 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
详细了解NetApp为Google云平台(GCP) Google Cloud VMware Engine (GCVe)带来的功能—从作为子系统连接存储设备或补充NFS数据存储库的NetApp、到迁移工作流、扩展/扩充到云、备份/还原和灾难恢复。

从以下选项中选择，跳至所需内容部分：

* link:#config["在 GCP 中配置 GCVE"]
* link:#datastore["适用于 GCVE 的 NetApp 存储选项"]
* link:#solutions["NetApp/VMware云解决方案"]




== 在 GCP 中配置 GCVE

与内部部署一样，规划基于云的虚拟化环境对于成功创建 VM 和迁移生产就绪环境至关重要。

本节介绍如何设置和管理 GCVE ，并将其与连接 NetApp 存储的可用选项结合使用。


NOTE: 将Cloud Volumes ONTAP和Google Cloud NetApp卷连接到GCVE)时、唯一受支持的方法是子系统存储。

设置过程可细分为以下步骤：

* 部署和配置 GCVE
* 启用对 GCVE 的私有访问


查看详细信息 link:gcp-setup.html["GCVE的配置步骤"]。



== 适用于 GCVE 的 NetApp 存储选项

NetApp存储可以通过多种方式在GCP GCVE中用作guess connected或作为补充NFS数据存储库。

请访问 link:ehc-support-configs.html["支持的 NetApp 存储选项"] 有关详细信息 ...

Google Cloud 支持以下配置中的 NetApp 存储：

* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* Google Cloud NetApp卷(NetApp卷)作为子系统连接的存储
* Google Cloud NetApp卷(NetApp卷)作为补充NFS数据存储库


查看详细信息link:gcp-guest.html["GCVE的子系统连接存储选项"]。查看详细信息link:gcp-ncvs-datastore.html["GCVE的补充NFS数据存储库选项"]。

阅读有关或的更多信息link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Google Cloud NetApp Volumes数据存储库支持Google Cloud VMware引擎(NetApp博客)"^]link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["如何使用Google Cloud NetApp卷作为Google Cloud VMware Engine的数据存储库(Google博客)"^]



== 解决方案用例

借助 NetApp 和 VMware 云解决方案，许多用例都可以轻松部署在 Azure AVS 中。为VMware定义的每个云区域定义了SE案例：

* 保护(包括灾难恢复和备份/还原)
* 扩展
* 迁移


link:gcp-solutions.html["浏览适用于 Google Cloud GCVE 的 NetApp 解决方案"]
