---
sidebar: sidebar 
permalink: ehc/gcp-storage-options.html 
keywords: gcp, gcve, gcnv, nfs, supplemental, datastore, vcenter, vmware, cvo, storage, options 
summary: NetApp存储可以作为子系统连接存储或补充存储连接到Google云虚拟化引擎。 
---
= Google Cloud VMware Engine：用于使用NetApp存储的选项
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp存储可以作为子系统连接存储或补充存储连接到Google云虚拟化引擎。



== Google Cloud NetApp卷(NetApp卷)作为补充NFS数据存储库

如果客户需要在其Google Cloud VMware Engine (GCVe)环境中增加存储容量、则可以使用Google Cloud NetApp卷作为补充NFS数据存储库进行挂载。通过将数据存储在Google Cloud NetApp Volumes上、客户可以在不同区域之间进行复制、以防止灾难。

有关详细信息、请访问link:gcp-ncvs-datastore.html["Google Cloud NetApp卷(NetApp卷)作为补充NFS数据存储库"]



== NetApp CVO作为子系统连接存储

Cloud Volumes ONTAP 是行业领先的云数据管理解决方案 、基于NetApp的ONTAP 存储软件构建、可在Amazon Web Services (AWS)、Microsoft Azure和Google Cloud Platform (GCP)上本机获得。

它是ONTAP 的软件定义版本、使用云原生存储、可以在云端和内部环境中使用相同的存储软件、从而减少了对IT员工进行全新数据管理方法培训的需求。

借助CVO、客户可以无缝地将数据从边缘、数据中心、云和云端来回移动、从而将混合云整合在一起—所有这些都通过一个单一窗格管理控制台NetApp Cloud Manager进行管理。

按照设计、CVO可提供极致性能和高级数据管理功能、即使在云中要求最苛刻的应用程序也能满足其需求。

有关详细信息、请访问link:gcp-guest.html#gcp-cvo["NetApp CVO作为子系统连接存储"]



== Google Cloud NetApp卷(NetApp卷)作为子系统连接存储

可以从VMware引擎环境中创建的VM挂载Google Cloud NetApp卷共享。由于Google Cloud NetApp卷支持SMB和NFS协议、因此也可以在Linux客户端上挂载卷并将其映射到Windows客户端。只需简单的步骤即可设置Google Cloud NetApp卷。

Google Cloud NetApp Volumes和Google Cloud VMware引擎私有云必须位于同一区域。

有关详细信息、请访问link:gcp-guest.html#gcnv["Google Cloud NetApp卷(NetApp卷)作为子系统连接存储"]
