---
sidebar: sidebar 
permalink: hybrid-cloud/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 此页面提供了视频和教程的简介。 
---
= 混合云，桌面虚拟化和容器视频和演示
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


请参见以下视频和演示，其中重点介绍了混合云，桌面虚拟化和容器解决方案的特定功能。



== NetApp 与 VMware Tanzu

借助 VMware Tanzu ，客户可以通过 vSphere 或 VMware Cloud Foundation 部署，管理和管理 Kubernetes 环境。通过 VMware 的这一产品组合，客户可以选择最适合其需求的 VMware Tanzu 版本，从一个控制平台管理所有相关的 Kubernetes 集群。

有关 VMware Tanzu 的详细信息，请参见 https://tanzu.vmware.com/tanzu["VMware Tanzu 概述"^]。此审核涵盖使用情形，可用添加内容以及有关 VMware Tanzu 的更多信息。



== NetApp 与 VMware Tanzu 视频系列

* https://www.youtube.com/watch?v=ZtbXeOJKhrc["如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 1 部分"^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE["如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 2 部分"^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU["如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 3 部分"^]




== 采用 Red Hat OpenShift 的 NetApp

Red Hat OpenShift 是一款企业级 Kubernetes 平台，可用于运行采用开放式混合云策略的基于容器的应用程序。Red Hat OpenShift 作为领先公有云上的云服务或自助管理软件提供，可为客户提供设计基于容器的解决方案所需的灵活性。

有关 Red Hat OpenShift 的详细信息，请参见此部分 https://www.redhat.com/en/technologies/cloud-computing/openshift["Red Hat OpenShift 概述"^]。您还可以查看产品文档和部署选项，了解有关 Red Hat OpenShift 的更多信息。



== NetApp 与 Red Hat OpenShift 视频

* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html["工作负载迁移—采用 NetApp 的 Red Hat OpenShift"^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html["Red Hat OpenShift Deployment on RHV ：采用 NetApp 的 Red Hat OpenShift"^]

