---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_overview_storint.html 
keywords: Astra, Astra Control Center, Trident, Astra Trident, persistent storage 
summary: NetApp提供了许多产品、可帮助客户在基于容器的环境中编排和管理永久性数据、例如Anthos。 
---
= NetApp 存储集成概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/




== Anthos Ready存储合作伙伴计划。

Google Cloud会定期通过其Anthos Ready存储合作伙伴计划请求对合作伙伴存储与新版本Anthos的集成进行更新验证。您可以找到当前已验证的存储解决方案、CSI驱动程序、可用功能以及支持的Anthos版本的列表 https://cloud.google.com/anthos/docs/resources/partner-storage["此处"^]。

NetApp一直定期遵守这些请求、每季度对符合Astra Trident CSI的存储编排程序以及采用Anthos版本的ONTAP 和Element存储系统进行验证。

下表列出了在Anthos Ready存储合作伙伴计划中由NetApp和NetApp合作伙伴工程师针对NetApp Astra Trident CSI驱动程序和功能集验证进行测试的Anthos版本：

|===


| 部署类型 | version | 存储系统 | Astra Trident版本 | 协议 | 功能 


| VMware | 1.10 | ONTAP | 22.01 | NAS | Multiwriter、卷扩展、快照 


| VMware | 1.10 | ONTAP | 22.01 | SAN | 原始块、卷扩展、快照 


| VMware | 1.10 | Element | 22.01 | SAN | 原始块、卷扩展、快照 


| 裸机 | 1.10 | ONTAP | 22.01 | NAS | Multiwriter、卷扩展、快照 


| 裸机 | 1.10 | ONTAP | 22.01 | SAN | 原始块、卷扩展、快照 
|===


== NetApp 存储集成

NetApp提供了许多产品、可帮助您在基于容器的环境(如Anthos)中编排和管理永久性数据。

NetApp Astra Trident是一款开源且完全受支持的存储编排程序、适用于容器和Kubernetes分发软件(包括Anthos)。有关详细信息，请访问 Astra Trident 网站 https://docs.netapp.com/us-en/trident/index.html["此处"]。

以下页面介绍了有关已通过NetApp解决方案 在Anthos中的应用程序和永久性存储管理验证的NetApp产品的追加信息 ：

* link:a-w-n_overview_trident.html["NetApp Astra Trident"]


link:a-w-n_overview_advanced.html["接下来：高级配置选项：采用NetApp的Anthos。"]
