---
sidebar: sidebar 
permalink: infra/rhv-1._configure_management_switches.html 
keywords: Cisco	switches, VLAN, LACP, vPCs, in-band, out-of-band 
summary:  
---
= 1. 配置管理交换机：采用 RHV 的 NetApp HCI
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
此部署操作步骤中使用了 Cisco Nexus 3048 交换机，以便为计算和存储节点的带内和带外管理提供 1 Gbps 连接。这些步骤将在交换机机架安装，通电并完成初始设置过程后开始。要配置交换机以提供与基础架构的管理连接，请完成以下步骤：



=== 为 Cisco Nexus 启用高级功能

在每个 Cisco Nexus 3048 交换机上运行以下命令以配置高级功能：

. 进入配置模式：
+
....
Switch-01# configure terminal
....
. 启用 VLAN 功能。
+
....
Switch-01(config)# feature interface-vlan
....
. 启用 LACP 。
+
....
Switch-01(config)# feature lacp
....
. 启用虚拟端口通道（ vPC ）。
+
....
Switch-01(config)# feature vpc
....
. 设置全局端口通道负载平衡配置。
+
....
Switch-01(config)# port-channel load-balance src-dst ip-l4port
....
. 执行全局生成树配置


....
Switch-01(config)# spanning-tree port type network default
Switch-01(config)# spanning-tree port type edge bpduguard default
....


=== 配置交换机上的端口以进行带内管理

. 运行以下命令创建 VLAN 以进行管理：
+
....
Switch-01(config)# vlan 2
Switch-01(config-vlan)# Name Native_VLAN
Switch-01(config-vlan)# vlan 16
Switch-01(config-vlan)# Name OOB_Network
Switch-01(config-vlan)# vlan 1172
Switch-01(config-vlan)# Name MGMT_Network
Switch-01(config-vlan)# exit
....
. 将端口 eth1/2-32 配置为连接到每个 HCI 存储节点上的管理接口的 VLAN 中继端口。


....
Switch-01(config)# int eth 1/29
Switch-01(config-if)# description HCI-STG-01 PortA
Switch-01(config-if)# switchport mode trunk
Switch-01(config-if)# switchport trunk native vlan 2
Switch-01(config-if)# switchport trunk allowed vlan 1172
Switch-01(config-if)# spanning tree port type edge trunk
Switch-01(config-if)# int eth 1/30
Switch-01(config-if)# description HCI-STG-02 PortA
Switch-01(config-if)# switchport mode trunk
Switch-01(config-if)# switchport trunk native vlan 2
Switch-01(config-if)# switchport trunk allowed vlan 1172
Switch-01(config-if)# spanning tree port type edge trunk
Switch-01(config-if)# int eth 1/31
Switch-01(config-if)# description HCI-STG-03 PortA
Switch-01(config-if)# switchport mode trunk
Switch-01(config-if)# switchport trunk native vlan 2
Switch-01(config-if)# switchport trunk allowed vlan 1172
Switch-01(config-if)# spanning tree port type edge trunk
Switch-01(config-if)# int eth 1/32
Switch-01(config-if)# description HCI-STG-04 PortA
Switch-01(config-if)# switchport mode trunk
Switch-01(config-if)# switchport trunk native vlan 2
Switch-01(config-if)# switchport trunk allowed vlan 1172
Switch-01(config-if)# spanning tree port type edge trunk
Switch-01(config-if)# exit
....


=== 配置交换机上的端口以进行带外管理

运行以下命令，配置用于为每个 HCI 节点上的 IPMI 接口布线的端口。

....
Switch-01(config)# int eth 1/13
Switch-01(config-if)# description HCI-CMP-01 IPMI
Switch-01(config-if)# switchport mode access
Switch-01(config-if)# switchport access vlan 16
Switch-01(config-if)# spanning-tree port type edge
Switch-01(config-if)# int eth 1/14
Switch-01(config-if)# description HCI-STG-01 IPMI
Switch-01(config-if)# switchport mode access
Switch-01(config-if)# switchport access vlan 16
Switch-01(config-if)# spanning-tree port type edge
Switch-01(config-if)# int eth 1/15
Switch-01(config-if)# description HCI-STG-03 IPMI
Switch-01(config-if)# switchport mode access
Switch-01(config-if)# switchport access vlan 16
Switch-01(config-if)# spanning-tree port type edge
Switch-01(config-if)# exit
....

NOTE: 在经验证的配置中，我们使用缆线将奇节点 IPMI 接口连接到 Switch-01 ，并将偶节点 IPMI 接口连接到 Switch-02 。



=== 创建 vPC 域以确保容错

. 激活两台交换机之间用于 vPC 对等链路的端口。
+
....
Switch-01(config)# int eth 1/1
Switch-01(config-if)# description vPC peer-link Switch-02 1/1
Switch-01(config-if)# int eth 1/2
Switch-01(config-if)# description vPC peer-link Switch-02 1/2
Switch-01(config-if)# exit
....
. 执行 vPC 全局配置。


....
Switch-01(config)# vpc domain 1
Switch-01(config-vpc-domain)# role priority 10
Switch-01(config-vpc-domain)# peer-keepalive destination <switch-02_mgmt_address> source <switch-01_mgmt_address> vrf managment
Switch-01(config-vpc-domain)# peer-gateway
Switch-01(config-vpc-domain)# auto recovery
Switch-01(config-vpc-domain)# ip arp synchronize
Switch-01(config-vpc-domain)# int eth 1/1-2
Switch-01(config-vpc-domain)# channel-group 10 mode active
Switch-01(config-vpc-domain)# int Po10
Switch-01(config-if)# description vPC peer-link
Switch-01(config-if)# switchport mode trunk
Switch-01(config-if)# switchport trunk native vlan 2
Switch-01(config-if)# switchport trunk allowed vlan 16, 1172
Switch-01(config-if)# spanning-tree port type network
Switch-01(config-if)# vpc peer-link
Switch-01(config-if)# exit
....
link:rhv-2._configure_data_switches.html["下一步： 2.配置数据交换机"]
