---
sidebar: sidebar 
permalink: vmw-sc/sc-use-cases.html 
keywords: NetApp Solutions, vmware, sovereign cloud, netapp, use case 
summary:  
---
= 采用VMware Sovereign Cloud的NetApp：用例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp通过集成多种NetApp技术、为VMware Sovereign Cloud概念提供支持。

使用以下链接详细了解NetApp技术与VMware Sovereover Cloud的集成：

* link:#storageGRID["NetApp StorageGRID作为对象存储扩展"]




== NetApp StorageGRID作为对象存储扩展

NetApp已与VMware合作、将NetApp StorageGRID集成到VMware Cloud Director中、以支持VMware Sovereign云。此VMware Cloud Director插件支持服务提供商使用StorageGRID作为其对象存储产品(无论使用情形如何)、并允许通过服务提供商用来管理其产品目录中其他部分的相同VMware多租户解决方案(VMware Cloud Director)进行StorageGRID管理。

提供VMware主权云的合作伙伴可以选择NetApp StorageGRID来帮助他们管理和维护包含非结构化数据的云环境。它在为Amazon S3 API等行业标准API提供本机支持方面实现了通用兼容性、有助于确保在各种云环境之间实现顺畅的互操作性、而自动化生命周期管理等独特创新有助于确保更经济高效地保护、存储和长期保留客户的非结构化数据。

NetApp的Sovereign Cloud与Cloud Director集成为客户提供以下优势：

* 确保敏感数据(包括元数据)仍受主权控制、同时防止可能违反数据隐私法律的外国当局访问。
* 提高安全性和合规性、保护应用程序和数据免受快速演变的攻击向量的影响、同时保持与可信本地系统的持续合规性。基础架构、内置框架和本地专家。
* 打造适应未来需求的基础架构、快速应对不断变化的数据隐私法规、安全威胁和地缘政治。
* 能够通过安全的数据共享和分析释放数据的价值、从而在不违反隐私法律的情况下推动创新。数据完整性受到保护、可确保获得准确的洞察力。


有关StorageGRID集成的详细信息、请查看以下内容：

* link:https://www.netapp.com/newsroom/press-releases/news-rel-20231107-561294/["NetApp公告"]

