---
sidebar: sidebar 
permalink: containers/a-w-n_LB_SeeSaw.html 
summary: 此页面详细介绍了seesaw负载平衡器的安装和配置说明。 
keywords: Anthos, GKE, Kubernetes, SeeSaw, LoadBalancer 
---
= 安装seesaw负载平衡器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
此页面列出了seesaw受管负载平衡器的安装和配置说明。

seesaw是VMware环境中安装在Anthos Clusters 1.6到1.10版的默认受管网络负载平衡器。



== 安装seesaw负载平衡器

seesaw负载平衡器与VMware上的Anthos集群完全集成、并在管理和用户集群设置中自动执行部署。`cluster.YAML`配置文件中存在文本块、必须进行修改才能提供负载平衡器信息、然后在部署集群之前、还需要执行一个额外步骤、使用内置的`gkectl`工具部署负载平衡器。


NOTE: 可以在HA或非HA模式下部署seesaw负载平衡器。为了进行此验证、seesaw负载平衡器部署在非HA模式下、这是默认设置。出于生产目的、NetApp建议在HA配置中部署seesaw、以实现容错和可靠性。



== 与Anthos集成

每个配置文件中分别为管理集群和您选择部署的每个用户集群提供了一个部分、用于配置负载平衡器、以便由Anthos on-Prem管理。

以下文本是GKE-Admin集群分区配置的示例。需要取消注释和修改的值以粗体文本显示在下方：

[listing, subs="+quotes,+verbatim"]
----
*loadBalancer:*
  # (Required) The VIPs to use for load balancing
  *vips:*
    # Used to connect to the Kubernetes API
    *controlPlaneVIP: "10.61.181.230"*
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" or "ManualLB". Uncomment
  # the corresponding field below to provide the detailed spec
  *kind: Seesaw*
  # # (Required when using "ManualLB" kind) Specify pre-defined nodeports
  # manualLB:
  #   # NodePort for ingress service's http (only needed for user cluster)
  #   ingressHTTPNodePort: 0
  #   # NodePort for ingress service's https (only needed for user cluster)
  #   ingressHTTPSNodePort: 0
  #   # NodePort for control plane service
  #   controlPlaneNodePort: 30968
  #   # NodePort for addon service (only needed for admin cluster)
  #   addonsNodePort: 31405
  # # (Required when using "F5BigIP" kind) Specify the already-existing partition and
  # # credentials
  # f5BigIP:
  #   address:
  #   credentials:
  #     username:
  #     password:
  #   partition:
  #   # # (Optional) Specify a pool name if using SNAT
  #   # snatPoolName: ""
  # (Required when using "Seesaw" kind) Specify the Seesaw configs
  *seesaw:*
  # (Required) The absolute or relative path to the yaml file to use for IP allocation
  #  for LB VMs. Must contain one or two IPs.
  *ipBlockFilePath: "admin-seesaw-block.yaml"*
  #   (Required) The Virtual Router IDentifier of VRRP for the Seesaw group. Must
  #   be between 1-255 and unique in a VLAN.
    *vrid: 100*
  #   (Required) The IP announced by the master of Seesaw group
    *masterIP: "10.61.181.236"*
  #   (Required) The number CPUs per machine
    *cpus: 1*
  #   (Required) Memory size in MB per machine
    *memoryMB: 2048*
  #   (Optional) Network that the LB interface of Seesaw runs in (default: cluster
  #   network)
    *vCenter:*
  #   vSphere network name
      *networkName: VM_Network*
  #   (Optional) Run two LB VMs to achieve high availability (default: false)
    *enableHA: false*
----
seesaw负载平衡器还具有一个单独的静态`seesaw-block.yaml`文件、您必须为每个集群部署提供该文件。此文件必须位于与`cluster.yaml`部署文件相关的同一目录中、或者必须在上述部分中指定完整路径。

`admin-seesaw-block.yaml`文件的示例类似于以下脚本：

[listing, subs="+quotes,+verbatim"]
----
blocks:
  - netmask: "255.255.255.0"
    gateway: "10.63.172.1"
    ips:
    - ip: "10.63.172.152"
      hostname: "admin-seesaw-vm"
----

NOTE: 此文件提供负载平衡器为底层集群提供的网络的网关和网络掩码、以及为运行负载平衡器而部署的虚拟机的管理IP和主机名。
