---
sidebar: sidebar 
permalink: containers/a-w-n_solution_overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Trident 
summary: 本参考文档对部署在多数据中心环境中且经过NetApp和我们的工程合作伙伴验证的NetApp解决方案 中的Anthos进行了部署验证。 
---
= NVA-1165：采用NetApp的Anthos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


NetApp公司Banu Sundharand Suresh ThopPay

[role="lead"]
本参考文档将对部署在多个数据中心环境中的Anthos与NetApp解决方案 进行部署验证。此外、还详细介绍了如何使用Trident存储流程编排程序管理永久性存储、从而实现与NetApp存储系统的存储集成。最后、我们将探讨并记录许多解决方案 验证和实际使用情形。



== 用例

采用NetApp解决方案 的Anthos旨在为客户提供卓越的价值、其使用情形如下：

* 使用在裸机上提供的`bmctl`工具或在VMware vSphere上使用`gkectl`工具部署的Anthos环境、易于部署和管理。
* 将企业级容器和虚拟化工作负载的强大功能与几乎部署在vSphere上或裸机上的Anthos相结合 https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["kubevirt"^]。
* 与NetApp存储和Trident (适用于Kubnetes的开源存储流程编排程序)结合使用时、介绍Anthos功能的实际配置和用例。




== 业务价值

企业越来越多地采用 DevOps 实践来创建新产品，缩短发布周期并快速添加新功能。由于容器和微服务本身的灵活性，它们在支持 DevOps 实践方面发挥着至关重要的作用。但是，在企业环境中以生产规模实施 DevOps 会带来自身的挑战，并对底层基础架构提出一些要求，例如：

* 堆栈中所有层的高可用性
* 易于部署过程
* 无中断运行和升级
* API 驱动的可编程基础架构，可跟上微服务灵活性的步伐
* 具有性能保证的多租户
* 能够同时运行虚拟化和容器化工作负载
* 能够根据工作负载需求独立扩展基础架构


采用NetApp解决方案 的Anthos认识到这些挑战、并提供了一个解决方案 、通过在客户选择的数据中心环境中在内部实施完全自动化的Anthos部署、帮助解决每个问题。



== 技术概述

采用NetApp解决方案 的Anthos包含以下主要组件：



=== Prem上的Anthos

Prem上的Anthos是一款完全受支持的企业级Kubernetes平台、可以部署在VMware vSphere虚拟机管理程序中或您选择的裸机基础架构上。

有关 Anthos 的详细信息，请参见位于的 Anthos 网站 https://cloud.google.com/anthos["此处"^]。



=== NetApp 存储系统

NetApp 拥有多个存储系统，非常适合企业数据中心和混合云部署。NetApp产品组合包括NetApp ONTAP、Cloud Volumes ONTAP、Google Cloud NetApp Volumes、Azure NetApp Files、FSx ONTAP for NetApp ONTAP存储系统、所有这些都可以为容器化应用程序提供永久性存储。

有关详细信息，请访问 NetApp 网站 https://www.netapp.com["此处"]。



=== NetApp 存储集成

Trident是一款完全受支持的开源存储流程编排程序、适用于容器和Kub并 网分发(包括Anthos)。

有关详细信息，请访问Trident网站 https://docs.netapp.com/us-en/trident/index.html["此处"]。



== 高级配置选项

本节专门介绍实际用户在将此解决方案部署到生产环境中时可能需要执行的自定义设置，例如创建专用私有映像注册表或部署自定义负载平衡器实例。



== 已验证版本的当前支持列表

请参见 https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["此处"] 已验证版本的支持列表。
