---
sidebar: sidebar 
permalink: containers/a-w-n_overview_storint.html 
keywords: Trident, Trident, persistent storage 
summary: NetApp提供了许多产品、可帮助客户在Anthos等基于容器的环境中编排和管理持久数据。 
---
= NetApp 存储集成概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp提供了许多产品、可帮助客户在Anthos等基于容器的环境中编排和管理持久数据。



== Anthos Ready存储合作伙伴计划。

Google Cloud会定期通过其Anthos Ready存储合作伙伴计划请求对合作伙伴存储与新版本Anthos的集成进行更新验证。您可以找到当前已验证的存储解决方案、CSI驱动程序、可用功能以及支持的Anthos版本的列表 https://cloud.google.com/anthos/docs/resources/partner-storage["此处"^]。

NetApp每季度定期保持合规性、并要求验证我们符合Trident CSI的存储编排程序以及使用Anthos版本的ONTAP存储系统。

下表列出了NetApp和NetApp合作伙伴工程师针对NetApp Trident CSI驱动程序和功能集验证测试的Anthos版本、这些版本是Anthos就绪存储合作伙伴计划的一部分：

|===


| 部署类型 | version | 存储系统 | Trident版本 | 协议 | 功能 


| VMware | 1.28 | ONTAP 9.12.1 | 24.02. | NAS | Multiwriter、卷扩展、快照、PVCDataSource 


| VMware | 1.28 | ONTAP 9.12.1 | 24.02. | SAN | 原始块、卷扩展、快照、PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04. | NAS | Multiwriter、卷扩展、快照、PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04. | SAN | 原始块、卷扩展、快照、PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | NAS | Multiwriter、卷扩展、快照、PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | SAN | 原始块、卷扩展、快照、PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | NAS | Multiwriter、卷扩展、快照、PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | SAN | 原始块、卷扩展、快照、PVCDataSource 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | NAS | Multiwriter、卷扩展、快照 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | SAN | 原始块、卷扩展、快照 


| VMware | 1.11 | 要素 12.3 | 22.04 | SAN | 原始块、卷扩展、快照 


| 裸机 | 1.10 | ONTAP 9.8 | 22.01 | NAS | Multiwriter、卷扩展、快照 


| 裸机 | 1.10 | ONTAP 9.8 | 22.01 | SAN | 原始块、卷扩展、快照 
|===


== NetApp 存储集成

NetApp提供了许多产品、可帮助您在基于容器的环境(如Anthos)中编排和管理永久性数据。

NetApp Trident是一款完全受支持的开源存储流程编排程序、适用于容器和Kub并 网分发(包括Anthos)。有关详细信息，请访问Trident网站 https://docs.netapp.com/us-en/trident/index.html["此处"]。

以下页面介绍了有关已在采用NetApp解决方案 的Anthos中针对应用程序和永久性存储管理进行验证的NetApp产品的追加信息。
