---
sidebar: sidebar 
permalink: containers/anthos_concept_overview.html 
summary: 采用 Anthos 的 NetApp HCI 是一款经验证的最佳混合云架构，用于以可靠的方式部署内部 Google Kubernetes Engine （ GKEE ）环境。本 NetApp 经验证的架构参考文档既可作为设计指南，也可作为解决方案上的 Anthos NetApp HCI 的部署验证。 
keywords: Kubernetes, GKE, NVA-1141 
---
= NVA-1141 ：采用 Anthos 的 NetApp HCI ，设计和部署


Alan Cowles

本文档中介绍的计划解决方案经过精心设计和全面测试，可最大限度地降低部署风险并加快上市速度。

本文档面向 NetApp 和合作伙伴解决方案工程师以及客户战略决策者。本节介绍了用于确定支持经验证的工作负载所需的特定设备，布线和配置的架构设计注意事项。

采用 Anthos 的 NetApp HCI 是一款经验证的最佳混合云架构，用于以可靠的方式部署内部 Google Kubernetes Engine （ GKEE ）环境。本 NetApp 经验证的架构参考文档既可作为设计指南，也可作为解决方案上的 Anthos NetApp HCI 的部署验证。本文档所述的架构已通过 NetApp 和 Google 的主题专家的验证，可以在您自己的企业数据中心环境中运行 NetApp HCI 上的 Anthos 。

NetApp HCI 是业内首款领先的分解式混合云基础架构，可提供超融合解决方案的广泛认可优势。其优势包括降低了 TCO ，简化了虚拟化工作负载的采集，部署和管理，同时还允许企业客户根据需要独立扩展计算和存储资源。采用 Anthos 的 NetApp HCI 为部署由内部 Anthos GKEE 管理的容器化工作负载提供了内部类似云的体验。此解决方案可提供简化的管理，详细的指标和一系列其他功能，从而可以轻松移动现场和云中部署的工作负载。



== 功能

借助 NetApp HCI for Anthos ，您可以在内部数据中心部署完全集成的生产级 Anthos GKEE 环境，从而利用以下功能：

* NetApp HCI 计算和存储节点
+
** 专为混合云工作负载设计的企业级超融合基础架构
** NetApp Element 存储软件
** 基于 Intel 的服务器计算节点，包括适用于 Nvidia GPU 的选项


* VMware vSphere 6.7U3
+
** 用于部署和管理虚拟基础架构的企业级虚拟机管理程序解决方案


* Google Cloud 和内部环境中的 Anthos GKE
+
** 在 Google Cloud 或 NetApp HCI 上部署 Anthos GKEE 实例




经验证的 NetApp 架构计划为客户提供针对特定工作负载和使用情形的参考配置和规模估算指导。

link:anthos_concept_solution_components.html["接下来：解决方案组件"]
