---
sidebar: sidebar 
permalink: containers/bmanthos_introduction.html 
keywords: WP-7337, Google Cloud, Cloud Volumes ONTAP, Cloud Volume Service, hypervisor, Kubernetes 
summary: NetApp 和 Google Cloud 之间的关系已有多年， NetApp 率先通过 Cloud Volumes ONTAP 和 Cloud Volumes Service 向 Google Cloud 推出云数据服务。然后，我们对 NetApp HCI 平台进行了验证，使其能够与内部环境中部署的 Google Cloud Anthos 结合使用，这是一种基于虚拟机管理程序的混合多云 Kubernetes 解决方案，部署在 VMware vSphere 上。然后， NetApp 通过了 NetApp Trident ， ONTAP 和 NFS 协议的 Anthos Ready 认证，为容器提供动态持久存储。 
---
= WP-7337 ：《裸机上的 Anthos 》
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp 公司 Alan Cowles 和 Nikhil M Kulkarni

NetApp 和 Google Cloud 之间的关系已有多年， NetApp 首次通过 Cloud Volumes ONTAP 和 Cloud Volumes Service 为 Google Cloud 推出云数据服务。然后，我们对 NetApp HCI 平台进行了验证，使其能够与内部环境中部署的 Google Cloud Anthos 结合使用，这是一种基于虚拟机管理程序的混合多云 Kubernetes 解决方案，部署在 VMware vSphere 上。然后， NetApp 通过了 NetApp Trident ， ONTAP 和 NFS 协议的 Anthos Ready 认证，为容器提供动态持久存储。

现在， Anthos 可以直接安装在客户环境中的裸机服务器上，这为客户提供了一个额外的选项，可以在不使用虚拟机管理程序的情况下将 Google Cloud 扩展到其本地数据中心。此外，通过利用 NetApp ONTAP 存储操作系统和 NetApp Trident 的功能，您可以通过为容器集成永久性存储来扩展平台的功能。

通过这种组合，您可以充分发挥服务器，存储和网络的全部潜能，并获得 Google Cloud 提供的支持，服务级别，每月计费和按需灵活性。由于您使用的是自己的硬件，网络和存储，因此您可以直接控制应用程序的规模，安全性和网络延迟，还可以利用裸机上的 Anthos 实现托管和容器化应用程序的优势。

link:bmanthos_solution_overview.html["接下来：解决方案概述。"]
