---
sidebar: sidebar 
permalink: containers/dwn_solution_overview.html 
keywords: DevOps, Netapp, Astra Trident, Astra Control, Astra 
summary: 本技术报告概述了NetApp如何在使用容器化应用程序时、在多个方面轻松高效地使用DevOps用例。首先、我们将利用Astra产品组合详细介绍NetApp存储系统及其与Kubernetes平台的集成。最后，我们还探讨并记录了许多解决方案验证和实际使用情形。 
---
= TR-4919：《采用NetApp Astra的DevOps》
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/
:k8s_distribution_name: Red Hat OpenShift, VMware Tanzu, Anthos by Google Cloud etc.


[role="lead"]
本技术报告概述了NetApp如何在使用容器化应用程序时、在多个方面轻松高效地使用DevOps用例。首先、我们将利用Astra产品组合详细介绍NetApp存储系统及其与Kubernetes平台的集成。最后，我们还探讨并记录了许多解决方案验证和实际使用情形。

NetApp 公司 Alan Cowles 和 Nikhil M Kulkarni



== 用例

采用NetApp Astra解决方案 的开发运营旨在为客户提供卓越的价值、其使用情形如下：

* 易于部署和管理在受支持的Kubernetes分发版上部署的应用程序和开发环境。
* 讨论DevOps工作流的实际使用情形、以及NetApp可提供的工具和方法示例、以使这些方法更易于采用和使用。
* 探索如何使用应用程序一致的快照、备份和克隆来增强DevOps体验。




== 业务价值

企业越来越多地采用 DevOps 实践来创建新产品，缩短发布周期并快速添加新功能。由于容器和微服务本身的灵活性，它们在支持 DevOps 实践方面发挥着至关重要的作用。但是，在企业环境中以生产规模实施 DevOps 会带来自身的挑战，并对底层基础架构提出一些要求，例如：

* 堆栈中所有层的高可用性、因此工作流不会中断。
* 为最终用户简化部署和管理过程。
* API驱动的可编程基础架构、可跟上微服务和开发人员灵活性的步伐。
* 能够根据工作负载需求以自动化方式独立扩展基础架构。
* 保护应用程序及其为DevOps工作流提供支持的永久性数据集、无需依赖重新部署或手动复制数据、加快了产品上市速度。


本技术报告认识到这些功能和挑战、概述了使用广泛的NetApp产品组合改进和简化容器化应用程序的DevOps用例的过程。



== 技术概述

采用NetApp解决方案 的DevOps包含以下主要组件：



=== DevOps实践

DevOps实践侧重于自动化、可重复且易于管理的操作、通过允许最终用户控制其代码开发环境来增强开发工作流。本解决方案 提供了几个示例和用例、其中NetApp技术可为这些操作带来最大优势。



=== 容器编排

目前使用的容器业务流程平台数量众多。虽然其中大多数平台都基于Kubernetes、但每个平台都有利弊。因此、在为DevOps工作流选择容器编排平台时、了解功能集和集成非常重要。借助NetApp Astra产品套件、我们可以为以下平台提供全面的DevOps用例支持：

* https://www.redhat.com/en/technologies/cloud-computing/openshift["Red Hat OpenShift"] 4.6.8+
* https://rancher.com/["Rancher"] 2.5以上
* https://kubernetes.io/["Kubernetes"] 1.20以上
* https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/index.html["VMware Tanzu Kubernetes网格"] 1.4及更高版本
* https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid-Integrated-Edition/index.html["VMware Tanzu Kubernetes Grid Integrated Edition"] 1.12.2+




=== NetApp 存储系统

NetApp 拥有多个存储系统，非常适合企业数据中心和混合云部署。NetApp 产品组合包括 NetApp ONTAP ， NetApp Element 和 NetApp E 系列存储系统，所有这些系统均可为容器化应用程序提供永久性存储。

有关详细信息、请访问NetApp网站 https://www.netapp.com["此处"]。



=== NetApp 存储集成

NetApp Astra控制中心为部署在内部环境中并采用值得信赖的NetApp数据保护技术的有状态Kubernetes工作负载提供丰富的存储和应用程序感知型数据管理服务。

有关详细信息，请访问 NetApp Astra 网站 https://cloud.netapp.com/astra["此处"]。

Astra Trident是一款开源且完全受支持的存储编排程序、适用于｛K8s_distribution_name｝等容器和Kubernetes分发版。

有关详细信息，请访问 Astra Trident 网站 https://docs.netapp.com/us-en/trident/index.html["此处"]。
