---
sidebar: sidebar 
permalink: containers/rh-os-rhv_best_practices_for_production_deployments.html 
summary: 在 NetApp HCI 上部署 Red Hat OpenShift 的最佳实践 
keywords: best practices, VM, Virtual Machine, Host affinity, custom install file, customized install 
---
= 生产部署最佳实践—基于 RHV 的适用于 Red Hat OpenShift 的 NetApp HCI
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本节列出了企业在将此解决方案部署到生产环境之前应考虑的几个最佳实践。



=== 将 OpenShift 部署到至少包含三个节点的 RHV 集群

本文档中介绍的经验证的架构介绍了适用于 HA 操作的最低硬件部署，具体方法是部署两个 RHV-H 虚拟机管理程序节点，并确保采用容错配置，两个主机均可管理托管引擎，而已部署的虚拟机可在两个虚拟机管理程序之间迁移。由于 Red Hat OpenShift 最初使用三个主节点进行部署，因此在双节点配置中，可以确保至少有两个主节点将占用同一节点，如果特定节点不可用，可能会导致 OpenShift 中断。因此， Red Hat 的最佳实践是，在解决方案中至少部署三个 RHV-H 虚拟机管理程序节点，以便 OpenShift 主节点可以均匀分布，并且解决方案可以获得更多的容错能力。



=== 配置虚拟机 / 主机关联性

通过启用虚拟机 / 主机关联性，可确保在多个虚拟机管理程序节点之间分布 OpenShift 主节点。关联性是一种为一组 VM 和 / 或主机定义规则的方法，用于确定这些 VM 是在组中的同一主机上运行还是在不同主机上运行。它通过创建由具有一组相同参数和条件的 VM 和 / 或主机组成的关联组来应用于 VM 。根据关联组中的 VM 是在组中的同一主机上运行，还是在不同主机上单独运行，此关联组的参数可以定义正关联性或负关联性。为参数定义的条件可以是强制实施，也可以是软强制实施。强制实施可确保关联组中的 VM 始终严格遵循正 / 负关联性，而不考虑外部条件。另一方面，软强制实施可确保在可行的情况下为关联组中的 VM 设置更高的优先级，以便遵循正 / 负关联性。在本文档所述的两个或三个虚拟机管理程序配置中，建议使用软关联性设置，在较大的集群中，可以依赖硬关联性来确保 OpenShift 节点的分布。要配置相关性组，请参见 https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html/virtual_machine_management_guide/sect-affinity_groups["Red Hat 6.11 。关联性组文档"^]。



=== 使用自定义安装文件进行 OpenShift 部署

通过本文档前面讨论的交互式向导， IPI 可以轻松部署 OpenShift 集群。但是，在集群部署过程中，可能需要更改某些默认值。在这些情况下，无需立即部署集群，即可运行向导并为其分配任务，而是输出一个配置文件，以便稍后可以从该配置文件中部署集群。如果需要更改任何 IPI 默认设置，或者用户希望在其环境中部署多个相同的集群以用于多租户等其他用途，则此功能非常有用。有关为 OpenShift 创建自定义安装配置的详细信息，请参见 https://docs.openshift.com/container-platform/4.4/installing/installing_rhv/installing-rhv-customizations.html["Red Hat OpenShift 通过自定义在 RHV 上安装集群"^]。

link:rh-os-rhv_videos_and_demos.html["接下来：视频和演示： Red Hat 虚拟化上的适用于 Red Hat OpenShift 的 NetApp HCI"]
