---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= 视频和演示：采用 NetApp 的 Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
以下视频演示了本文档中介绍的一些功能：

.使用Amazon FSx for NetApp ONTAP在ROSA上实时迁移OpenShift虚拟化中的虚拟机
video::4b3ef03d-7d65-4637-9dab-b21301371d7d[panopto,width=360]
.可通过Ansight自动化在OpenShift集群上部署Trident和创建存储类
video::fae6605f-b61a-4a34-a97f-b1ed00d2de93[panopto,width=360]
link:https://github.com/NetApp/trident-install["可在GitHub中找到使用Ans得 安装NetApp Trident、StorageClasses和后端的操作手册。"]

.使用ONTAP SAN (iSCSI)存储类在OpenShift虚拟化中部署新VM
video::2e2c6fdb-4651-46dd-b028-b1ed00d37da3[panopto,width=360]
.使用ONTAP NAS存储类部署PostgreSQL容器应用程序
video::d3eacf8c-888f-4028-a695-b1ed00d28dee[panopto,width=360]
.Cloud Insights与OpenShift虚拟化的集成
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.使用Red Hat VtTM通过NetApp ONTAP存储将VM迁移到OpenShift虚拟化
video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto,width=360]
.使用Trident的高级数据管理功能对OpenShift VM进行故障转移/故障恢复(仅提供早期使用计划)
video::f2a8fa24-2971-4cdc-9bbb-b1f1007032ea[panopto,width=360]
.Cloud Insights与OpenShift虚拟化的集成
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.可通过Ansight自动化在OpenShift集群上部署Trident和创建存储类
video::fae6605f-b61a-4a34-a97f-b1ed00d2de93[panopto,width=360]
** GitHub中的Ans负责 代码示例**link:https://github.com/NetApp/trident-install["可在GitHub中找到使用Ans得 安装NetApp Trident、StorageClasses和后端的操作手册。"]

.使用ONTAP NAS存储类部署PostgreSQL容器应用程序
video::d3eacf8c-888f-4028-a695-b1ed00d28dee[panopto,width=360]
.借助Astra Control和NetApp FlexClone技术加快软件开发速度—采用NetApp的Red Hat OpenShift
video::26b7ea00-9eda-4864-80ab-b01200fa13ac[panopto,width=360]
.利用 NetApp Astra Control 执行数据剖析和恢复应用程序
video::3ae8eb53-eda3-410b-99e8-b01200fa30a8[panopto,width=360]
.Astra Control Center在CI/CD管道中保护数据
video::a6400379-52ff-4c8f-867f-b01200fa4a5e[panopto,width=360]
.使用Asta控制中心迁移工作负载—采用NetApp的Red Hat OpenShift
video::e397e023-5204-464d-ab00-b01200f9e6b5[panopto,width=360]
.工作负载迁移—采用 NetApp 的 Red Hat OpenShift
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]
.安装OpenShift虚拟化—使用NetApp的Red Hat OpenShift
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]
.使用OpenShift虚拟化部署虚拟机—采用NetApp的Red Hat OpenShift
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.基于 Red Hat 虚拟化的适用于 Red Hat OpenShift 的 NetApp HCI
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]