---
sidebar: sidebar 
permalink: containers/rh-os-rhv_design_considerations.html 
keywords: network, VLAN, IPMI, OCP 
summary:  
---
= 设计注意事项：基于 RHV 的适用于 Red Hat OpenShift 的 NetApp HCI
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




=== 网络设计

HCI 解决方案上的 RHV 上的 Red Hat OpenShift 使用两个数据交换机以 25 Gbps 的速度提供主数据连接。它还使用两个额外的管理交换机，这些交换机以 1 Gbps 的速度提供连接，用于存储节点的带内管理以及 IPMI 功能的带外管理。OCP 使用 RHV 上的逻辑网络进行集群管理。本节介绍解决方案中使用的每个虚拟网段的布局和用途，并概述了部署解决方案的前提条件。



==== VLAN 要求

基于 RHV 解决方案的 NetApp HCI for Red Hat OpenShift 旨在通过使用虚拟局域网（ VLAN ）在逻辑上隔离不同用途的网络流量。NetApp HCI 至少需要三个网段。但是，可以扩展此配置以满足客户需求，或者为特定网络服务提供进一步隔离。下表列出了实施解决方案所需的 VLAN ，以及稍后在经验证的架构部署中使用的特定 VLAN ID 。

|===
| VLAN | 目的 | VLAN ID 


| 带外管理网络 | HCI 节点和 IPMI 的管理 | 16. 


| 带内管理网络 | 管理 HCI 节点， ovirtmgmt 和 VM | 1172. 


| 存储网络 | NetApp Element 的存储网络 | 3343 


| 迁移网络 | 用于虚拟子系统迁移的网络 | 3345 
|===


==== 网络基础架构支持资源

在 NetApp HCI 解决方案上的 Red Hat 虚拟化上部署 OpenShift 容器平台（ OCP ）之前，应具备以下基础架构：

* 至少一个 DNS 服务器，该服务器可提供完整的主机名解析，可从带内管理网络和 VM 网络访问。
* 至少可从带内管理网络和 VM 网络访问一个 NTP 服务器。
* （可选）带内管理网络和 VM 网络的出站 Internet 连接。
* RHV 集群应至少具有 28 个 vCPU ， 112 GB RAM 和 840GB 可用存储（具体取决于生产工作负载要求）。


link:rh-os-rhv_deployment_summary.html["下一步：在 RHV 上部署适用于 Red Hat OpenShift 的 NetApp HCI"]
