---
sidebar: sidebar 
permalink: containers/rh-os-rhv-9._download_and_install_netapp_trident.html 
keywords: Installation, Trident, OCP Cluster, storage backend 
summary:  
---
= 9. 在 RHV 上下载并安装 NetApp Trident ：适用于 Red Hat OpenShift 的 NetApp HCI
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
要下载并安装 NetApp Trident ，请完成以下步骤：

. 确保登录到 OCP 集群的用户具有足够的权限来安装 Trident 。
+
....
[user@rhel7 openshift-deploy]$ oc auth can-i '*' '*' --all-namespaces
 yes
....
. 验证您是否可以从注册表下载映像并访问 NetApp Element 集群的 MVIP 。
+
....
[user@rhel7 openshift-deploy]$ oc run -i --tty ping --image=busybox --restart=Never --rm -- ping 10.63.172.140
If you don't see a command prompt, try pressing enter.
64 bytes from 10.63.172.140: seq=1 ttl=63 time=0.312 ms
64 bytes from 10.63.172.140: seq=2 ttl=63 time=0.271 ms
64 bytes from 10.63.172.140: seq=3 ttl=63 time=0.254 ms
64 bytes from 10.63.172.140: seq=4 ttl=63 time=0.309 ms
64 bytes from 10.63.172.140: seq=5 ttl=63 time=0.319 ms
64 bytes from 10.63.172.140: seq=6 ttl=63 time=0.303 ms
^C
--- 10.63.172.140 ping statistics ---
7 packets transmitted, 7 packets received, 0% packet loss
round-trip min/avg/max = 0.254/0.387/0.946 ms
pod "ping" deleted
....
. 使用以下命令下载 Trident 安装程序包并将其解压缩到目录中。
+
....
[user@rhel7 ~]$ wget
[user@rhel7 ~]$ tar -xf trident-installer-20.04.0.tar.gz
[user@rhel7 ~]$ cd trident-installer
....
. Trident 安装程序包含用于定义所有所需资源的清单。使用适当的清单创建 TridentProvider 自定义资源定义。
+
....
[user@rhel7 trident-installer]$ oc create -f deploy/crds/trident.netapp.io_tridentprovisioners_crd_post1.16.yaml

customresourcedefinition.apiextensions.k8s.io/tridentprovisioners.trident.netapp.io created
....
. 创建 Trident 命名空间， Trident 操作符需要使用此命名空间。
+
....
[user@rhel7 trident-installer]$ oc create namespace trident
namespace/trident created
....
. 创建 Trident 操作员部署所需的资源，例如操作员的 ServiceAccount ， ServiceAccount 的 ClusterRole 和 ClusterRoleBinding/ 专用 PodSecurityPolicy 或操作员本身。
+
....
[user@rhel7 trident-installer]$ oc kustomize deploy/ > deploy/bundle.yaml
[user@rhel7 trident-installer]$ oc create -f deploy/bundle.yaml
serviceaccount/trident-operator created
clusterrole.rbac.authorization.k8s.io/trident-operator created
clusterrolebinding.rbac.authorization.k8s.io/trident-operator created
deployment.apps/trident-operator created
podsecuritypolicy.policy/tridentoperatorpods created
....
. 验证是否已部署 Trident 操作员。
+
....
[user@rhel7 trident-installer]$ oc get deployment -n trident
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
trident-operator   1/1     1            1           56s
[user@rhel7 trident-installer]$ oc get pods -n trident
NAME                               READY   STATUS    RESTARTS   AGE
trident-operator-564d7d66f-qrz7v   1/1     Running   0          71s
....
. 安装 Trident 操作符后，使用此操作符安装 Trident 。在此示例中，创建了 TridentProvider 自定义资源（ CR ）。Trident 安装程序附带了用于创建 TridentProvider CR 的定义。可以根据需要修改这些设置。
+
....
[user@rhel7 trident-installer]$ oc create -f deploy/crds/tridentprovisioner_cr.yaml
tridentprovisioner.trident.netapp.io/trident created
....
. 使用 `oc get csr -o name` xargs oc adm certificate approve 来批准提供 CSR 证书的 Trident 。
+
....
[user@rhel7 trident-installer]$ oc get csr -o name | xargs oc adm certificate approve
certificatesigningrequest.certificates.k8s.io/csr-4b7zh approved
certificatesigningrequest.certificates.k8s.io/csr-4hkwc approved
certificatesigningrequest.certificates.k8s.io/csr-5bgh5 approved
certificatesigningrequest.certificates.k8s.io/csr-5g4d6 approved
certificatesigningrequest.certificates.k8s.io/csr-5j9hz approved
certificatesigningrequest.certificates.k8s.io/csr-5m8qb approved
certificatesigningrequest.certificates.k8s.io/csr-66hv2 approved
certificatesigningrequest.certificates.k8s.io/csr-6rdgg approved
certificatesigningrequest.certificates.k8s.io/csr-6t24f approved
certificatesigningrequest.certificates.k8s.io/csr-76wgv approved
certificatesigningrequest.certificates.k8s.io/csr-78qsq approved
certificatesigningrequest.certificates.k8s.io/csr-7r58n approved
certificatesigningrequest.certificates.k8s.io/csr-8ghmk approved
certificatesigningrequest.certificates.k8s.io/csr-8sn5q approved
....
. 使用 Trident 配置程序 CR 验证是否已安装 Trident 20.04 ，并验证与 Trident 相关的 Pod 是否已安装。
+
....
[user@rhel7 trident-installer]$ oc get tprov -n trident
NAME      AGE
trident   9m49s

[user@rhel7 trident-installer]$ oc describe tprov trident -n trident
Name:         trident
Namespace:    trident
Labels:       <none>
Annotations:  <none>
API Version:  trident.netapp.io/v1
Kind:         TridentProvisioner
Metadata:
  Creation Timestamp:  2020-05-26T18:49:19Z
  Generation:          1
  Resource Version:    640347
  Self Link:           /apis/trident.netapp.io/v1/namespaces/trident/tridentprovisioners/trident
  UID:                 52656806-0414-4ed8-b355-fc123fafbf4e
Spec:
  Debug:  true
Status:
  Message:  Trident installed
  Status:   Installed
  Version:  v20.04
Events:
  Type    Reason      Age                    From                        Message
  ----    ------      ----                   ----                        -------
  Normal  Installing  9m32s                  trident-operator.netapp.io  Installing Trident
  Normal  Installed   3m47s (x5 over 8m56s)  trident-operator.netapp.io  Trident installed
[user@rhel7 trident-installer]$ oc get pods -n trident
NAME                               READY   STATUS    RESTARTS   AGE
trident-csi-7f769c7875-s6fmt       5/5     Running   0          10m
trident-csi-cp7wg                  2/2     Running   0          10m
trident-csi-hhx94                  2/2     Running   0          10m
trident-csi-l72bt                  2/2     Running   0          10m
trident-csi-xfl9d                  2/2     Running   0          10m
trident-csi-xrhqx                  2/2     Running   0          10m
trident-csi-zb7ws                  2/2     Running   0          10m
trident-operator-564d7d66f-qrz7v   1/1     Running   0          27m

[user@rhel7 trident-installer]$ ./tridentctl -n trident version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 20.04.0        | 20.04.0        |
+----------------+----------------+
....
. 创建一个存储后端， Trident 将使用该后端来配置卷。存储后端在 NetApp HCI 中指定 Element 集群。您还可以使用相应的 QoS 规格指定铜牌，银牌和金牌类型示例。
+
....
[user@rhel7 trident-installer]$ vi backend.json
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin: admin- password@10.63.172.140/json-rpc/8.0",
    "SVIP": "10.61.185.205:3260",
    "TenantName": "trident",
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}
[user@rhel7 trident-installer]$ ./tridentctl -n trident create backend -f backend.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| solidfire_10.61.185.205 | solidfire-san  | 40f48d99-5d2e-4f6c-89ab-8aee2be71255 | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
....
+
修改 `backend.json` 以满足以下值的环境详细信息或要求：

+
** 端点对应于 NetApp HCI Element 集群的凭据和 MVIP 。
** SVIP 对应于标题为的一节中通过 VM 网络配置的 SVIP link:redhat_openshift_1._create_storage_network_vlan__netapp_hci_for_red_hat_openshift_on_rhv.html["创建存储网络 VLAN"]。
** 类型对应于不同的 QoS 带。可以通过指定确切的存储池来使用特定 QoS 设置创建新的永久性卷。


. 创建一个存储类，将 Trident 指定为配置程序，并将存储后端指定为 `solidfire-san` 。


....
[user@rhel7 trident-installer]$ vi storage-class-basic.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "solidfire-san"
  provisioningType: "thin"

[user@rhel7 trident-installer]$ oc create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic created
....

NOTE: 在此示例中，创建的 StorageClass 设置为默认值，但是 OpenShift 管理员可以根据不同的 QoS 要求以及其他因素根据其应用程序定义多个存储类。Trident 会选择一个可满足存储类定义的参数部分中指定的所有条件的存储后端。然后，最终用户可以根据需要配置存储，而无需管理干预。

link:rh-os-rhv_validation_results.html["接下来：验证结果：基于 RHV 的适用于 Red Hat OpenShift 的 NetApp HCI"]
