---
sidebar: sidebar 
permalink: dp-sec/cleondris_disaster_recovery_overview.html 
keywords: DR	Disaster, TR-4380, 4830, tr4830, continuity, application catalog 
summary:  
---
= TR-4830 ：使用 Cleondris 实现 NetApp HCI 灾难恢复
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp 公司 Michael White



== 业务连续性和灾难恢复概述

业务连续性和灾难恢复（ Business Continuity and Disaster Recovery ， BCDr ）模式是为了让员工恢复工作。灾难恢复侧重于将电子邮件服务器等技术恢复为现实。通过业务连续性，用户可以访问该电子邮件服务器。单是灾难恢复就意味着该技术正在运行，但可能没有人在使用它； BCDr 意味着人们已经开始使用已恢复的技术。



== 业务影响评估

很难知道第 1 层应用程序需要什么才能正常运行。通常很明显，身份验证服务器和 DNS 非常重要。但是，是否也有数据库服务器？

此信息非常重要，因为您需要打包第 1 层应用程序，以便它们在测试故障转移和实际故障转移中都能正常工作。会计公司可以执行业务影响评估（ BIA ），为您提供成功保护应用程序所需的所有信息：例如，确定所需组件，应用程序所有者以及应用程序的最佳支持人员。



== 应用程序目录

如果您没有 BIA ，则可以自己执行某个版本的操作：应用程序目录。通常会在电子表格中填写以下字段：应用程序名称，组件，要求，所有者，支持， 支持电话号码以及赞助商或业务应用程序所有者。此类目录对于保护您的应用程序非常重要且非常有用。帮助台有时可以帮助您处理应用程序目录；他们通常已经启动了一个应用程序目录。



== 不需要保护的内容

某些应用程序不应受到保护。例如，您可以轻松且经济地在灾难恢复站点上将域控制器作为虚拟机（ VM ）运行，因此无需保护。事实上，恢复域控制器可能会在恢复期间出现发生原因问题。如果在灾难恢复站点中恢复了生产站点中使用的监控软件，则该软件不一定适用于灾难恢复站点。

通常没有必要保护可通过高可用性进行保护的应用程序。高可用性是可能的最佳保护；其故障转移时间通常不到一秒。因此，灾难恢复流程编排工具不应保护这些应用程序，但高可用性可以。例如，银行中支持 ATM 的软件。

您可以看出，如果应用程序所有者制定了 20 秒恢复时间目标（ RTO ），您需要了解应用程序的高可用性解决方案。RTO 不仅仅是复制解决方案。



== 产品概述

Cleondris HCI 控制中心（ HCC ）为新的和现有的 NetApp HCI 部署添加了灾难恢复功能。它与 NetApp SolidFire 存储引擎完全集成，可以保护任何类型的数据和应用程序。当客户站点发生故障时，可以使用 HCC 恢复二级 NetApp HCI 站点上的所有数据，包括基于策略的 VM 启动流程编排。

为多个卷设置复制可能会很耗时，并且在手动执行时容易出错。HCC 可以为其复制向导提供帮助。此向导可帮助正确设置复制，以便在发生灾难时服务器可以访问卷。使用 HCC ，可以在沙盒中的二级系统上启动 VMware 环境，而不会影响生产。VM 将在隔离的网络中启动，并可进行功能测试。
