---
sidebar: sidebar 
permalink: vdi-vds/citrix_netapp_value.html 
keywords: Data fabric, Cloud Volumes ONTAP, Azure NetApp Files, ShareFile, filecache 
summary: 利用 NetApp 提供支持的 Data Fabric 构建的基础架构，您可以将数据迁移或执行从一个站点到另一个站点（包括云）的灾难恢复。通过 Cloud Insights ，您可以监控，优化公有云以及私有数据中心中部署的资源并对其进行故障排除。 
---
= NetApp 价值
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




=== Data Fabric

利用 NetApp 提供支持的 Data Fabric 构建的基础架构，您可以将数据迁移或执行从一个站点到另一个站点（包括云）的灾难恢复。Citrix 虚拟应用程序和桌面中的数据可分为以下几类：

* 基础架构组件
* 计算机映像
* 应用程序
* 用户配置文件
* 用户数据


根据您的需求，可以将站点配置为主动 / 主动或主动 / 被动。基础架构组件可以在内部或云中使用，并可作为服务进行访问。要配置桌面和应用程序池，必须将 VM 模板分发到每个站点。应用程序层，用户配置文件和数据存储在 SMB 文件共享中，这些文件共享必须在每个站点上可用。

您可以在大多数用户所在位置使用 Azure NetApp Files ， NetApp Cloud Volumes ONTAP 和 FlexGroup 卷创建全局命名空间。其他位置可以使用全局文件缓存在文件服务器上本地缓存内容。如果首选 Citrix ShareFile ，则 NetApp StorageGRID 可提供与 S3 兼容的高性能存储，以便通过 NAS 网关访问在内部托管数据。



=== Cloud Insights

通过 Cloud Insights ，您可以监控，优化公有云以及私有数据中心中部署的资源并对其进行故障排除。

Cloud Insights 可通过以下方式为您提供帮助：

* * 将平均解决时间缩短多达 90% 。 * 停止长时间的日志查找并无法手动关联基础架构；使用我们的动态拓扑和关联分析立即确定问题区域。
* * 将云基础架构成本平均降低 33% 。 * 通过确定已废弃和未使用的资源以及适当规模的工作负载以优化性能和成本层，消除低效问题。
* * 防止多达 80% 的云问题影响最终用户。 * 通过使用高级分析和机器学习功能在问题发生严重中断之前识别问题，停止搜索大量数据以查找相关项目。

