---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_nvidia_licensing.html 
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC 
summary: 使用 H610C 或 H615C 时， GPU 的许可证必须从有权转售许可证的 NVIDIA 合作伙伴处购买。 
---
= NVIDIA 许可
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
使用 H610C 或 H615C 时， GPU 的许可证必须从有权转售许可证的 NVIDIA 合作伙伴处购买。您可以找到 NVIDIA 与的合作伙伴 https://["配对节点定位器"^]。搜索虚拟 GPU （ vGPU ）或 Tesla 等能力。

NVIDIA vGPU 软件有四个版本：

* NVIDIA GRID 虚拟 PC （ GRID vPC ）
* NVIDIA GRID 虚拟应用程序（ GRID vApp ）
* NVIDIA Quadro 虚拟数据中心工作站（ Quadro vDWS ）
* NVIDIA Virtual ComputeServer （ vComputeServer ）




== 网格虚拟 PC

此产品非常适合希望使用虚拟桌面为 Microsoft Windows 应用程序，浏览器，高清视频和多显示器支持提供卓越用户体验的用户。NVIDIA GRID 虚拟 PC 可在虚拟环境中提供原生体验，让您可以以全性能运行所有 PC 应用程序。



== 网格虚拟应用程序

网格 vApp 适用于部署远程桌面会话主机（ RDSH ）或其他应用程序流式或基于会话的解决方案的组织。网格 vApp 还支持 Windows Server 托管的 RDSH 桌面，旨在以全性能交付 Microsoft Windows 应用程序。



== Quadro 虚拟数据中心工作站

本版本非常适合使用功能强大的 3D 内容创建应用程序的主流和高端设计人员，例如，达索 CATIA ， SOLIDWORKS ， 3dexcite ， Siemens NX ， PTC 克里奥， Schlumberg器 Petrel 或 Autodesk Maya 。通过 NVIDIA Quadro vDWS ，用户可以在任何设备上访问具有全部功能和性能的专业图形应用程序。



== NVIDIA Virtual ComputeServer

许多组织都运行计算密集型服务器工作负载，例如人工智能（ AI ），深度学习（ DL ）和数据科学。对于这些使用情形， NVIDIA vComputeServer 软件可虚拟化 NVIDIA GPU ，从而通过错误更正代码，页面停用，通过 NVLink 对等和多 vGPU 等功能加快计算密集型服务器工作负载的速度。


NOTE: 使用 Quadro vDWS 许可证，您可以使用网格 vPC 和 NVIDIA vComputeServer 。

link:hcvdivds_deployment.html["下一步：部署"]
