---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_solutions_for_industry.html 
keywords: GPU, Azure, NVIDIA, Tesla M60, 
summary: 图形工作站通常用于制造业，医疗保健，能源，媒体和娱乐，教育， 架构等。对于图形密集型应用程序，移动性往往受到限制。 
---
= 行业解决方案
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


图形工作站通常用于制造业，医疗保健，能源，媒体和娱乐，教育， 架构等。对于图形密集型应用程序，移动性往往受到限制。

为了解决移动性问题描述问题，虚拟桌面服务可以使用云中的硬件资源或 NetApp HCI 为从任务员工到专家用户的所有类型的员工提供桌面环境，包括灵活的 GPU 配置选项。VDS 支持用户使用笔记本电脑，平板电脑和其他移动设备从任意位置访问工作环境。

要使用 ANSYS Fluent ， ANSYS MechanIC ， AutoDESCad ， AutoDESCIGAN ， AutoDESCUTE VENIGAN ， AutoDESCKS Max 等软件运行制造工作负载， ｛ \f4 ｝ ｛ \f4 ｝ ｛ \f4 ｝ ｛ \f4 ｝ ｛ Systèmes \f4 ｝ ｛ \f4 ｝ ｛ \f4 ｝ ｛ \f4 ｝ ｛ \f4 ｝ ｛ \f4 ｝ ｛ Systèmes 下表列出了各种云（截至 2021 年 1 月）上可用的 GPU 。

[cols="20,20,20,20,20"]
|===
| GPU 型号 | Microsoft Azure | Google 计算（ GCP ） | Amazon Web Services （ AWS ） | 内部部署（ NetApp HCI ） 


| NVIDIA M60 | 是的。 | 是的。 | 是的。 | 否 


| NVIDIA T4 | 否 | 是的。 | 是的。 | 是的。 


| NVIDIA P100 | 否 | 是的。 | 否 | 否 


| NVIDIA P4 | 否 | 是的。 | 否 | 否 
|===
此外，还提供与其他用户的共享桌面会话以及专用个人桌面。虚拟桌面可以具有一到四个 GPU ，也可以在 NetApp HCI 中使用部分 GPU 。NVIDIA T4 是一款多功能 GPU 卡，可满足各种用户工作负载的需求。NetApp HCI H615C 上的每个 GPU 卡都有 16 GB 的帧缓冲区内存，每个服务器有三个卡。可以托管在一个 H615C 服务器上的用户数量取决于用户工作负载。

[cols="25,25,25,25"]
|===
| 用户 / 服务器 | 轻型（ 4 GB ） | 中型（ 8 GB ） | 重磅（ 16 GB ） 


| H615C | 12 | 6. | 3. 
|===
要确定用户类型，请在用户使用执行典型任务的应用程序时运行 GPU 配置程序工具。GPU 配置程序可捕获内存需求，显示数量以及用户所需的分辨率。然后，您可以选择满足您要求的 vGPU 配置文件。

使用 GPU 的虚拟桌面可支持高达 8K 的显示分辨率，而实用程序 nView 可将一个监控器拆分为多个区域，以便使用不同的数据集。

借助 ONTAP 文件存储，您可以实现以下优势：

* 一个命名空间，可通过 4000 亿个文件增长到 20 PB 的存储空间，而无需大量管理输入
* 一种可通过全局文件缓存跨越全球的命名空间
* 利用受管 NetApp 存储实现安全多租户
* 使用 NetApp FabricPool 将冷数据迁移到对象存储
* 通过文件系统分析快速提供文件统计信息
* 将存储集群扩展到多达 24 个节点，以提高容量和性能
* 能够使用配额控制存储空间，并具有 QoS 限制的性能保障
* 通过加密保护数据安全
* 满足广泛的数据保护和合规性要求
* 提供灵活的业务连续性选项


link:vdi-vds/hcvdivds_conclusion.html["接下来：总结。"]
