---
sidebar: sidebar 
permalink: virtualization/vmware-scv-overview.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= 适用于 VMware vSphere 的 SnapCenter 插件
:allow-uri-read: 




== 适用于 VMware vSphere 的 SnapCenter 插件

[role="lead"]
适用于VMware vSphere的SnapCenter插件可为虚拟机(VM)、数据存储库和VMDK提供快速、高效且VM一致的备份和还原操作。它可与SnapCenter服务器配合使用、为SnapCenter应用程序专用插件提供基于应用程序的备份和还原功能。



=== 文档资源

有关详细信息、请参见以下文档资源。

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["适用于 VMware vSphere 的 SnapCenter 插件文档"]




=== 解决方案资源

请参阅以下3-2-1备份解决方案、其中包含适用于VMware vSphere的SnapCenter插件以及适用于VM的BlueXP备份和恢复。

技术报告： link:../ehc/bxp-scv-hybrid-solution.html["3-2-1使用SnapCenter插件和适用于VM的BlueXP备份和恢复为VMware提供数据保护"]

Tech OnTap博客： link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["3-2-1使用SnapCenter插件和适用于VM的BlueXP备份和恢复为VMware提供数据保护"]



=== 视频资源

.适用于 VMware vSphere 的 SnapCenter 插件—解决方案 前提条件
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.适用于 VMware vSphere 的 SnapCenter 插件—部署
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.适用于 VMware vSphere 的 SnapCenter 插件—备份工作流
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.适用于 VMware vSphere 的 SnapCenter 插件—还原工作流
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter — SQL 还原工作流
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]