---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: 此页面提供了视频和教程的简介。 
---
= 虚拟化视频和演示
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
请参见以下视频和演示、其中重点介绍了混合云、虚拟化和容器解决方案的特定功能。

.适用于 VMware vSphere 的 NetApp ONTAP 工具
[%collapsible]
====
.适用于VMware的ONTAP 工具—概述
video::e8071955-f6f1-45a0-a868-b12a010bba44[panopto]
.使用ONTAP 配置VMware iSCSI数据存储库
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.使用ONTAP 配置VMware NFS数据存储库
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.适用于 VMware vSphere 的 SnapCenter 插件
[%collapsible]
====
NetApp SnapCenter 软件是一款易于使用的企业平台，可安全地协调和管理应用程序，数据库和文件系统之间的数据保护。

您可以使用适用于 VMware vSphere 的 SnapCenter 插件对 VM 执行备份，还原和连接操作，并对直接在 VMware vCenter 中向 SnapCenter 注册的数据存储库执行备份和挂载操作。

有关适用于 VMware vSphere 的 NetApp SnapCenter 插件的详细信息，请参见 link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["适用于 VMware vSphere 的 NetApp SnapCenter 插件概述"]。

.适用于 VMware vSphere 的 SnapCenter 插件—解决方案 前提条件
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.适用于 VMware vSphere 的 SnapCenter 插件—部署
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.适用于 VMware vSphere 的 SnapCenter 插件—备份工作流
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.适用于 VMware vSphere 的 SnapCenter 插件—还原工作流
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter — SQL 还原工作流
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.3-2-1数据保护解决方案
[%collapsible]
====
3-2-1数据保护解决方案使用SnapMirror技术将内部主备份和二级备份与使用BlueXP备份和恢复将复制的副本整合到对象存储中。

.3-2-1使用适用于VMware vSphere的SnapCenter插件和适用于虚拟机的BlueXP备份和恢复对VMFS数据存储库进行数据保护
video::7c21f3fc-4025-4d8f-b54c-b0e001504c76[panopto,width=360]
====
.采用AWS FSX for NetApp ONTAP 的AWS上的VMware云
[%collapsible]
====
.使用iSCSI使用FSX ONTAP 的Windows子系统连接存储
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.使用NFS使用FSX ONTAP 的Linux子系统连接存储
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.借助适用于NetApp ONTAP 的Amazon FSX、基于AWS的VMware Cloud可节省TCO
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.AWS上的VMware Cloud补充数据存储库、使用适用于NetApp ONTAP 的Amazon FSX
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.适用于VMC的VMware HCX部署和配置设置
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.使用VMware HCX for VMC和FSxN进行VMotion迁移演示
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.使用适用于VMC和FSxN的VMware HCX进行冷迁移演示
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.采用Azure NetApp Files (ANF)的Azure上的Azure VMware服务
[%collapsible]
====
.Azure NetApp Files 中的Azure VMware解决方案 补充数据存储库概述
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.采用Cloud Volumes ONTAP 、SnapCenter 和Jetstream的Azure VMware解决方案 灾难恢复
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.使用适用于AVS和ANF的VMware HCX进行冷迁移演示
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.使用适用于AVS和ANF的VMware HCX进行VMotion演示
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.使用适用于AVS和ANF的VMware HCX进行批量迁移演示
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.VMware Cloud Foundation与NetApp ONTAP
[%collapsible]
====
.NFS数据存储库作为VCF工作负载域的主要存储
video::9b66ac8d-d2b1-4ac4-a33c-b16900f67df6[panopto]
.iSCSI存储库作为VCF管理域的补充存储
video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto]
====
.NetApp 与 VMware Tanzu
[%collapsible]
====
借助 VMware Tanzu ，客户可以通过 vSphere 或 VMware Cloud Foundation 部署，管理和管理 Kubernetes 环境。通过 VMware 的这一产品组合，客户可以选择最适合其需求的 VMware Tanzu 版本，从一个控制平台管理所有相关的 Kubernetes 集群。

有关 VMware Tanzu 的详细信息，请参见 https://tanzu.vmware.com/tanzu["VMware Tanzu 概述"^]。此审核涵盖使用情形，可用添加内容以及有关 VMware Tanzu 的更多信息。

.如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 1 部分
video::ZtbXeOJKhrc[youtube,width=360]
.如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 2 部分
video::FVRKjWH7AoE[youtube,width=360]
.如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 3 部分
video::Y-34SUtTTtU[youtube,width=360]
====
.NetApp Cloud Insights
[%collapsible]
====
NetApp Cloud Insights是一款全面的监控和分析平台、旨在提供对内部和云基础架构的可见性和控制。

.NetApp Cloud Insights—现代数据中心的可观察性
video::1e4da521-3104-4d51-8cde-b0e001502d3d[panopto,width=360]
====