---
sidebar: sidebar 
permalink: virtualization/vsphere_admin_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: 本页介绍在 VMware vSphere 环境中实施 NetApp ONTAP Storage 解决方案的最佳实践。 
---
= 适用于 vSphere 管理员的 ONTAP 简介
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== 为什么选择适用于 vSphere 的 ONTAP ？

NetApp ONTAP 简化了存储和数据管理操作，并对 VMware 环境进行了显著的补充，无论是在内部部署还是在云端部署。在基于 SAN 和基于 NAS 的 VMware 架构中， NetApp 同类最佳的数据保护，存储效率创新以及卓越的性能都是成千上万客户选择 ONTAP 作为其适用于 vSphere 的存储解决方案部署的原因。

NetApp 为各种 VMware 产品提供了大量 VMware 插件，验证和资格认定，以支持面临管理虚拟化环境的独特挑战的客户。NetApp 在存储和数据管理方面的作用与 VMware 在虚拟化方面的作用一样，使客户能够专注于其核心能力，而不是管理物理存储。VMware 和 NetApp 之间近 20 年的合作关系不断发展，随着 VMware Cloud Foundation 和 Tanzu 等新技术的出现，客户价值不断增加，同时也在继续为 vSphere 的基础提供支持。

客户价值的关键因素包括：

* * 统一存储 *
* * 存储效率 * 。
* * 虚拟卷和基于存储策略的管理 *
* * 混合云 *


有关受支持的 NetApp 和 VMware 解决方案的详细信息，请参见以下资源：

* https://mysupport.netapp.com/matrix/#welcome["NetApp 互操作性表工具"^] IMTIMT 定义了可用于构建 FC/FCoE ， iSCSI ， NFS 和 CIFS 配置的合格组件和版本。
* https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san&details=1&partner=64&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["VMware 兼容性指南"^]。VMware 兼容性指南列出了系统， I/O ，存储 /SAN 和备份与 VMware 基础架构和软件产品的兼容性
* https://www.netapp.com/support-and-training/documentation/ontap-tools-for-vmware-vsphere-documentation/["适用于 VMware 的 NetApp ONTAP 工具"^]。适用于 VMware vSphere 的 ONTAP 工具是一个 vCenter Server 插件，其中包括 VSC ， VASA Provider 和 Storage Replication Adapter （ SRA ）扩展。

