---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 此页面提供了视频和教程的简介。 
---
= 混合云、虚拟化和容器视频和演示
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
请参见以下视频和演示、其中重点介绍了混合云、虚拟化和容器解决方案的特定功能。

.适用于 VMware vSphere 的 NetApp ONTAP 工具
[%collapsible]
====
.适用于VMware的ONTAP 工具—概述
[%collapsible]
=====
video::otv_overview.mp4[]
=====
.使用ONTAP 配置VMware iSCSI数据存储库
[%collapsible]
=====
video::otv_iscsi_provision.mp4[]
=====
.使用ONTAP 配置VMware NFS数据存储库
[%collapsible]
=====
video::otv_nfs_provision.mp4[]
=====
====
.采用AWS FSX for NetApp ONTAP 的AWS上的VMware云
[%collapsible]
====
.使用iSCSI使用FSX ONTAP 的Windows子系统连接存储
[%collapsible]
=====
video::vmc_windows_vm_iscsi.mp4[]
=====
.使用NFS使用FSX ONTAP 的Linux子系统连接存储
[%collapsible]
=====
video::vmc_linux_vm_nfs.mp4[]
=====
.借助适用于NetApp ONTAP 的Amazon FSX、基于AWS的VMware Cloud可节省TCO
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC-TCO-calculator.mp4[]
=====
.AWS上的VMware Cloud补充数据存储库、使用适用于NetApp ONTAP 的Amazon FSX
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC.mp4[]
=====
.使用FSxN和VMware HCX迁移AWS上的VMware Cloud
[%collapsible]
=====
video::VMC_HCX_Setup.mp4[]
video::Migration_HCX_VMC_FSxN_VMotion.mp4[]
video::Migration_HCX_VMC_FSxN_cold_migration.mp4[]
=====
====
.采用Azure NetApp Files (ANF)的Azure上的Azure VMware服务
[%collapsible]
====
.Azure NetApp Files 中的Azure VMware解决方案 补充数据存储库概述
[%collapsible]
=====
video::ANF-NFS-datastore-on-AVS.mp4[]
=====
.采用Cloud Volumes ONTAP 、SnapCenter 和Jetstream的Azure VMware解决方案 灾难恢复
[%collapsible]
=====
video::AVS-guest-connect-DR-use-case.mp4[]
=====
.采用ANF和VMware HCX的Azure VMware解决方案 迁移
[%collapsible]
=====
video::Migration_HCX_AVS_ANF_ColdMigration.mp4[]
video::Migration_HCX_AVS_ANF_VMotion.mp4[]
video::Migration_HCX_AVS_ANF_Bulk.mp4[]
=====
====
.适用于 VMware vSphere 的 SnapCenter 插件
[%collapsible]
====
NetApp SnapCenter 软件是一款易于使用的企业平台，可安全地协调和管理应用程序，数据库和文件系统之间的数据保护。

您可以使用适用于 VMware vSphere 的 SnapCenter 插件对 VM 执行备份，还原和连接操作，并对直接在 VMware vCenter 中向 SnapCenter 注册的数据存储库执行备份和挂载操作。

有关适用于 VMware vSphere 的 NetApp SnapCenter 插件的详细信息，请参见 link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["适用于 VMware vSphere 的 NetApp SnapCenter 插件概述"]。

.适用于 VMware vSphere 的 SnapCenter 插件—解决方案 前提条件
[%collapsible]
=====
video::scv_prereq_overview.mp4[]
=====
.适用于 VMware vSphere 的 SnapCenter 插件—部署
[%collapsible]
=====
video::scv_deployment.mp4[]
=====
.适用于 VMware vSphere 的 SnapCenter 插件—备份工作流
[%collapsible]
=====
video::scv_backup_workflow.mp4[]
=====
.适用于 VMware vSphere 的 SnapCenter 插件—还原工作流
[%collapsible]
=====
video::scv_restore_workflow.mp4[]
=====
.SnapCenter — SQL 还原工作流
[%collapsible]
=====
video::scv_sql_restore.mp4[]
=====
====
.NetApp 与 VMware Tanzu
[%collapsible]
====
借助 VMware Tanzu ，客户可以通过 vSphere 或 VMware Cloud Foundation 部署，管理和管理 Kubernetes 环境。通过 VMware 的这一产品组合，客户可以选择最适合其需求的 VMware Tanzu 版本，从一个控制平台管理所有相关的 Kubernetes 集群。

有关 VMware Tanzu 的详细信息，请参见 https://tanzu.vmware.com/tanzu["VMware Tanzu 概述"^]。此审核涵盖使用情形，可用添加内容以及有关 VMware Tanzu 的更多信息。

* https://www.youtube.com/watch?v=ZtbXeOJKhrc["如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 1 部分"^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE["如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 2 部分"^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU["如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 3 部分"^]


====
.采用 Red Hat OpenShift 的 NetApp
[%collapsible]
====
Red Hat OpenShift 是一款企业级 Kubernetes 平台，可用于运行采用开放式混合云策略的基于容器的应用程序。Red Hat OpenShift 作为领先公有云上的云服务或自助管理软件提供，可为客户提供设计基于容器的解决方案所需的灵活性。

有关 Red Hat OpenShift 的详细信息，请参见此部分 https://www.redhat.com/en/technologies/cloud-computing/openshift["Red Hat OpenShift 概述"^]。您还可以查看产品文档和部署选项，了解有关 Red Hat OpenShift 的更多信息。

* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html["工作负载迁移—采用 NetApp 的 Red Hat OpenShift"^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html["Red Hat OpenShift Deployment on RHV ：采用 NetApp 的 Red Hat OpenShift"^]


====