---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 此页面提供了视频和教程的简介。 
---
= 虚拟化视频和演示
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
请参见以下视频和演示、其中重点介绍了混合云、虚拟化和容器解决方案的特定功能。

.适用于 VMware vSphere 的 NetApp ONTAP 工具
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
适用于VMware的ONTAP 工具—概述

 a| 
使用ONTAP 配置VMware iSCSI数据存储库

 a| 
使用ONTAP 配置VMware NFS数据存储库


|===
====
.采用AWS FSX for NetApp ONTAP 的AWS上的VMware云
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
使用iSCSI使用FSX ONTAP 的Windows子系统连接存储

 a| 
使用NFS使用FSX ONTAP 的Linux子系统连接存储

 a| 
借助适用于NetApp ONTAP 的Amazon FSX、基于AWS的VMware Cloud可节省TCO




 a| 
AWS上的VMware Cloud补充数据存储库、使用适用于NetApp ONTAP 的Amazon FSX

 a| 
适用于VMC的VMware HCX部署和配置设置

 a| 
使用VMware HCX for VMC和FSxN进行VMotion迁移演示




 a| 
使用适用于VMC和FSxN的VMware HCX进行冷迁移演示

 a| 
 a| 

|===
====
.采用Azure NetApp Files (ANF)的Azure上的Azure VMware服务
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Azure NetApp Files 中的Azure VMware解决方案 补充数据存储库概述

 a| 
采用Cloud Volumes ONTAP 、SnapCenter 和Jetstream的Azure VMware解决方案 灾难恢复

 a| 
使用适用于AVS和ANF的VMware HCX进行冷迁移演示




 a| 
使用适用于AVS和ANF的VMware HCX进行VMotion演示

 a| 
使用适用于AVS和ANF的VMware HCX进行批量迁移演示

 a| 

|===
====
.适用于 VMware vSphere 的 SnapCenter 插件
[%collapsible]
====
NetApp SnapCenter 软件是一款易于使用的企业平台，可安全地协调和管理应用程序，数据库和文件系统之间的数据保护。

您可以使用适用于 VMware vSphere 的 SnapCenter 插件对 VM 执行备份，还原和连接操作，并对直接在 VMware vCenter 中向 SnapCenter 注册的数据存储库执行备份和挂载操作。

有关适用于 VMware vSphere 的 NetApp SnapCenter 插件的详细信息，请参见 link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["适用于 VMware vSphere 的 NetApp SnapCenter 插件概述"]。

[cols="5a, 5a, 5a"]
|===


 a| 
适用于 VMware vSphere 的 SnapCenter 插件—解决方案 前提条件

 a| 
适用于 VMware vSphere 的 SnapCenter 插件—部署

 a| 
适用于 VMware vSphere 的 SnapCenter 插件—备份工作流




 a| 
适用于 VMware vSphere 的 SnapCenter 插件—还原工作流

 a| 
SnapCenter — SQL 还原工作流

 a| 

|===
====
.NetApp 与 VMware Tanzu
[%collapsible]
====
借助 VMware Tanzu ，客户可以通过 vSphere 或 VMware Cloud Foundation 部署，管理和管理 Kubernetes 环境。通过 VMware 的这一产品组合，客户可以选择最适合其需求的 VMware Tanzu 版本，从一个控制平台管理所有相关的 Kubernetes 集群。

有关 VMware Tanzu 的详细信息，请参见 https://tanzu.vmware.com/tanzu["VMware Tanzu 概述"^]。此审核涵盖使用情形，可用添加内容以及有关 VMware Tanzu 的更多信息。

[cols="5a, 5a, 5a"]
|===


 a| 
如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 1 部分

video::ZtbXeOJKhrc[youtube,width=360] a| 
如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 2 部分

video::FVRKjWH7AoE[youtube,width=360] a| 
如何在 NetApp 和 VMware Tanzu Basic 中使用 VVOL ，第 3 部分

video::Y-34SUtTTtU[youtube,width=360]
|===
====