---
sidebar: sidebar 
permalink: virtualization/vsphere_ontap_whats_new.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 本页介绍在 VMware vSphere 环境中自动执行基本 ONTAP 功能的优势。 
---
= 适用于 VMware 虚拟化的 ONTAP 的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/
:firstname: :allow-uri-read
:author: :allow-uri-read
:authorinitials: :
:authors: :allow-uri-read




== VMware 虚拟化

ONTAP 9.8 中的 VMware 集成和支持得到了提升，包括 FlexGroup 数据存储库支持在内的许多新功能。通过 ONTAP 9.8 ，您可以将 FlexGroup 卷配置为 VMware NFS 数据存储库，从而通过一个可扩展的数据存储库来简化数据存储库管理，该数据存储库可提供完整的 ONTAP 集群功能。其中许多新功能都随适用于 VMware vSphere 9.8 的 ONTAP 工具提供。

这意味着以下各项适用：

* 经验证的性能和放置
* 互操作性资格认定
* 增强了 VAAI 副本卸载功能，速度更快，可在后台完成
* 虚拟存储控制台支持，包括 FlexGroup 配置，调整大小和删除，在各个 VM 上设置 QoS 以及显示 VM 的性能指标（延迟， IOPS 和吞吐量）
* NetApp SnapCenter 主存储备份和恢复支持
* 最多支持 64 TB VMFS LUN 。借助 NetApp 全 SAN 阵列支持 128 TB LUN/300 TB FlexVol 卷，您可以在适用于 VMware vSphere 9.8 的 ONTAP 工具中使用虚拟存储控制台配置最大 64 TB VMFS 数据存储库。
* 增加 https://www.vmware.com/in/products/site-recovery-manager.html["Site Recovery Manager （ SRM ）"^] 扩展。适用于 VMware vSphere 的 ONTAP 工具 9.8 版中的存储复制适配器可将支持的数据存储库和保护组的扩展性提高到 512 。
* 使用 REST API 的 VMware vSphere VVol 文件指标。ONTAP 9.8 增加了对 VVOL 文件指标的 REST API 支持，允许虚拟存储控制台在信息板和报告中显示 VVOL 的 ONTAP 存储性能指标。
* https://docs.vmware.com/en/Site-Recovery-Manager/8.3/com.vmware.srm.admin.doc/GUID-5651B2B8-6410-48AE-8882-6D51C85AC201.html["Storage Replication Adapter （ SRA ）"^] 支持 SnapMirror 同步
* 支持 https://tanzu.vmware.com/tanzu["VMware Tanzu"^] storage
* 改进了对 VVOL 的支持，包括增强的 SAN VVOL 重新平衡命令以及存储功能配置文件的增强功能。有关最新 VMware 虚拟化支持的详细信息，请参见以下资源：
* https://soundcloud.com/techontap_podcast/episode-263-virtualization-in-ontap-fall-2020-update["Tech OnTap 播客第 263 集：《 ONTAP 中的虚拟化— 2020 年秋季》"^]
* https://www.netapp.com/us/media/tr-4597.pdf["TR-4597 ：采用 ONTAP 的 VMware vSphere"^]

