---
sidebar: sidebar 
permalink: virtualization/vsrm-ontap9_appendix_a__troubleshooting_srm_when_using_vvols_replication.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, srm, vvols, replication 
summary: 使用 VVOL 复制时， SRM 中的工作流与使用 SRA 和传统数据存储库时的工作流有明显不同。 
---
= 对使用 VVol 复制的 SRM 进行故障排除
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


使用 VVOL 复制时， SRM 中的工作流与使用 SRA 和传统数据存储库时的工作流有明显不同。例如，没有阵列管理器概念。因此，永远看不到 `discoverarrays` 和 `discoverdevices` 命令。

在进行故障排除时，了解下面列出的新工作流非常有用：

. queryReplicationPeer ：发现两个故障域之间的复制协议。
. queryFaultDomain ：发现故障域层次结构。
. queryReplicationGroup ：发现源域或目标域中的复制组。
. syncReplicationGroup ：同步源和目标之间的数据。
. queryPointInTimeReplica ：发现目标上的时间点副本。
. testFailoverReplicationGroupStart ：开始测试故障转移。
. testFailoverReplicationGroupStop ：结束测试故障转移。
. promoteReplicationGroup ：将当前正在测试的组提升为生产组。
. prepareFailoverReplicationGroup ：准备灾难恢复。
. failoverReplicationGroup ：执行灾难恢复。
. reverseReplicateGroup ：启动反向复制。
. queryMatchingContainer ：查找可能使用给定策略满足配置请求的容器（以及主机或复制组）。
. queryResourceMetadata ：从 VASA 提供程序中发现所有资源的元数据，资源利用率可以作为问题解答返回给 queryMatchingContainer 函数。


配置 VVOL 复制时，最常见的错误是无法发现 SnapMirror 关系。之所以出现这种情况，是因为卷和 SnapMirror 关系是在 ONTAP 工具的权限范围之外创建的。因此，最佳做法是，在尝试创建复制的 VVOL 数据存储库之前，始终确保 SnapMirror 关系已完全初始化，并且您已在两个站点的 ONTAP 工具中运行重新发现。
