= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
AWS 支持以下配置中的 NetApp 存储：

* FSX ONTAP 作为子系统连接的存储
* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* FSX ONTAP 作为原生 数据存储库^1^


查看详细信息 link:aws/aws-guest.html["VMC的子系统连接存储选项"]。

查看详细信息 link:aws-guest.html["VMC的子系统连接存储选项"]。

了解更多信息 link:https://blogs.vmware.com/cloud/2021/12/01/vmware-cloud-on-aws-going-big-reinvent2021/["FSX ONTAP 作为原生数据存储库^1."^]。


NOTE: 1 —当前处于私有预览模式

--
.Azure / AVS
--
Azure 支持以下配置中的 NetApp 存储：

* Azure NetApp Files （ ANF ）作为子系统连接的存储
* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* Azure NetApp Files (ANF)作为原生 数据存储库^1^


查看详细信息 link:azure/azure-guest.html["AVS的子系统连接存储选项"]。

查看详细信息 link:azure-guest.html["AVS的子系统连接存储选项"]。

了解更多信息 link:https://azure.microsoft.com/en-us/updates/azure-netapp-files-datastores-for-azure-vmware-solution-is-coming-soon/["Azure NetApp Files （ ANF ）作为原生数据存储库^1."^]。


NOTE: 1 —当前处于私有预览模式

--
.GCP / GCVE
--
Google Cloud 支持以下配置中的 NetApp 存储：

* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* Cloud Volumes Service （ CVS ）作为子系统连接的存储
* Cloud Volumes Service (CVS)作为原生 数据存储库^1^


查看详细信息 link:gcp/gcp-guest.html["GCVE的子系统连接存储选项"]。

查看详细信息 link:gcp-guest.html["GCVE的子系统连接存储选项"]。

了解更多信息 link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["Cloud Volumes Service （ CVS ）作为原生数据存储库^1."^]。


NOTE: 1 —当前处于私有预览模式

--
====