= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
AWS 支持以下配置中的 NetApp 存储：

* FSX ONTAP 作为子系统连接的存储
* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* FSX ONTAP 作为补充NFS数据存储库^1^


查看详细信息 link:aws/aws-guest.html["VMC的子系统连接存储选项"]。

查看详细信息 link:aws-guest.html["VMC的子系统连接存储选项"]。


NOTE: 1—VMC的FSxN当前处于IA状态(初始可用性)。有关详细信息、请联系您的NetApp销售代表。

--
.Azure / AVS
--
Azure 支持以下配置中的 NetApp 存储：

* Azure NetApp Files （ ANF ）作为子系统连接的存储
* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* Azure NetApp Files (ANF)作为补充NFS数据存储库^1^


查看详细信息 link:azure/azure-guest.html["AVS的子系统连接存储选项"]。

查看详细信息 link:azure-guest.html["AVS的子系统连接存储选项"]。


NOTE: 1—ANF作为AVS的补充NFS数据存储库当前处于公有 预览模式。了解更多信息 https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?branch=main&tabs=azure-portal["此处"]。

--
.GCP / GCVE
--
Google Cloud 支持以下配置中的 NetApp 存储：

* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* Cloud Volumes Service （ CVS ）作为子系统连接的存储
* Cloud Volumes Service (CVS)作为补充NFS数据存储库^1^


查看详细信息 link:gcp/gcp-guest.html["GCVE的子系统连接存储选项"]。

查看详细信息 link:gcp-guest.html["GCVE的子系统连接存储选项"]。

了解更多信息 link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["Cloud Volumes Service (CVS)作为补充NFS数据存储库^1."^]。


NOTE: 1 —当前处于私有预览模式

--
====