---
sidebar: sidebar 
permalink: databases/aws_ora_fsx_ec2_deploy_intro.html 
summary: 本白皮书概述并验证了适用于AWS的解决方案 自定义Oracle RDS数据库HA和DR、并在多可用性区域部署中利用AWS FSx存储服务。 
keywords: HA, DR, database, Oracle, RDS, AWS 
---
= WP-7357：《在EC2和FSX上部署Oracle数据库最佳实践》简介
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


NetApp公司的Allen Cao、Niyaz Mohamed、Jeffrey Steiner

[role="lead"]
许多任务关键型企业级Oracle数据库仍托管在内部、许多企业都希望将这些Oracle数据库迁移到公有 云。这些Oracle数据库通常以应用程序为中心、因此需要用户专用配置、而许多数据库即服务公共云产品都缺少这一功能。因此、当前的数据库环境要求基于公共云的Oracle数据库解决方案 、该数据库是基于高性能、可扩展的计算和存储服务构建的、可满足独特的需求。AWS EC2计算实例和AWS FSX存储服务可能是这个难题的缺失部分、您可以利用这些信息构建任务关键型Oracle数据库工作负载并将其迁移到公有 云。

Amazon Elastic Compute Cloud (Amazon EC2)是一种Web服务、可在云中提供安全、可调整大小的计算容量。它旨在使企业更轻松地进行网络级云计算。通过简单的Amazon EC2 Web服务界面、您可以轻松获得和配置容量、而不会产生任何摩擦。它可以让您完全控制计算资源、并在经过Amazon验证的计算环境中运行。

Amazon FSx ONTAP是一项AWS存储服务、它使用行业领先的NetApp ONTAP块和文件存储、可公开NFS、SMB和iSCSI。借助如此强大的存储引擎、将任务关键型Oracle数据库应用程序重新定位到AWS从未如此简单、其响应时间为亚毫秒级、吞吐量高达多Gbps、每个数据库实例的IOPS超过100、000次。更好的是、FSX存储服务还附带了原生 复制功能、您可以轻松地将内部Oracle数据库迁移到AWS、或者将任务关键型Oracle数据库复制到二级AWS可用性区域以实现HA或DR。

本文档的目标是、提供有关如何使用FSX存储和EC2实例部署和配置Oracle数据库的分步流程、过程和最佳实践指导、该实例可提供与内部系统类似的性能。NetApp还提供了一个自动化工具包、用于自动执行在AWS公有 云中部署、配置和管理Oracle数据库工作负载所需的大部分任务。

要了解有关解决方案 和用例的更多信息、请观看以下概述视频：

link:https://www.netapp.tv/insight/details/30000?playlist_id=275&mcid=04891225598830484314259903524057913910["利用AWS和FSX ONTAP 中的混合云打造现代化的Oracle数据库、第1部分—用例和解决方案 架构"^]
