---
sidebar: sidebar 
permalink: databases/getting_started_requirements.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 此页面介绍了在 NetApp ONTAP 存储上部署 Oracle19c 的自动化方法。 
---
= 入门
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
此解决方案可以在 AWX/Tower 环境中运行，也可以通过命令行界面在 Ansible 控制主机上运行。



== AWX/ 塔式

对于 AWX/Tower 环境，系统将引导您创建 ONTAP 集群管理和 Oracle 服务器（ IP 和主机名）清单，创建凭据，配置从 NetApp Automation Github 提取 Ansible 代码的项目以及启动自动化的作业模板。

. 填写特定于您的环境的变量，然后将其复制并粘贴到作业模板中的额外 VAR 字段中。
. 将额外的变量添加到作业模板后，您可以启动自动化。
. 通过为 ontap_config ， linux_config 和 oracle_config 指定标记，作业模板将分三个阶段运行。




== 通过 Ansible 控制主机执行 CLI

. 配置 Linux 主机，以便用作 Ansible 控制主机link:../automation/getting-started.html["单击此处了解详细说明"]
. 配置 Ansible 控制主机后，您可以克隆 Ansible Automation 存储库。
. 使用 ONTAP 集群管理的 IP 和 / 或主机名以及 Oracle 服务器的管理 IP 编辑 hosts 文件。
. 填写特定于您的环境的变量，然后将其复制并粘贴到 `vars.yml` 文件中。
. 每个 Oracle 主机都有一个可变文件，该文件由其主机名标识，其中包含主机专用变量。
. 完成所有可变文件后，您可以通过为 `ontap_config` ， `linux_config` 和 `oracle_config` 指定标记来分三个阶段运行此攻略手册。




== 要求

[cols="3, 9"]
|===
| environment | 要求 


.4+| * 可逆环境 * | AWX/Tower 或 Linux 主机作为 Ansible 控制主机 


| Ansible v.10 及更高版本 


| Python 3. 


| Python 库— netapp-lib — xmltodict — jMespath 


.3+| * ONTAP * | ONTAP 版本 9.3 - 9.7 


| 两个数据聚合 


| 已创建 NFS VLAN 和 ifgrp 


.5+| * Oracle 服务器 * | RHEL 7/8 


| Oracle Linux 7/8 


| NFS ，公有和可选管理的网络接口 


| Oracle 服务器上的 Oracle 安装文件 
|===


== 自动化详细信息

此自动化部署采用一本 Ansible 攻略手册设计，该攻略手册包含三个不同的角色。这些角色适用于 ONTAP ， Linux 和 Oracle 配置。下表介绍了正在自动执行的任务。

[cols="4, 9"]
|===
| Role | 任务 


.5+| * ontap_config* | 预检查 ONTAP 环境 


| 为 Oracle 创建基于 NFS 的 SVM 


| 创建导出策略 


| 为 Oracle 创建卷 


| 创建 NFS LIF 


.9+| * Linux 配置 * | 创建挂载点并挂载 NFS 卷 


| 验证 NFS 挂载 


| 特定于操作系统的配置 


| 创建 Oracle 目录 


| 配置页面 


| 禁用 SELinux 和防火墙守护进程 


| 启用并启动 chronyd 服务 


| 增加文件描述符硬限制 


| 创建 pam 会话文件 


.8+| * ORACLE_CONFIG * | Oracle 软件安装 


| 创建 Oracle 侦听器 


| 创建 Oracle 数据库 


| Oracle 环境配置 


| 保存 PDB 状态 


| 启用实例归档模式 


| 启用 DNFS 客户端 


| 在操作系统重新启动之间启用数据库自动启动和关闭 
|===


== 默认参数

为了简化自动化，我们已使用默认值预设了许多必需的 Oracle 部署参数。通常，无需更改大多数部署的默认参数。更高级的用户可以谨慎地更改默认参数。默认参数位于每个角色文件夹的默认目录下。



== 部署说明

开始之前，请下载以下 Oracle 安装和修补程序文件，并将其放置在 ` /tmp/archive` 目录中，以便每个要部署的数据库服务器上的所有用户都能进行读取，写入和执行访问。自动化任务会在该特定目录中查找命名的安装文件，以便进行 Oracle 安装和配置。

[listing]
----
LINUX.X64_193000_db_home.zip -- 19.3 base installer
p31281355_190000_Linux-x86-64.zip -- 19.8 RU patch
p6880880_190000_Linux-x86-64.zip -- opatch version 12.2.0.1.23
----


== 许可证

您应按照 Github 存储库中的说明读取许可证信息。访问，下载，安装或使用此存储库中的内容即表示您同意所规定的许可证条款 link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["此处"^]。

请注意，在生成和 / 或共享任何派生作品时，此存储库中的内容存在一定的限制。请务必阅读的条款 link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["许可证"^] 在使用内容之前。如果您不同意所有条款，请勿访问，下载或使用此存储库中的内容。

准备就绪后，单击 link:awx_automation.html["此处可查看 AWX/ 塔式部署的详细步骤"] 或 link:cli_automation.html["此处用于命令行界面部署"]。
