---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_prereq_cloud.html 
summary: 在安装 Cloud Manager Connector 和 Cloud Volumes ONTAP 并配置 SnapMirror 之前，我们必须为云环境做一些准备。此页面介绍了部署 Cloud Volumes ONTAP 时需要执行的工作以及注意事项。 
keywords: prerequisites, aws, azure, gcp, cloud central, cloud volumes ontap 
---
= 公有云的前提条件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:hybrid_dbops_snapcenter_prereq_onprem.html["先前版本：内部前提条件。"]

在安装 Cloud Manager Connector 和 Cloud Volumes ONTAP 并配置 SnapMirror 之前，我们必须为云环境做一些准备。此页面介绍了部署 Cloud Volumes ONTAP 时需要执行的工作以及注意事项。



== Cloud Manager 和 Cloud Volumes ONTAP 部署前提条件检查清单

* NetApp Cloud Central 登录
* 从 Web 浏览器到多个端点的网络访问
* 连接器的网络位置
* 云提供商权限
* 为单个服务建立网络


有关入门内容的详细信息，请访问我们的 https://docs.netapp.com/us-en/occm/reference_checklist_cm.html["云文档"^]。



== 注意事项



=== 1. 什么是 Cloud Manager 连接器？

在大多数情况下， Cloud Central 帐户管理员必须在云或内部网络中部署连接器。借助此连接器， Cloud Manager 可以管理公有云环境中的资源和流程。

有关连接器的详细信息，请访问我们的 https://docs.netapp.com/us-en/occm/concept_connectors.html["云文档"^]。



=== 2. Cloud Volumes ONTAP 规模估算和架构

部署 Cloud Volumes ONTAP 时，您可以选择预定义的软件包或创建自己的配置。虽然其中许多值稍后可以无中断地进行更改，但在部署之前，需要根据要在云中部署的工作负载做出一些关键决策。

每个云提供商都有不同的部署选项，几乎每个工作负载都有自己的独特属性。NetApp 具有 https://cloud.netapp.com/cvo-sizer["CVO 规模估算工具"^] 这有助于根据容量和性能正确估算部署规模，但它是围绕一些基本概念构建的，值得考虑：

* 所需容量
* 云虚拟机的网络功能
* 云存储的性能特征


关键在于规划的配置不仅要满足当前的容量和性能要求，还要考虑未来的增长。这通常称为容量余量和性能余量。

如果您希望了解更多信息，请阅读有关正确规划的文档 https://docs.netapp.com/us-en/occm/task_planning_your_config.html["AWS"^]， https://docs.netapp.com/us-en/occm/task_planning_your_config_azure.html["Azure 酒店"^]，和 https://docs.netapp.com/us-en/occm/task_planning_your_config_gcp.html["GCP"^]。



=== 3. 单节点还是高可用性？

在所有云中，您可以选择在单个节点或具有两个节点的集群模式高可用性对中部署 CVO 。根据使用情形，您可能希望部署一个节点以节省成本，或者部署一个 HA 对以提供进一步的可用性和冗余。

对于灾难恢复使用情形或为开发和测试而启动临时存储的情形，单个节点很常见，因为突然的区域或基础架构中断所造成的影响较小。但是，对于任何生产用例，如果数据仅位于一个位置，或者数据集必须具有更多冗余和可用性，则建议使用高可用性。

有关每个云高可用性版本的架构的详细信息，请访问的文档 https://docs.netapp.com/us-en/occm/concept_ha.html["AWS"^]， https://docs.netapp.com/us-en/occm/concept_ha_azure.html["Azure 酒店"^] 和 https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html["GCP"^]。

link:hybrid_dbops_snapcenter_getting_started.html["下一步：入门概述。"]
