---
sidebar: sidebar 
permalink: databases/marketing_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: 此页面介绍了在 NetApp ONTAP 存储上部署 Oracle19c 的自动化方法。 
---
= 解决方案概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== 在 NFS 上自动部署适用于 ONTAP 的 Oracle19c

企业正在对其环境进行自动化，以提高效率，加快部署速度并减少手动操作。Ansible 等配置管理工具正在用于简化企业数据库操作。在此解决方案中，我们将演示如何使用 Ansible 通过 NetApp ONTAP 自动配置和配置 Oracle 19c 。通过使存储管理员，系统管理员和 DBA 能够一致快速地部署新存储，配置数据库服务器并安装 Oracle 19c 软件，您可以获得以下优势：

* 消除设计复杂性和人为错误，并实施可重复的一致部署和最佳实践
* 缩短配置存储，配置数据库主机和安装 Oracle 的时间
* 提高数据库管理员，系统和存储管理员的工作效率
* 轻松扩展存储和数据库


NetApp 为客户提供经过验证的 Ansible 模块和角色，以加快 Oracle 数据库环境的部署，配置和生命周期管理。此解决方案提供了相关说明和 Ansible 攻略手册代码，可帮助您：

* 为 Oracle 数据库创建和配置 ONTAP NFS 存储
* 在 RedHat Enterprise Linux 7/8 或 Oracle Linux 7/8 上安装 Oracle 19c
* 在 ONTAP NFS 存储上配置 Oracle 19c


有关更多详细信息或要开始，请参见下面的概述视频。



=== AWX/ 塔式部署

第 1 部分：入门，要求，自动化详细信息和初始 AWX/ 塔式配置

.AWX部署
video::d844a9c3-4eb3-4512-bf21-b01200f09f66[panopto]
第 2 部分：变量和运行攻略手册

.AWX操作手册运行
video::6da1b960-e1c9-4950-b750-b01200f0bdfa[panopto]


=== CLI 部署

第 1 部分：入门，要求，自动化详细信息和可变控制主机设置

.CLI 部署
video::373e7f2a-c101-4292-a3e4-b01200f0d078[panopto]
第 2 部分：变量和运行攻略手册

.命令行界面操作手册运行
video::d58ebdb0-8bac-4ef9-b4d1-b01200f95047[panopto]