---
sidebar: sidebar 
permalink: ehc/azure/azure-avs.html 
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= 适用于 Azure AVS 的 NetApp 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
详细了解NetApp为Azure VMware解决方案 (AVS)提供的功能—从作为子系统连接存储设备或补充NFS数据存储库的NetApp到迁移工作流、扩展/突发到云、备份/还原和灾难恢复。

从以下选项中选择，跳至所需内容部分：

* link:#config["在 Azure 中配置 AVS"]
* link:#datastore["适用于 AVS 的 NetApp 存储选项"]
* link:#solutions["NetApp/VMware云解决方案"]




== 在 Azure 中配置 AVS

与内部部署一样，规划基于云的虚拟化环境对于成功创建 VM 和迁移生产就绪环境至关重要。

本节介绍如何设置和管理 Azure VMware 解决方案并将其与连接 NetApp 存储的可用选项结合使用。


NOTE: 来宾存储是将Cloud Volumes ONTAP 连接到Azure VMware解决方案 的唯一受支持方法。

设置过程可细分为以下步骤：

* 注册资源提供商并创建私有云
* 连接到新的或现有的 ExpressRoute 虚拟网络网关
* 验证网络连接并访问私有云


查看详细信息 link:azure-setup.html["AVS的配置步骤"]。



== 适用于 AVS 的 NetApp 存储选项

NetApp存储可以通过多种方式在Azure AVS中用作guess connected或作为补充NFS数据存储库。

请访问 link:../ehc-support-configs.html["支持的 NetApp 存储选项"] 有关详细信息 ...

Azure 支持以下配置中的 NetApp 存储：

* Azure NetApp Files （ ANF ）作为子系统连接的存储
* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* Azure NetApp Files (ANF)作为补充NFS数据存储库


查看详细信息 link:azure-guest.html["AVS的子系统连接存储选项"]。查看详细信息 link:azure-native-nfs-datastore-option.html["AVS的补充NFS数据存储库选项"]。



== 解决方案用例

借助 NetApp 和 VMware 云解决方案，许多用例都可以轻松部署在 Azure AVS 中。为VMware定义的每个云区域定义了SE案例：

* 保护(包括灾难恢复和备份/还原)
* 扩展
* 迁移


link:azure-solutions.html["浏览适用于 Azure AVS 的 NetApp 解决方案"]
