---
sidebar: sidebar 
permalink: ehc/aws/aws-vmc.html 
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= 适用于 AWS VMC 的 NetApp 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
详细了解NetApp为AWS VMware Cloud (VMC)提供的功能—从作为子系统连接存储设备或补充NFS数据存储库的NetApp到迁移工作流、扩展/突发到云、备份/还原和灾难恢复。

从以下选项中选择，跳至所需内容部分：

* link:#config["在 AWS 中配置 VMC"]
* link:#datastore["适用于 VMC 的 NetApp 存储选项"]
* link:#solutions["NetApp/VMware云解决方案"]




== 在 AWS 中配置 VMC

与内部部署一样，规划基于云的虚拟化环境对于成功创建 VM 和迁移生产就绪环境至关重要。

本节介绍如何在 AWS SDDC 上设置和管理 VMware Cloud ，并将其与连接 NetApp 存储的可用选项结合使用。


NOTE: 只支持使用来宾存储将Cloud Volumes ONTAP 连接到AWS VMC。

设置过程可细分为以下步骤：

* 部署和配置适用于AWS的VMware Cloud
* 将 VMware Cloud 连接到 FSX ONTAP


查看详细信息 link:aws-setup.html["VMC的配置步骤"]。



== 适用于 VMC 的 NetApp 存储选项

NetApp存储可以通过多种方式在AWS VMC中用作guess connected或作为补充NFS数据存储库。

请访问 link:../ehc-support-configs.html["支持的 NetApp 存储选项"] 有关详细信息 ...

AWS 支持以下配置中的 NetApp 存储：

* FSX ONTAP 作为子系统连接的存储
* Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储
* FSX ONTAP 作为补充NFS数据存储库


查看详细信息 link:aws-guest.html["VMC的子系统连接存储选项"]。查看详细信息 link:aws-native-nfs-datastore-option.html["VMC的补充NFS数据存储库选项"]。



== 解决方案用例

借助 NetApp 和 VMware 云解决方案，许多用例都可以轻松部署在 AWS VMC 中。为VMware定义的每个云区域定义了使用情形：

* 保护(包括灾难恢复和备份/还原)
* 扩展
* 迁移


link:aws-solutions.html["浏览适用于 AWS VMC 的 NetApp 解决方案"]
