---
sidebar: sidebar 
permalink: ehc/aws/aws-vmc.html 
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= 适用于 AWS VMC 的 NetApp 功能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
详细了解 NetApp 为 AWS VMware Cloud （ VMC ）提供的功能—从作为子系统连接存储设备或原生数据存储库的 NetApp 到迁移工作流，扩展 / 突发到云，备份 / 还原和灾难恢复。

从以下选项中选择，跳至所需内容部分：

* link:#config["超大规模部署中的 VMware"]
* link:#datastore["NetApp 存储选项"]




== 在 AWS 中配置 VMC

与内部部署一样，规划基于云的虚拟化环境对于成功创建 VM 和迁移生产就绪环境至关重要。

与内部部署一样，在 AWS 上规划 VMware Cloud 对于成功打造可随时投入生产的环境以创建 VM 和迁移至关重要。

本节介绍如何在 AWS SDDC 上设置和管理 VMware Cloud ，并将其与连接 NetApp 存储的可用选项结合使用。


NOTE: 只支持使用来宾存储将 FSX ONTAP 和 Cloud Volumes ONTAP 连接到 AWS VMC 。

设置过程可细分为以下步骤：

* link:/ehc/aws/aws-setup.html#deploy["部署和配置适用于 AWS 的 VMware Cloud"]
* link:/ehc/aws/aws-setup.html#connect["将 VMware Cloud 连接到 FSX ONTAP"]




== 适用于 VMC 的 NetApp 存储选项

NetApp 存储可以通过多种方式在 AWS VMC 中用作 guess connected 或原生数据存储库。

请访问 link:ehc-support-configs.html["支持的 NetApp 存储选项"] 有关详细信息 ...

AWS 支持以下配置中的 NetApp 存储：

* 来宾连接存储 *

* link:/ehc/aws/aws-guest.html#fsx-ontap["FSX ONTAP 作为子系统连接的存储"]
* link:/ehc/aws/aws-guest.html#cvo["Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储"]


* 原生数据存储库 *

* link:https://blogs.vmware.com/cloud/2021/12/01/vmware-cloud-on-aws-going-big-reinvent2021/["FSX ONTAP 作为原生数据存储库^1."^]



NOTE: 1 —当前处于私有预览模式
