---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-cloud-backup-config.html 
keywords: secondary, windows, snapcenter server, veeam server 
summary: 要将应用程序VM和数据库卷故障转移到AWS中运行的VMware云卷服务、您必须安装并配置SnapCenter 服务器和Veeam备份和复制服务器的正在运行的实例。故障转移完成后、您还必须配置这些工具以恢复正常备份操作、直到计划并执行到内部数据中心的故障恢复为止。 
---
= 云备份工具和配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-config-veeam.html["先前版本：部署和配置Veeam Backup Server。"]

要将应用程序VM和数据库卷故障转移到AWS中运行的VMware云卷服务、您必须安装并配置SnapCenter 服务器和Veeam备份和复制服务器的正在运行的实例。故障转移完成后、您还必须配置这些工具以恢复正常备份操作、直到计划并执行到内部数据中心的故障恢复为止。



== 部署二级Windows SnapCenter 服务器

SnapCenter 服务器部署在VMware云SDDC中或安装在VPC中的EC2实例上、并通过网络连接到VMware云环境。

SnapCenter 软件可从NetApp支持站点获得、并可安装在位于域或工作组中的Microsoft Windows系统上。有关详细的规划指南和安装说明、请参见 https://docs.netapp.com/us-en/snapcenter/install/install_workflow.html["NetApp文档中心"^]。

您可以在以下位置找到SnapCenter 软件： https://mysupport.netapp.com["此链接。"^]。



== 配置二级Windows SnapCenter 服务器

要还原镜像到FSX ONTAP 的应用程序数据、您必须先完全还原内部SnapCenter 数据库。此过程完成后、将重新建立与VM的通信、现在可以使用FSX ONTAP 作为主存储来恢复应用程序备份。

为此、您必须在SnapCenter 服务器上完成以下各项：

. 将计算机名称配置为与原始内部SnapCenter 服务器相同。
. 配置网络以与VMware Cloud和FSX ONTAP 实例进行通信。
. 完成操作步骤 以还原SnapCenter 数据库。
. 确认SnapCenter 处于灾难恢复模式、以确保FSX现在成为备份的主存储。
. 确认已与还原的虚拟机重新建立通信。


有关完成这些步骤的详细信息、请参见第节的 link:aws-guest-dr-failover.html#snapcenter-database-restore-process["SnapCenter 数据库还原过程"]。



== 部署二级Veeam Backup & Replication服务器

您可以在AWS上的VMware Cloud中的Windows服务器或EC2实例上安装Veeam Backup & Replication服务器。有关详细的实施指导、请参见 https://www.veeam.com/documentation-guides-datasheets.html["Veeam帮助中心技术文档"^]。



== 配置二级Veeam Backup & Replication服务器

要还原已备份到Amazon S3存储的虚拟机、您必须在Windows服务器上安装Veeam服务器、并将其配置为与VMware Cloud、FSX ONTAP 和包含原始备份存储库的S3存储分段进行通信。此外、还必须在FSX ONTAP 上配置一个新的备份存储库、以便在虚拟机还原后对其执行新备份。

要执行此过程、必须完成以下各项：

. 配置网络以与VMware Cloud、FSX ONTAP 和包含原始备份存储库的S3存储分段进行通信。
. 将FSX ONTAP 上的SMB共享配置为新的备份存储库。
. 在内部挂载用作横向扩展备份存储库一部分的原始S3存储分段。
. 还原VM后、建立新的备份作业以保护SQL和Oracle VM。


有关使用Veeam还原VM的详细信息、请参见一节 link:aws-guest-dr-restore-veeam-full.html["使用Veeam Full Restore还原应用程序VM"]。

link:aws-guest-dr-snapcenter-db-backup.html["接下来：用于灾难恢复的SnapCenter 数据库备份。"]
