---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-technology.html 
keywords: technology, vmware cloud foundation, vsphere, nsx, snapcenter, veeam, VMware Cloud on AWS, Amazon FSx 
summary: 本节概述了为此解决方案 提供支持的不同技术组件。 
---
= 技术
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-solution-overview.html["上一步：解决方案概述。"]

此解决方案 包含NetApp、VMware、Amazon Web Services (AWS)和Veeam的创新技术。



== VMware



=== VMware Cloud Foundation

VMware Cloud Foundation平台集成了多种产品、可使管理员在异构环境中配置逻辑基础架构。这些基础架构(称为域)可在私有云和公有 云之间提供一致的操作。Cloud Foundation软件附带的材料清单可确定经过预先验证和认证的组件、以降低客户风险并简化部署。

Cloud Foundation BOM的组件包括以下内容：

* Cloud Builder
* SDDC管理器
* VMware vCenter Server 设备
* VMware ESXi
* VMware NSX
* vRealize Automation
* vRealize Suite Lifecycle Manager
* vRealize Log Insight


有关VMware Cloud Foundation的详细信息、请参见 https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["VMware Cloud Foundation文档"^]。



=== VMware vSphere

VMware vSphere是一个虚拟化平台、可将物理资源转换为计算、网络和存储池、以满足客户的工作负载和应用程序要求。VMware vSphere的主要组件包括：

* * ESXi。*此VMware虚拟机管理程序支持对计算处理器、内存、网络和其他资源进行抽象化、并使其可供虚拟机和容器工作负载使用。
* * vCenter。* VMware vCenter可为在虚拟基础架构中与计算资源、网络和存储进行交互提供集中管理体验。


通过将NetApp ONTAP 与深度产品集成、强大的支持以及强大的功能和存储效率结合使用、客户可以充分发挥其vSphere环境的全部潜能、从而打造出强大的混合多云环境。

有关VMware vSphere的详细信息、请参见 https://docs.vmware.com/en/VMware-vSphere/index.html["此链接。"^]。

有关采用VMware的NetApp解决方案的详细信息、请参见 https://docs.netapp.com/us-en/netapp-solutions/virtualization/netapp-vmware.html["此链接。"^]。



=== VMware NSX

VMware NSX通常称为网络虚拟机管理程序、它采用软件定义的模型来连接虚拟化工作负载。VMware NSX在内部和AWS上的VMware Cloud中无处不在、它为客户应用程序和工作负载的网络虚拟化和安全性提供支持。

有关VMware NSX的详细信息、请参见 https://docs.vmware.com/en/VMware-NSX-T-Data-Center/index.html["此链接。"^]。



== NetApp



=== NetApp ONTAP

近 20 年来， NetApp ONTAP 软件一直是 VMware vSphere 环境中的领先存储解决方案，并不断增加创新功能来简化管理，同时降低成本。将 ONTAP 与 vSphere 结合使用是一个很好的组合，可帮助您降低主机硬件和 VMware 软件支出。您还可以利用原生 存储效率、以更低的成本、稳定一致的高性能保护数据。

有关NetApp ONTAP 的详细信息、请参见 https://docs.vmware.com/en/VMware-Cloud-on-AWS/index.html["此链接。"^]。



=== 适用于VMware的NetApp ONTAP 工具

适用于VMware的ONTAP 工具可将多个插件组合到一个虚拟设备中、从而为使用NetApp存储系统的VMware环境中的虚拟机提供端到端生命周期管理。适用于VMware的ONTAP 工具包括以下内容：

* *虚拟存储控制台(VSC)。*使用NetApp存储对VM和数据存储库执行全面的管理任务。
* *适用于ONTAP 的VASA Provider。*支持使用VMware虚拟卷(VVOL)和NetApp存储进行基于存储策略的管理(SPBM)。
* *存储复制适配器(SRA)*。与VMware Site Recovery Manager (SRM)结合使用时、在发生故障时恢复vCenter数据存储库和虚拟机。


通过适用于VMware的ONTAP 工具、用户不仅可以管理外部存储、还可以与VVOL以及VMware Site Recovery Manager集成。这样可以更轻松地在vCenter环境中部署和操作NetApp存储。

有关适用于VMware的NetApp ONTAP 工具的详细信息、请参见 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["此链接。"^]。



=== NetApp SnapCenter

NetApp SnapCenter 软件是一款易于使用的企业平台，可安全地协调和管理应用程序，数据库和文件系统之间的数据保护。SnapCenter 可将这些任务卸载到应用程序所有者、而不会影响对存储系统上活动的监控和监管、从而简化备份、还原和克隆生命周期管理。通过利用基于存储的数据管理、SnapCenter 不仅可以提高性能和可用性、还可以缩短测试和开发时间。

适用于VMware vSphere的SnapCenter 插件支持对虚拟机(VM)、数据存储库和虚拟机磁盘(VMDK)执行崩溃状态一致和VM一致的备份和还原操作。它还支持SnapCenter 应用程序专用插件、以保护虚拟化数据库和文件系统的应用程序一致的备份和还原操作。

有关NetApp SnapCenter 的详细信息、请参见 https://docs.netapp.com/us-en/snapcenter/["此链接。"^]。



== 第三方数据保护



=== Veeam备份和复制

Veeam备份和复制是一种适用于云、虚拟和物理工作负载的备份、恢复和数据管理解决方案。Veeam Backup & Replication与NetApp Snapshot技术具有专门的集成、可进一步保护vSphere环境。

有关Veeam Backup & Replication的详细信息、请参见 https://www.veeam.com/vm-backup-recovery-replication-software.html["此链接。"^]。



== 公有云



=== AWS身份和访问管理

AWS环境包含多种产品、包括计算、存储、数据库、网络、分析、 以及更多有助于解决业务挑战的功能。企业必须能够定义有权访问这些产品、服务和资源的人员。同样重要的是、确定允许用户在哪些条件下操作、更改或添加配置。

AWS身份和访问管理(AWS Identity and Access Management、Aaim)提供了一个安全控制平台、用于管理对AWS服务和产品的访问。正确配置的用户、访问密钥和权限允许在AWS和Amazon FSX上部署VMware Cloud。

有关AIM"的详细信息、请参见 https://docs.aws.amazon.com/iam/index.html["此链接。"^]。



=== 基于 AWS 的 VMware Cloud

基于 AWS 的 VMware 云通过优化对原生 AWS 服务的访问，将 VMware 企业级 SDDC 软件引入 AWS 云。VMware Cloud on AWS由VMware Cloud Foundation提供支持、它将VMware的计算、存储和网络虚拟化产品(VMware vSphere、VMware vSAN和VMware NSX)与VMware vCenter Server管理功能相集成、并经过优化、可在专用的弹性裸机AWS基础架构上运行。

有关AWS上的VMware Cloud的详细信息、请参见 https://docs.vmware.com/en/VMware-Cloud-on-AWS/index.html["此链接。"^]。



=== 适用于 NetApp ONTAP 的 Amazon FSX

适用于NetApp ONTAP 的Amazon FSx是一款功能全面且受全面管理的ONTAP 系统、可作为原生 AWS服务使用。它基于NetApp ONTAP 构建、可提供熟悉的功能、同时还可提供完全托管的云服务的简便性。

适用于ONTAP 的Amazon FSX可为各种计算类型提供多协议支持、包括公有 云或内部环境中的VMware。适用于ONTAP 的Amazon FSX可用于当今的子系统连接用例以及技术预览版中的NFS数据存储库、支持企业从内部环境和云中利用熟悉的功能。

有关适用于NetApp ONTAP 的Amazon FSX的详细信息、请参见 https://aws.amazon.com/fsx/netapp-ontap/["此链接。"]。

link:aws-guest-dr-overview.html["接下来：概述—AWS子系统连接存储灾难恢复。"]
