---
sidebar: sidebar 
permalink: vmware/migrate-vms-to-ec2-fsxn.html 
keywords: netapp, vmware, amazon, ec2, fsxn, migration, iscsi, 
summary: '本技术报告介绍如何使用卷云迁移(CMC)的MigrateOps "数据移动性即代码"功能将内部VMware vSphere VM迁移到数据磁盘位于FSx ONTAP iSCSI LUN上的Amazon EC2实例。' 
---
= 使用Amazon FSx for ONTAP将VM迁移到Amazon EC2：概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
企业正在加快向AWS上的云计算解决方案的迁移速度、并利用Amazon Elel生 计算云(Amazon EC2)实例和Amazon FSx for NetApp ONTAP (FSx ONTAP)等服务来打造现代化的IT基础架构、节省成本并提高运营效率。这些AWS产品支持通过基于消费的定价模式和企业级存储功能来优化总拥有成本(TCO)的迁移、从而提供灵活性和可扩展性来满足不断变化的全球业务需求。



== 概述

对于在VMware vSphere上投入了大量资金的企业来说、在当前市场条件下、迁移到AWS是一个经济高效的选择、这是一个独特的机会。

随着这些企业过渡到AWS、他们希望在保留熟悉的功能集的同时、充分利用云的灵活性和成本优势、尤其是在存储方面。在迁移工作负载或设置灾难恢复解决方案时、使用熟悉的存储协议(尤其是iSCSI)流程、工具和技能组保持无缝操作至关重要。

利用AWS托管存储服务FSx ONTAP保留企业级存储功能(这些功能也来自任何第三方供应商的内部存储)、企业可以充分发挥AWS的潜能、同时最大限度地减少中断并最大限度地提高未来投资的价值。

本技术报告介绍如何使用卷云迁移(CMC)的MigrateOps "数据移动性即代码"功能将内部VMware vSphere VM迁移到数据磁盘位于FSx ONTAP iSCSI LUN上的Amazon EC2实例。



== 解决方案要求

VMware客户目前希望解决许多挑战。这些组织希望：

. 利用企业级存储功能、例如精简配置、存储效率技术、零占用空间克隆、集成备份、块级复制、 和层。这有助于优化迁移工作、并从第一天起在AWS上进行适应未来需求的部署。
. 通过整合FSx ONTAP及其提供的成本优化功能、优化当前使用Amazon EC2实例的AWS上的存储部署。
. 通过对Amazon EC2实例进行适当的规模估算以满足所需的IOPS和吞吐量参数、降低将Amazon EC2实例与块存储解决方案结合使用时的总拥有成本(TCO)。对于块存储、Amazon EC2磁盘操作具有带宽和I/O速率上限。使用FSx ONTAP的文件存储会使用网络带宽。换言之、FSx ONTAP没有VM级别的I/O限制。




== 技术组件概述



=== FSx ONTAP概念

Amazon FSx ONTAP是一项完全托管的AWS存储服务，可为NetApp®ONTAP®文件系统提供AWS上所有熟悉的ONTAP数据管理功能、性能和API。其高性能存储支持多种协议(NFS、SMB、iSCSI)、可为使用Windows、Linux和macOS EC2实例的工作负载提供单一服务。

由于FSx ONTAP是一个ONTAP文件系统，因此它具有许多熟悉的NetApp功能和服务，包括SnapMirror®数据复制技术、精简克隆和NetApp Snapshot™副本。通过数据分层利用低成本容量层、FSx ONTAP具有弹性、可实现几乎无限的扩展。此外、借助NetApp签名存储效率技术、它可以进一步降低AWS上的存储成本。有关详细信息，请参见link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSx ONTAP入门"]。



==== 文件系统

FSx ONTAP的核心资源是基于固态驱动器(Solid-State Drive、SSD)存储的文件系统。配置FSx ONTAP文件系统时、用户输入所需的吞吐量和存储容量、并选择文件系统所在的Amazon VPC。

用户还可以在文件系统的两种内置高可用性部署模式之间进行选择：多可用性区域(AZ)或单可用性区域部署。其中每个选项都提供自己的持久性和可用性级别、客户可以根据其使用情形的业务连续性要求进行选择。多可用性分区部署由双节点组成、可在两个可用性分区之间无缝复制。成本优化程度更高的单可用性(AZ)部署选项可将文件系统组织在两个节点中、这两个节点分别位于一个可用性(AZ)中的两个独立故障域之间。



=== Storage Virtual Machine

FSx ONTAP文件系统中的数据通过一个称为Storage Virtual Machine (SVM)的逻辑存储分区进行访问。SVM实际上是自己的文件服务器、配有自己的数据和管理访问点。访问FSx ONTAP文件系统上的iSCSI LUN时、Amazon EC2实例会使用SVM的iSCSI端点IP地址直接与SVM连接。

虽然可以在一个集群中维护一个SVM、但选择在一个集群中运行多个SVM具有广泛的用途和优势。客户可以根据业务需求(包括工作负载隔离要求)确定要配置的最佳SVM数量。



==== Volumes

FSx ONTAP SVM中的数据以称为卷的结构进行存储和组织、卷充当虚拟容器。可以为单个卷配置一个或多个LUN。存储在每个卷中的数据会占用文件系统中的存储容量。但是、由于FSx ONTAP会对卷进行精简配置、因此该卷只会占用所存储数据量的存储容量。



=== 卷云迁移云迁移运营概念

CMC是一款可交易的软件即服务(SaaS)产品、由美国国家/地区的Aclucian Data Solutions、Inc.提供、可通过AWS Marketplace获取。MigrateOps是CMC的数据移动即代码自动化功能、允许您使用YAML中的简单操作配置声明性地管理大规模数据移动操作。MigrateOps配置决定了您希望如何执行数据移动任务。要了解有关MigrateOps的更多信息、请参见 link:https://www.google.com/url?q=https://customer.cirrusdata.com/cdc/kb/articles/about-migrateops-hCCHcmhfbj&sa=D&source=docs&ust=1715480377722215&usg=AOvVaw033gzvuAlgxAWDT_kOYLg1["关于MigrateOps"]。

MigrateOps采用自动化优先的方法、专为简化整个流程而构建、可确保在不中断运营的情况下实现云规模企业级数据移动。除了CMC提供的功能丰富的自动化功能之外、MigrateOps还进一步添加了通常由外部管理的其他自动化功能、例如：

* 操作系统修复
* 应用程序转换和审批计划
* 零停机集群迁移
* 公共云/私有云平台集成
* 虚拟化平台集成
* 企业存储管理集成
* SAN (iSCSI)配置


在上述任务完全自动化的情况下、准备本机源虚拟机(例如添加AWS代理和工具)、创建目标FSx LUN、在AWS目标实例上设置iSCSI和多路径/MPIO的所有繁琐步骤、 只需在YAML文件中指定参数、即可消除停止/启动应用程序服务的所有任务。

FSx ONTAP用于提供数据LUN并合理调整Amazon EC2实例类型的大小、同时提供组织以前在其内部环境中拥有的所有功能。CMC的MigrateOps功能将用于自动执行所有相关步骤、包括配置映射的iSCSI LUN、从而将此操作转变为可预测的声明性操作。

*注意*：CMC要求在源和目标虚拟机实例上安装非常精简的代理、以确保从存储源存储到FSx ONTAP的安全数据传输。



== 将Amazon FSx ONTAP与EC2实例结合使用的优势

适用于Amazon EC2实例的FSx ONTAP存储具有以下优势：

* 高吞吐量和低延迟存储、可为要求最苛刻的工作负载提供稳定一致的高性能
* 智能NVMe缓存可提高性能
* 可调整的容量、吞吐量和IOPS可以随时更改、并快速适应不断变化的存储需求
* 从内部ONTAP存储到AWS的基于块的数据复制
* 多协议可访问性、包括iSCSI、该功能在内部VMware部署中广泛使用
* 由SnapMirror协调的NetApp SnapSnapshot™技术和灾难恢复可防止数据丢失并加快恢复速度
* 可减少存储占用空间和成本的存储效率功能、包括精简配置、重复数据删除、数据压缩和数据缩减
* 高效复制可将创建备份所需的时间从数小时缩短到几分钟、从而优化了ROTO
* 使用NetApp SnapCenter®进行文件备份和恢复的粒度选项


使用FSx ONTAP部署Amazon EC2实例作为基于iSCSI的存储层、可提供高性能、任务关键型数据管理功能以及降低成本的存储效率功能、帮助您转变AWS上的部署方式。

FSx ONTAP运行Flash Cache、多个iSCSI会话、并利用5%的工作集大小、可以提供~35万次的IOPS、从而提供可满足最密集工作负载要求的性能级别。

由于FSx ONTAP仅会应用网络带宽限制、而不会应用块存储带宽限制、因此用户可以利用小型Amazon EC2实例类型、同时实现与大型实例类型相同的性能速率。使用此类小型实例类型还可以降低计算成本、从而优化TCO。

FSx ONTAP提供多个协议的能力是另一个优势、它有助于标准化一个AWS存储服务、以满足各种现有数据和文件服务要求。对于在VMware vSphere上投入了大量资金的企业来说、在当前市场条件下、迁移到AWS是一个经济高效的选择、这是一个独特的机会。
