---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-hybrid-multicloud.html 
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud 
summary:  
---
= 混合多云
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
采用NetApp的VMware混合多云架构支持在内部基础架构和公有云服务之间无缝集成、从而提供灵活性和可扩展性。



== 简介

通过这种方法、企业可以轻松迁移工作负载、优化资源使用、并在两种环境之间保持一致的运营。

有关使用VMware和NetApp的混合云方案的详细信息，请参见link:https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-overview.html#vmware-cloud-options-in-public-cloud["NetApp混合多云与VMware概述"]。



== 使用NetApp的VMware部署方案

本节介绍了跨内部环境和公有云的各种VMware环境部署选项。每个云提供商都在其各自的公有云产品中支持VMware软件定义的数据中心(SDDC)和/或VMware Cloud Foundation (VCF)堆栈。

* *VMware内部*


将VMware与内部NetApp存储结合使用可提供一个强大、可扩展且灵活的虚拟化环境。通过将NetApp的高级数据管理功能(如重复数据删除、数据压缩和高效快照)与由ONTAP提供支持的相应存储系统进行配对、客户可以选择适合他们的平台。这种组合可确保为虚拟化工作负载提供高性能、可靠性和简化的管理、从而提高数据中心的整体效率。

* *Azure VMware解决方案*


Azure VMware 解决方案是一种混合云服务，支持在 Microsoft Azure 公有云中实现完全正常运行的 VMware SDDC 。Azure VMware 解决方案是由 Microsoft 全面管理和支持的第一方解决方案，由 VMware 利用 Azure 基础架构进行验证。这意味着，在部署 Azure VMware 解决方案时，客户可以获得用于计算虚拟化的 VMware ESXi ，用于超融合存储的 vSAN ， 和 NSX 实现网络连接和安全性，同时充分利用 Microsoft Azure 的全球影响力，一流的数据中心设施以及邻近丰富的原生 Azure 服务和解决方案生态系统的优势。

* *基于AWS*的VMware Cloud


基于 AWS 的 VMware 云通过优化对原生 AWS 服务的访问，将 VMware 企业级 SDDC 软件引入 AWS 云。VMware Cloud on AWS 由 VMware Cloud Foundation 提供支持，它将 VMware 的计算，存储和网络虚拟化产品（ VMware vSphere ， VMware vSAN 和 VMware NSX ）与 VMware vCenter Server 管理相集成，并经过优化，可在专用的弹性裸机 AWS 基础架构上运行。

* *Google Cloud VMware Engine*


Google Cloud VMware Engine是一款基于Google Cloud高性能可扩展基础架构和VMware Cloud Foundation堆栈(VMware vSphere、vCenter、vSAN和NSX-T)构建的基础架构即服务(Infrastructure as a-Service、IaaS)产品。通过此服务、您可以快速迁移到云、将现有VMware工作负载从内部环境无缝迁移或扩展到Google Cloud Platform、而无需重新构建应用程序或重新部署操作、付出成本、精力或风险。这是一项由 Google 销售和支持的服务，与 VMware 密切合作。
