---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= FC上的VMFS作为VI工作负载域的主存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在此情景中、我们将介绍如何配置使用光纤通道(Fibre Channel、FC)作为主存储的VMFS数据存储库、以便在VCF中部署VI工作负载域。我们将在适当的情况下参考外部文档、了解在VCF的SDDC Manager中必须执行的步骤、并介绍特定于存储配置部分的步骤。



== 光纤通道的优势

*高性能：* FC提供高速数据传输速率、非常适合需要快速可靠地访问大量数据的应用程序。

*低延迟：*极低延迟，这对于数据库和虚拟化环境等性能敏感型应用程序至关重要。

*可靠性：* FC网络因其稳健性和可靠性而闻名、具有内置冗余和纠错等功能。

*专用带宽：* FC为存储流量提供专用带宽、降低网络拥塞的风险。

有关在NetApp存储系统中使用光纤通道的详细信息，请参阅 https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["使用FC配置SAN"]。



== 方案概述

此情景包括以下高级步骤：

* 为FC流量创建具有逻辑接口(Logical Interface、Logical Interface、Logical Interface、
* 收集要部署的主机的WWPN信息、并在ONTAP存储系统上创建相应的启动程序组。
* 在ONTAP存储系统上创建FC卷。
* 映射启动程序组以创建FC卷
* 在FC交换机上使用单个启动程序-目标分区。为每个启动程序创建一个分区（单个启动程序分区）。
+
** 对于每个分区，包括一个目标，该目标是 SVM 的 ONTAP FC 逻辑接口（ WWPN ）。每个 SVM 的每个节点至少应有两个逻辑接口。请勿使用物理端口的 WWPN 。


* 在SDDC Manager中为vMotion流量创建网络池。
* 在VCF中配置主机以在VI工作负载域中使用。
* 使用FC数据存储库作为主存储、在VCF中部署VI工作负载域。



NOTE: 此解决方案适用于支持NFS存储的ONTAP平台、包括NetApp AFF和FAS。



== 前提条件

在此情景中、将使用以下组件和配置：

* FC端口连接到FC交换机的ONTAP AFF或ASA存储系统。
* 已使用FC SVM创建SVM。
* 使用FC HBA连接到FC交换机的vSphere。
* 在FC交换机上配置了单个启动程序-目标分区。



NOTE: NetApp建议为FC LUN使用多路径。



== 部署步骤



=== 管理域-默认集群

只有VCF brownfield导入工具才支持初始集群上的FC主体存储。如果VCF是随云构建器工具部署的(截至版本5.2.x)、则仅支持VSAN。有关详细信息、请参见 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["将现有vSphere环境转换为管理域"]。



=== 管理域—附加集群

可以使用以下选项部署管理域上的其他vSphere集群：*在vSphere环境中部署其他集群、并使用VCF brownfield导入工具将vSphere环境转换为管理域。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["适用于 VMware vSphere 的 ONTAP 工具"] https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager或ONTAP API"]可用于将VMFS数据存储库部署到vSphere集群。*使用SDDC API部署其他集群。vSphere主机应已配置VMFS数据存储库。 https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager或ONTAP API"]用于将LUN部署到vSphere主机。*使用SDDC Manager UI部署其他集群。但是、此选项仅会创建版本5.2.x之前的VSAN数据存储库



=== VI工作负载域—默认集群

管理域启动并运行后、可以创建VI工作负载域：

* 使用SDDC Manager UI。vSphere主机应已配置VMFS数据存储库。使用System Manager或ONTAP API将LUN部署到vSphere主机。
* 将现有vSphere环境导入为新的VI工作负载域。可以使用适用于VMware vSphere、System Manager或ONTAP API的ONTAP工具将VMFS数据存储库部署到vSphere集群。




=== VI工作负载域—附加集群

VI工作负载启动并运行后、可以使用以下选项在FC LUN上使用VMFS部署其他集群。

* vSphere环境中使用VCF brownfield导入工具导入的其他集群。可以使用适用于VMware vSphere、System Manager或ONTAP API的ONTAP工具将VMFS数据存储库部署到vSphere集群。
* 使用SDDC Manager UI或API部署其他集群。vSphere主机应已配置VMFS数据存储库。使用System Manager或ONTAP API将LUN部署到vSphere主机。




== 追加信息

有关配置ONTAP存储系统的信息、请参见 link:https://docs.netapp.com/us-en/ontap["ONTAP 9文档"] 中心。

有关配置VCF的信息，请参见link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation文档"]。
