---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-ontap-apis-automation.html 
keywords:  
summary:  
---
= 使用NetApp API增强VMware管理功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
API (应用程序编程接口)可以实现虚拟化环境的自动化、集成和简化管理、在VMware管理中发挥着至关重要的作用。



== 简介

VMware提供了一系列API，允许管理员以编程方式与各种VMware产品和服务进行交互，从而提高了操作的效率和一致性。此外、NetApp ONTAP API还提供了一组强大的工具、使管理员能够自动执行、集成和优化存储环境的管理、尤其是与VMware工作负载结合使用时。这些API有助于在ONTAP存储系统和VMware之间实现无缝交互、从而提高效率、性能和数据保护。



== 基于VMware的API

* *VMware vSphere API：* vSphere API是一种全面的API，允许管理员管理和自动化VMware vSphere环境。您可以通过它访问各种vSphere功能、包括虚拟机配置、配置、监控和生命周期管理。
* *VMware vCenter Server REST API：* vCenter Server REST API提供了一个现代化的REST风格的界面，用于管理vCenter Server及其关联组件。它简化了自动化以及与其他系统和工具的集成。
* *VMware Cloud Foundation API：* VMware软件定义的数据中心(SDDC)API可通过编程方式访问VMware SDDC环境中的各种组件和服务。借助这些API、管理员和开发人员可以自动执行、管理和集成数据中心的各个方面、包括计算、存储、网络和管理服务。
* *VMware vSphere存储API -存储感知：* VASA,是一组API，可将存储阵列与vCenter集成在一起进行管理。该架构基于多个组件、包括负责处理VMware vSphere与存储系统之间通信的VASA Provider。借助ONTAP、该提供程序可作为适用于VMware vSphere的ONTAP工具的一部分来实施。
* *VMware vSphere Storage APIs - Array Integration：* Vaai是一组API、用于在VMware vSphere ESXi主机和存储设备之间进行通信。API包括一组原始操作、主机使用这些操作将存储操作卸载到阵列。VAAI可以显著提高存储密集型任务的性能。




== 基于ONTAP的API

* * NetApp ONTAP REST API:* ONTAP REST API为管理ONTAP存储系统提供了一个现代化的REST风格的界面。它简化了配置、监控和配置等存储任务的自动化。它可以轻松地与VMware vSphere和其他VMware管理工具集成、从而可以直接从VMware环境自动执行存储操作。它支持从基本存储管理到高级数据保护和复制任务等各种操作、从而实现可扩展的灵活存储管理。
* *适用于VMware vSphere的ONTAP工具：*适用于VMware vSphere的ONTAP工具是一组用于集成ONTAP和vSphere的工具。它可实施VASA API框架的提供程序功能。ONTAP工具还包括vCenter插件、适用于VMware Site Recovery Manager的存储复制适配器(Storage Replication Adapter、SRA)以及可用于构建自动化应用程序的REST API服务器。




== 摘要

总之、借助ONTAP API、管理员可以在VMware环境中为数据存储库的创建和配置编写脚本、从而确保快速一致地配置存储。此外、他们还可以自动为VMware虚拟机创建、计划和删除快照、从而提供高效的数据保护和恢复选项。SnapMirror API有助于实现复制关系设置和管理的自动化、从而确保为VMware工作负载提供强大的灾难恢复解决方案。管理员还可以实施脚本来监控存储性能指标、并在违反性能阈值时触发警报或自动操作、从而确保为VMware工作负载提供最佳存储性能。通过将ONTAP API与VMware API (例如vSphere和vReise提供的API)相集成、管理员可以获得无缝且高度自动化的管理体验、从而提高其虚拟化基础架构的整体效率和可靠性。
