---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-ontap-tools-for-vmware.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= 适用于VMware的ONTAP工具(OTV)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
适用于VMware vSphere的ONTAP工具可为使用NetApp存储系统的VMware环境中的虚拟机提供端到端生命周期管理。



== 简介

通过它、管理员可以直接管理vCenter Server中的存储、并简化VMware环境的存储和数据管理。VMware vSphere Client插件工具旨在将插件功能集成到vSphere Client中、而无需在vCenter Server中运行。这样可以隔离插件、并可横向扩展在大型vSphere环境中运行的插件。



== ONTAP工具组件

* *虚拟存储控制台(VSC)* VSC包括与vSphere客户端集成的界面、您可以在其中添加存储控制器、配置数据存储库、监控数据存储库的性能以及查看和更新ESXi主机设置。
* *VASA Provider*适用于ONTAP的VMware vSphere存储感知API (VASA)提供程序可将有关VMware vSphere所用存储的信息发送到vCenter Server、从而可以配置VMware虚拟卷(VVOl)数据存储库、创建和使用存储功能配置文件、验证合规性以及监控性能。
* *Storage Replication Adapter (SRA)*启用并与VMware Site Recovery Manager (SRM)结合使用后，SRA可以在发生故障时帮助恢复vCenter Server数据存储库和虚拟机，从而可以配置受保护站点和恢复站点以进行灾难恢复。


有关适用于VMware的NetApp ONTAP工具的详细信息、请参见 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["适用于 VMware vSphere 的 ONTAP 工具文档"]。
