---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-bluexp-disaster-recovery.html 
keywords: vmware, getting, started, overview, netapp, bluexp, disaster, recovery, draas 
summary:  
---
= BlueXP  灾难恢复(DRaaS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
灾难恢复规划对于VMware管理员来说至关重要、它可以在发生硬件故障、网络攻击或自然灾害时最大限度地减少停机时间。



== 简介

制定一个成功的计划并将多种技术相结合、可确保关键数据、应用程序和VM得到保护。灾难恢复面临的挑战是确定适当的保护级别和相关成本。

ONTAP阵列提供内置复制功能、可将卷数据以及指定数据存储库LUN上的虚拟机从一个站点传输到另一个站点。BlueXP  DRaaS可与vSphere集成并自动执行整个工作流、以便在发生灾难时实现无缝故障转移和故障恢复。

有关BlueXP  DRaaS的详细信息，请参见link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-overview.html["BlueXP  DRaaS概述"]。



== 注意事项

在VMware vSphere环境中、灾难恢复故障转移最耗时的部分是执行必要的步骤来清点、注册、重新配置和启动灾难恢复站点上的VM。理想的解决方案既具有较低的RPO (以分钟为单位)、又具有较低的RTO (以分钟到小时为单位)。在灾难恢复解决方案中、一个经常被忽略的因素是定期有效测试灾难恢复解决方案的能力。

在设计灾难恢复解决方案时、请牢记以下因素：

* 恢复时间目标(Recovery Time目标、Recovery Time目标、Recovery Time目标、Recovery Time恢复时间是指企业从灾难中恢复的速度、或者更具体地说、恢复过程需要多长时间才能使业务服务再次恢复可用。
* 恢复点目标(RPO)。RPO是指恢复数据可用后的时长(相对于灾难发生时间)。
* 可扩展性和适应性。这一因素包括能够随着需求的增加逐步增加存储资源。


有关可用解决方案的更多技术信息、请参见：

* link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-nfs.html["使用BlueXP  DRaaS对NFS数据存储库执行灾难恢复"]
* link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-vmfs.html["使用BlueXP  DRaaS对VMFS数据存储库执行灾难恢复"]

