---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-security-ransomware.html 
keywords:  
summary:  
---
= 解决VMware工作负载的安全性和防软件问题
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
降低VMware环境中的中断风险对于保持业务持续运营、确保关键应用程序的高可用性以及防止数据丢失至关重要。



== 简介

通过在VMware环境中利用NetApp ONTAP的高级功能、企业可以确保其数据的完整性、可用性和安全性。

请参见下面的内容，了解这些技术如何协同工作，以提供*安全性*和*备份优势*的详细信息。



== 安全性和防兰森

安全性是虚拟化环境中最关注的问题、NetApp ONTAP提供了强大的功能来增强VMware基础架构中的安全性。ONTAP可对空闲数据和传输中的数据进行加密、确保敏感信息不会受到未经授权的访问。加密密钥得到安全管理、ONTAP既支持基于软件的加密解决方案、也支持基于硬件的加密解决方案。通过与VMware的安全工具(例如vSphere的内置安全功能和第三方安全解决方案)相集成、ONTAP有助于创建安全合规的环境。



== 勒索软件防御

勒索软件攻击对组织构成重大威胁、VMware和ONTAP相结合可提供强大的防御机制。ONTAP的Snapshot技术支持创建不可变的快照、勒索软件无法更改或删除这些快照。在发生攻击时、可以使用这些快照将受影响的虚拟机和数据存储库快速还原到攻击前的状态、从而最大限度地减少停机和数据丢失。此外、ONTAP与安全信息和事件管理(SIEM)系统的集成还可以主动监控可疑活动并发出警报。ONTAP还支持多因素身份验证(MFA)和基于角色的访问控制(Role-Based Access Control、RBAC)、以进一步增强安全性。



== 勒索软件恢复担保

NetApp勒索软件担保计划为企业提供了强大可靠的解决方案来防范勒索软件攻击。通过利用NetApp ONTAP的高级功能、企业可以确保数据的安全性和可用性。这项保证让您高枕无忧、因为我们知道、一旦发生勒索软件攻击、数据可以快速有效地还原、最大程度地减少停机、数据丢失和财务影响。NetApp对数据安全和弹性的承诺使其成为希望保护其关键资产免受不断演变的网络威胁的组织的理想合作伙伴。



== 高级安全功能

ONTAP提供了一些高级安全功能、例如安全多租户功能(用于隔离多租户环境中的数据和资源)以及合规性审核功能(用于跟踪和记录对敏感数据的访问)。这些功能可确保数据始终安全、并确保企业能够证明符合行业法规和标准。



== 摘要

ONTAP的安全功能(例如加密、不可变更的快照和高级访问控制)与VMware工具相集成、可以针对勒索软件等网络威胁提供强大的防护。ONTAP支持安全多租户和合规性审核、可确保数据保护和合规性。

NetApp ONTAP和VMware共同提供了一个全面的解决方案来保护虚拟化环境的安全、使企业能够保护数据、最大限度地减少停机时间并保持业务连续性。实施这些技术有助于企业应对现代IT挑战、并保护关键资产免受不断演变的安全威胁的影响。
