---
sidebar: sidebar 
permalink: vmware/vmware_vcf_aff_prin_fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= FC上用作VCF主体数据存储库的VMFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在此情景中、我们将演示如何为管理和工作负载域部署具有光纤通道(Fibre Channel、FC)后端的VMFS数据存储库。

作者：Sresh Thoppay



== 方案概述

vcf主体存储是指在VCF域设置过程中部署、转换或导入的任何类型的存储。本文档涵盖以下情形。

[cols="20% 20% 20% 20% 20%"]
|===
| 存储类型 | 管理域-默认集群 | 管理域—附加集群 | VI工作负载域—默认集群 | VI工作负载域—附加集群 


| FC上的VMFS | *导入工具* | *导入工具、SDDC API* | 是的。 | 是的。 
|===


== 前提条件

此方案需要以下组件和配置：

* FC端口连接到FC交换机的ONTAP存储系统。
* 已使用FC SVM创建SVM。
* 使用FC HBA连接到FC交换机的vSphere。
* 在FC交换机上配置了单个启动程序-目标分区。
+

NOTE: 在区域配置中使用SVM FC逻辑接口、而不是在ONTAP系统上使用物理FC端口。



NetApp建议为FC LUN使用多路径。



== 部署步骤



=== 管理域-默认集群

只有VCF brownfield导入工具才支持初始集群上的FC主体存储。如果VCF是使用云构建工具部署的(截至版本5.2.x)、则仅支持VSAN。有关详细信息、请参见 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["将现有vSphere环境转换为管理域"]。



=== 管理域—附加集群

可以使用以下选项部署管理域上的其他vSphere集群：*在vSphere环境中部署其他集群、并使用VCF brownfield导入工具将vSphere环境转换为管理域。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["适用于 VMware vSphere 的 ONTAP 工具"] https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager或ONTAP API"]可用于将VMFS数据存储库部署到vSphere集群。*使用SDDC API部署其他集群。vSphere主机应已配置VMFS数据存储库。 https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["System Manager或ONTAP API"]用于将LUN部署到vSphere主机。*使用SDDC Manager UI部署其他集群。但是、此选项仅会创建版本5.2.x之前的VSAN数据存储库



=== VI工作负载域—默认集群

管理域启动并运行后、可以使用SDDC Manager用户界面*创建VI工作负载域。vSphere主机应已配置VMFS数据存储库。使用System Manager或ONTAP API将LUN部署到vSphere主机。*将现有vSphere环境导入为新的VI工作负载域。可以使用适用于VMware vSphere、System Manager或ONTAP API的ONTAP工具将VMFS数据存储库部署到vSphere集群。



=== VI工作负载域—附加集群

VI工作负载启动并运行后、可以使用以下选项在FC LUN上使用VMFS部署其他集群。

* vSphere环境中使用VCF brownfield导入工具导入的其他集群。可以使用适用于VMware vSphere、System Manager或ONTAP API的ONTAP工具将VMFS数据存储库部署到vSphere集群。
* 使用SDDC Manager UI或API部署其他集群。vSphere主机应已配置VMFS数据存储库。使用System Manager或ONTAP API将LUN部署到vSphere主机。




== 追加信息

有关配置ONTAP存储系统的信息、请参见 link:https://docs.netapp.com/us-en/ontap["ONTAP 9文档"] 中心。

有关配置VCF的信息，请参见link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation文档"]。
