---
sidebar: sidebar 
permalink: vmware/vsphere_auto_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: 本页介绍在 VMware vSphere 环境中自动执行基本 ONTAP 功能的优势。 
---
= ONTAP 和 vSphere 自动化简介
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本页介绍在 VMware vSphere 环境中自动执行基本 ONTAP 功能的优势。



== VMware 自动化

自 VMware ESX 推出以来，自动化已成为管理 VMware 环境不可或缺的一部分。能够将基础架构作为代码进行部署，并将实践扩展到私有云操作，有助于缓解对规模，灵活性，自行配置和效率的顾虑。

自动化可以分为以下几类：

* * 虚拟基础架构部署 *
* * 来宾计算机操作 *
* * 云操作 *


管理员可以选择多种方法来实现基础架构自动化。无论是通过将虚拟机的主机配置文件或自定义规范等原生 vSphere 功能用于 VMware 软件组件，操作系统和 NetApp 存储系统上的可用 API ，均可获得大量文档和指导。

如果 ESX 主机运行的是 ESX 4.1 或更高版本，则 Data ONTAP 8.0.1 及更高版本支持某些 VMware vSphere API for Array Integration （ VAAI ）功能。VAAI 是一组 API ，用于在 VMware vSphere ESXi 主机和存储设备之间进行通信。这些功能有助于将操作从 ESX 主机卸载到存储系统，并提高网络吞吐量。ESX 主机会在正确的环境中自动启用这些功能。您可以通过检查 VAAI 计数器中的统计信息来确定系统使用 VAAI 功能的程度。

自动部署 VMware 环境的最常见起点是配置基于块或文件的数据存储库。在开发相应的自动化之前，必须确定实际任务的要求。

有关 VMware 环境自动化的详细信息，请参见以下资源：

* https://netapp.io/configuration-management-and-automation/["NetApp Pub"^]。NetApp 配置管理和自动化。
* https://galaxy.ansible.com/community/vmware["适用于 VMware 的 Ansible GALAXY 社区"^]。一组适用于 VMware 的 Ansible 资源。
* https://community.broadcom.com/vmware-code/home["VMware ｛ code ｝ 资源"^](英文)为软件定义的数据中心设计解决方案所需的资源，包括论坛，设计标准，示例代码和开发人员工具。

