---
sidebar: sidebar 
permalink: ai/ai-edge-conclusion.html 
keywords: acknowledgements, additional information 
summary: AI 驱动的自动化和边缘计算是帮助业务组织实现数字化转型并最大限度地提高运营效率和安全性的领先方法。借助边缘计算，数据处理速度更快，因为它不必往返于数据中心。因此，将数据来回发送到数据中心或云的相关成本会降低。 
---
= 结论
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
AI 驱动的自动化和边缘计算是帮助业务组织实现数字化转型并最大限度地提高运营效率和安全性的领先方法。借助边缘计算，数据处理速度更快，因为它不必往返于数据中心。因此，将数据来回发送到数据中心或云的相关成本会降低。如果企业必须使用部署在边缘的人工智能推理模型近乎实时地做出决策，则降低延迟和提高速度将非常有用。

NetApp 存储系统可提供与本地 SSD 存储相同或更好的性能，并为数据科学家，数据工程师， AI/ML 开发人员以及业务或 IT 决策者带来以下优势：

* 在 AI 系统，分析和其他关键业务系统之间轻松共享数据。这种数据共享可减少基础架构开销，提高性能并简化整个企业的数据管理。
* 可独立扩展的计算和存储，最大限度地降低成本并提高资源利用率。
* 利用集成的 Snapshot 副本和克隆简化开发和部署工作流，实现瞬时且节省空间的用户工作空间，集成版本控制和自动化部署。
* 企业级数据保护，可实现灾难恢复和业务连续性。本文档中介绍的 NetApp 和联想解决方案是一种灵活的横向扩展架构，非常适合在边缘进行企业级 AI 推理部署。




== 致谢

* J.Falkanger ，高级联想 HPC & AI 解决方案经理
* NetApp 技术营销工程师 Dave Arnette
* NetApp E 系列 AI 解决方案技术主管 Joey Parnell
* NetApp QA 工程师 Cody Harryman




== 从何处查找追加信息

要了解有关本文档中所述信息的更多信息，请参见以下文档和 / 或网站：

* NetApp AFF A 系列阵列产品页面
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* NetApp ONTAP 数据管理软件— ONTAP 9 信息库
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727 ：《 NetApp EF 系列简介》
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* NetApp E 系列 SANtricity 软件产品规格
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* 适用于容器的 NetApp 持久存储— NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* NetApp BlueXP复制和同步
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* TensorFlow 基准测试
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* 联想 ThinkSystem SE350 边缘服务器
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* 联想 ThinkSystem DM5100F 统一闪存存储阵列
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"]


