---
sidebar: sidebar 
permalink: ai/ai-sent-deploying-support-center-sentiment-analysis.html 
keywords: deploy, NetApp DataOps Toolkit, NGC Configuration, NVIDIA RIVA Server, NVIDIA TAO Toolkit, Export TAO models to RIVA 
summary: 本节介绍部署此解决方案所需的详细步骤。 
---
= 部署支持中心观点分析
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-sent-design-considerations.html["先前：设计注意事项。"]

部署解决方案涉及以下组件：

. NetApp DataOps 工具包
. NGC 配置
. NVIDIA Riva 服务器
. NVIDIA TAO 工具包
. 将 TAO 模型导出到 Riva


要执行部署，请完成以下步骤：



== NetApp DataOps 工具包：支持中心情感分析

以使用 https://github.com/NetApp/netapp-dataops-toolkit["NetApp DataOps 工具包"^]，完成以下步骤：

. 通过 Pip 安装工具包。
+
....
python3 -m pip install netapp-dataops-traditional
....
. 配置数据管理
+
....
netapp_dataops_cli.py config
....




== NGC 配置：支持中心情感分析

进行设置 https://ngc.nvidia.com/setup/installers/cli["NVIDIA NGC"^]，完成以下步骤：

. 下载 NGC 。
+
....
wget -O ngccli_linux.zip https://ngc.nvidia.com/downloads/ngccli_linux.zip && unzip -o ngccli_linux.zip && chmod u+x ngc
....
. 将当前目录添加到路径。
+
....
echo "export PATH=\"\$PATH:$(pwd)\"" >> ~/.bash_profile && source ~/.bash_profile
....
. 您必须配置 NGC 命令行界面以供使用，才能运行命令。出现提示时，输入以下命令，包括 API 密钥。
+
....
ngc config set
....


对于不基于 Linux 的操作系统，请访问 https://ngc.nvidia.com/setup/installers/cli["此处"^]。



== NVIDIA Riva 服务器：支持中心情感分析

进行设置 https://docs.nvidia.com/deeplearning/riva/user-guide/docs/quick-start-guide.html["NVIDIA RIVA"^]，完成以下步骤：

. 从 NGC 下载 Riva 文件。
+
....
ngc registry resource download-version nvidia/riva/riva_quickstart:1.4.0-beta
....
. 初始化 Riva 设置（`Riva_init.sh` ）。
. 启动 Riva 服务器（`Riva_start.sh` ）。
. 启动 Riva 客户端（`Riva_start_client.sh` ）。
. 在 Riva 客户端中，安装音频处理库（ https://ffmpeg.org/download.html["FFmpeg"^]）
+
....
apt-get install ffmpeg
....
. 启动 https://jupyter-server.readthedocs.io/en/latest/["Jupyter"^] 服务器
. 运行 Riva 推理管道笔记本电脑。




== NVIDIA TAO 工具包：支持中心情感分析

要设置 NVIDIA TAO 工具包，请完成以下步骤：

. 准备并激活 https://docs.python.org/3/library/venv.html["虚拟环境"^] 适用于 TAO 工具包。
. 安装 https://docs.nvidia.com/tao/tao-toolkit/text/tao_toolkit_quick_start_guide.html["所需的软件包"^]。
. 手动拉取训练和微调期间使用的图像。
+
....
docker pull nvcr.io/nvidia/tao/tao-toolkit-pyt:v3.21.08-py3
....
. 启动 https://jupyter-server.readthedocs.io/en/latest/["Jupyter"^] 服务器
. 运行 TAO 微调笔记本电脑。




== 将 TAO 模型导出到 Riva ：支持中心情感分析

以使用 https://docs.nvidia.com/tao/tao-toolkit/text/riva_tao_integration.html["Riva 中的 TAO 工具包模型"^]，完成以下步骤：

. 将模型保存在 TAO 微调笔记本中。
. 将经过 TAO 训练的型号复制到 Riva 型号目录。
. 启动 Riva 服务器（`Riva_start.sh` ）。




== 部署障碍

在开发您自己的解决方案时，请谨记以下几点：

* 首先安装 NetApp DataOps 工具包，以确保数据存储系统以最佳状态运行。
* 必须先安装 NVIDIA NGC ，再安装其他任何版本，因为它会对映像和型号的下载进行身份验证。
* 必须先安装 Riva ，然后再安装 TAO 工具包。Riva 安装会根据需要配置 Docker 守护进程以提取映像。
* DGX 和 Docker 必须能够访问 Internet 才能下载这些型号。


link:ai-sent-validation-results.html["接下来：验证结果"]
