---
sidebar: sidebar 
permalink: ai/ai-sent-support-center-analytics.html 
keywords: tr-4910, tr4910, 4910, sentiment, analysis, customer value, support center, artificial intelligence 
summary: 本技术报告为客户在企业级全球支持中心内使用 NetApp 数据管理技术和 NVIDIA 软件框架以及传输学习和对话 AI 执行情感分析提供了设计指导。 
---
= TR-4910 ：《利用 NetApp AI 进行客户沟通时的情感分析》
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


SML 科学公司 Rick Huang ， Sathish Thyagarajan 和 NetApp 公司迭戈 Sosa-Coba 的 David Arnette

本技术报告为客户在企业级全球支持中心内使用 NetApp 数据管理技术和 NVIDIA 软件框架以及传输学习和对话 AI 执行情感分析提供了设计指导。此解决方案适用于希望从代表聊天日志，电子邮件和其他文本或音频通信的录制语音或文本文件中获得客户见解的任何行业。我们实施了一个端到端管道，用于在采用 NetApp 云连接全闪存存储的 GPU 加速计算集群上展示自动语音识别，实时情感分析和深度学习的自然语言处理模式 - 再培训功能。可以对大规模的一流语言模型进行培训和优化，以便与全球支持中心快速进行推理，从而打造卓越的客户体验，并对员工的长期业绩进行客观评估。

情绪分析是自然语言处理（ NLP ）中的一个研究领域，通过该领域，可以从文本中提取积极，负面或中立的情绪。随着越来越多的人与人工智能系统互动，对话式人工智能系统的集成程度已提升到接近全球水平。情感分析有多种使用情形，从确定支持中心员工在与来电者对话中的表现，提供适当的自动聊天机器人响应，到根据公司代表与受众在季度收益通话中的互动预测公司的股票价格。此外，情感分析可用于确定客户对品牌提供的产品，服务或支持的看法。

此端到端解决方案使用 NLP 模型执行高级别的情感分析，从而支持支持中心分析框架。录音会处理成书面文本，并从对话的每一句话中提取情感。可以将结果汇总到信息板中，以便对对话感受进行分析，包括历史和实时分析。此解决方案可以概括为具有类似数据模式和输出需求的其他解决方案。利用适当的数据，可以完成其他使用情形。例如，可以使用相同的端到端管道分析公司收益调用的情绪。由于管道的灵活性，还可以进行其他形式的 NLP 分析，例如主题建模和命名实体识别（ NER ）。

NVIDIA Riva ， NVIDIA TAO 工具包和 NetApp DataOps 工具包共同实现了这些 AI 实施。NVIDIA 的工具可用于使用预构建的型号和管道快速部署高性能 AI 解决方案。NetApp DataOps 工具包可简化各种数据管理任务，以加快开发速度。



== 客户价值

企业可以通过员工评估和客户响应工具在文本，音频和视频对话中获得价值，以便进行情绪分析。经理可以从信息板中提供的信息中受益，从而可以根据对话的两个方面评估员工和客户满意度。

此外， NetApp DataOps 工具包还可管理客户基础架构中数据的版本控制和分配。这样就会频繁更新信息板中提供的分析，而不会产生庞大的数据存储成本。

link:ai-sent-use-cases.html["下一步：用例"]
