---
sidebar: sidebar 
permalink: ai/ai-sent-validation-results.html 
keywords: validation, errors, metrics, score, recall, precision 
summary: 如上一节所述，只要有两个或更多机器学习模型按顺序运行，错误就会传播到整个管道中。对于此解决方案，句子的感受是衡量公司股票风险水平的最重要因素。语音到文本模式虽然对管道至关重要，但在预测情感之前，它是预处理单元。 
---
= 验证结果
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:ai-sent-deploying-support-center-sentiment-analysis.html["先前：部署支持中心观点分析。"]

[role="lead"]
如上一节所述，只要有两个或更多机器学习模型按顺序运行，错误就会传播到整个管道中。对于此解决方案，句子的感受是衡量公司股票风险水平的最重要因素。语音到文本模式虽然对管道至关重要，但在预测情感之前，它是预处理单元。真正重要的是基本事实句子与预测的句子之间的情感差异。此选项用作错误率（ WER ）一词的代理。语音到文本的准确性非常重要，但 WER 不会直接用于最终管道指标。

....
PIPELINE_SENTIMENT_METRIC = MEAN(DIFF(GT_sentiment, ASR_sentiment))
....
可以根据每句话的 F1 分数，回顾和精确度计算这些情感指标。然后，可以汇总结果并将其显示在混乱列表中，同时还可以显示每个指标的置信区间。

使用传输学习的优势在于，模型性能提高，只需满足极少的数据要求，培训时间和成本。此外，还应将经过微调的模型与其基线版本进行比较，以确保传输学习可以提高性能，而不会影响性能。换言之，经过微调的模型在支持中心数据上的性能应比预先训练的模型更好。



== 渠道评估

|===
| 测试用例 | 详细信息 


| 测试编号 | 渠道感受指标 


| 测试前提条件 | 经过微调的语音到文本和情感分析模型模型 


| 预期结果 | 经过微调的模型的情感指标比原始的预先训练模型的性能更好。 
|===


== 渠道感受指标

. 计算基线模型的情感指标。
. 计算经过微调的模型的情感指标。
. 计算这些指标之间的差异。
. 计算所有句子之间的差异平均值。


link:ai-sent-videos-and-demos.html["接下来：视频和演示。"]
