---
sidebar: sidebar 
permalink: ai/aicp_netapp_trident_deployment_and_configuration_overview.html 
keywords: Trident, Kubernetes, Storageclass 
summary: 此页面介绍了在 Kubernetes 集群中安装和配置 NetApp Trident 时必须完成的任务。 
---
= NetApp Trident 部署和配置
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本节介绍在 Kubernetes 集群中安装和配置 NetApp Trident 时必须完成的任务。



== 前提条件

在执行本节所述的部署练习之前，我们假定您已执行以下任务：

. 您已有一个有效的 Kubernetes 集群，并且正在运行 Trident 支持的 Kubernetes 版本。有关支持的版本列表，请参见 https://netapp-trident.readthedocs.io/["Trident 文档"^]。
. 您已有一个可正常工作的 NetApp 存储设备，软件定义的实例或云存储服务， Trident 支持此服务。




== 安装 Trident

要在 Kubernetes 集群中安装和配置 NetApp Trident ，请从部署跳转主机执行以下任务：

. 使用以下方法之一部署 Trident ：
+
** 如果您使用 NVIDIA DeepOps 部署 Kubernetes 集群，则也可以使用 NVIDIA DeepOps 在 Kubernetes 集群中部署 Trident 。要使用 DeepOps 部署 Trident ，请按照 https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster#netapp-trident["Trident 部署说明"] 在 NVIDIA DeepOps GitHub 站点上。
** 如果您未使用 NVIDIA DeepOps 部署 Kubernetes 集群，或者您只是希望手动部署 Trident ，则可以按照部署 Trident https://netapp-trident.readthedocs.io/["部署说明"^] 在 Trident 文档中。请务必至少创建一个 Trident 后端和一个 Kubernetes StorageClass 。有关后端和 StorageClasses 的详细信息，请参见 https://netapp-trident.readthedocs.io/["Trident 文档"^]。





NOTE: 如果要在 ONTAP AI POD 上部署 NetApp AI 控制平台解决方案，请参见 link:aicp_example_trident_backends_for_ontap_ai_deployments.html["ONTAP AI 部署的 Trident 后端示例"] 有关您可能希望创建和的不同 Trident 后端的一些示例，请参见 link:aicp_example_kubernetes_storageclasses_for_ontap_ai_deployments.html["适用于 ONTAP AI 部署的 Kubernetes Storageclasses 示例"] 有关可能要创建的不同 Kubernetes StorageClasses 的一些示例，请参见。

link:aicp_example_trident_backends_for_ontap_ai_deployments.html["接下来： ONTAP AI 部署的 Trident 后端示例"]
