---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: NetApp AI 控制平面解决方案不依赖于此特定硬件。 
---
= 硬件和软件要求
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp AI 控制平面解决方案不依赖于此特定硬件。解决方案与 Trident 支持的任何 NetApp 物理存储设备，软件定义的实例或云服务兼容。例如， NetApp AFF 存储系统， Azure NetApp Files ， NetApp Cloud Volumes Service ， NetApp ONTAP Select 软件定义的存储实例或 NetApp Cloud Volumes ONTAP 实例。此外，只要 Kubernetes 和 NetApp Trident 支持所使用的 Kubernetes 版本，即可在任何 Kubernetes 集群上实施解决方案。有关 Kubeflow 支持的 Kubernetes 版本列表，请参见 https://www.kubeflow.org/docs/started/getting-started/["Kubeflow 官方文档"^]。有关 Trident 支持的 Kubernetes 版本列表，请参见 https://netapp-trident.readthedocs.io/["Trident 文档"^]。有关用于验证解决方案的环境的详细信息，请参见下表。

|===
| 基础架构组件 | 数量 | 详细信息 | 操作系统 


| 部署跳转主机 | 1. | 虚拟机 | Ubuntu 20.04.2 LTS 


| Kubernetes 主节点 | 1. | 虚拟机 | Ubuntu 20.04.2 LTS 


| Kubernetes 工作节点 | 2. | 虚拟机 | Ubuntu 20.04.2 LTS 


| Kubernetes GPU 工作节点 | 2. | NVIDIA DGX-1 （裸机） | NVIDIA DGX OS 4.0.5 （基于 Ubuntu 18.04.2 LTS ） 


| 存储 | 1 个 HA 对 | NetApp AFF A220 | NetApp ONTAP 9.7 P6 
|===
|===
| 软件组件 | version 


| Apache 气流 | 2.0.1 


| Apache 气流 Helm 图表 | 8.0.8 


| Docker | 19.03.12 


| Kubeflow | 1.2 


| Kubernetes | 1.18.9 


| NetApp Trident | 21.01.2 


| NVIDIA DeepOps | 提交时主分支的 Trident 部署功能 link:https://github.com/NVIDIA/deepops/tree/61898cdfdaa0c59c07e9fabf3022945a905b148e/docs/k8s-cluster["61898cdfda"]；从 21.03 版开始提供所有其他功能 
|===


=== 支持

NetApp 不为 Apache Airflow ， Docker ， Kubeflow ， Kubernetes 或 NVIDIA DeepOps 提供企业级支持。如果您对具有与 NetApp AI 控制平台解决方案类似的功能的完全受支持的解决方案感兴趣， link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["请联系 NetApp"] 关于 NetApp 与合作伙伴共同提供的完全受支持的 AI/ML 解决方案。

link:aicp_kubernetes_deployment.html["接下来： Kubernetes 部署"]
