---
sidebar: sidebar 
permalink: ai/aicp_kubernetes_deployment.html 
keywords: NVIDIA, GPU, Kubernetes, Control Plane, Trident 
summary: 本页介绍部署 Kubernetes 集群以实施 NetApp AI 控制平面解决方案时必须完成的任务。如果您已有 Kubernetes 集群，则只要您运行的是 Kubernetes 和 NetApp Trident 支持的 Kubernetes 版本，就可以跳过本节。 
---
= Kubernetes 部署
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本节介绍部署 Kubernetes 集群以实施 NetApp AI 控制平面解决方案时必须完成的任务。如果您已有 Kubernetes 集群，则只要您运行的是 Kubernetes 和 NetApp Trident 支持的 Kubernetes 版本，就可以跳过本节。有关 Kubeflow 支持的 Kubernetes 版本列表，请参见 https://www.kubeflow.org/docs/started/getting-started/["Kubeflow 官方文档"^]。有关 Trident 支持的 Kubernetes 版本列表，请参见 https://netapp-trident.readthedocs.io/["Trident 文档"^]。

对于采用采用 NVIDIA GPU 的裸机节点的内部 Kubernetes 部署， NetApp 建议使用 NVIDIA 的 DeepOps Kubernetes 部署工具。本节概述了使用 DeepOps 部署 Kubernetes 集群的过程。



== 前提条件

在执行本节所述的部署练习之前，我们假定您已执行以下任务：

. 您已按照标准配置说明配置任何裸机 Kubernetes 节点（例如，属于 ONTAP AI POD 的 NVIDIA DGX 系统）。
. 您已在所有 Kubernetes 主节点和工作节点以及部署跳转主机上安装受支持的操作系统。有关 DeepOps 支持的操作系统列表，请参见 https://github.com/NVIDIA/deepops["DeepOps GitHub 站点"^]。




== 使用 NVIDIA DeepOps 安装和配置 Kubernetes

要使用 NVIDIA DeepOps 部署和配置 Kubernetes 集群，请从部署跳转主机执行以下任务：

. 按照上的说明下载 NVIDIA DeepOps https://github.com/NVIDIA/deepops/tree/master/docs["Getting Started 页面"^] 在 NVIDIA DeepOps GitHub 站点上。
. 按照上的说明在集群中部署 Kubernetes https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster["Kubernetes 部署指南页面"^] 在 NVIDIA DeepOps GitHub 站点上。

