---
sidebar: sidebar 
permalink: ai/aicp_kubeflow_deployment_overview.html 
keywords: Kubeflow, Prerequisites, Kubernetes, cluster 
summary: NetApp的开源MLOps—Kubeflow部署 
---
= Kubeflow 部署
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本节介绍在 Kubernetes 集群中部署 Kubeflow 必须完成的任务。



== 前提条件

在执行本节所述的部署练习之前，我们假定您已执行以下任务：

. 您已有一个正在运行的Kubenetes集群、并且正在运行的Kubeflow版本支持此Kubenetes版本。有关支持的Kubernetes版本的列表、请参阅中您的Kubeflow版本的依赖关系 link:https://www.kubeflow.org/docs/releases/["Kubeflow 官方文档"^]。
. 您已在Kubnetes集群中安装并配置NetApp Trident。有关Trident的详细信息，请参阅link:https://docs.netapp.com/us-en/trident/index.html["Trident 文档"]。




== 设置默认 Kubernetes StorageClass

在部署Kubeflow之前、我们建议在Kubenetes集群中指定一个默认StorageClass。Kubeflow部署过程可能会尝试使用默认StorageClass配置新的永久性卷。如果未将任何StorageClass指定为默认StorageClass、则部署可能会失败。要在集群中指定默认 StorageClass ，请从部署跳转主机执行以下任务。如果已在集群中指定默认 StorageClass ，则可以跳过此步骤。

. 将现有 StorageClasses 之一指定为默认 StorageClass 。以下示例命令显示了名为的StorageClass的命名 `ontap-ai-flexvols-retain` 作为默认StorageClass。



NOTE: `ontap-nas-flexgroup` Trident 后端类型的最小 PVC 大小相当大。默认情况下， KubeFlow 会尝试配置大小只有少数几 GB 的 PVC 。因此，在部署 Kubeflow 时，不应将利用 `ontap-nas-flexgroup` 后端类型的 StorageClass 指定为默认 StorageClass 。

....
$ kubectl get sc
NAME                                PROVISIONER             AGE
ontap-ai-flexgroups-retain          csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface1   csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface2   csi.trident.netapp.io   25h
ontap-ai-flexvols-retain            csi.trident.netapp.io   3s
$ kubectl patch storageclass ontap-ai-flexvols-retain -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
storageclass.storage.k8s.io/ontap-ai-flexvols-retain patched
$ kubectl get sc
NAME                                 PROVISIONER             AGE
ontap-ai-flexgroups-retain           csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface1    csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface2    csi.trident.netapp.io   25h
ontap-ai-flexvols-retain (default)   csi.trident.netapp.io   54s
....


== Kubeflow部署选项

部署Kubeflow有许多不同的选项。请参见 link:https://www.kubeflow.org/docs/started/installing-kubeflow/["Kubeflow 官方文档"] 有关部署选项的列表、请选择最适合您的需求的选项。


NOTE: 出于验证目的、我们使用部署了Kubeflow 1.7 link:https://www.deploykf.org["部署KF"] 0.1.1.
