---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: 采用NVIDIA DGX系统的NetApp AIPod—从何处查找追加信息 
---
= NVA-1173采用NVIDIA DGX系统的NetApp AIPod—结论和其他信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本节包括使用NVIDIA DGX系统的NetApp AIPod的追加信息参考。



== 结论

DGX BasePOD架构是下一代深度学习平台、需要同等高级的存储和数据管理功能。通过将DGX基本POD与NetApp AFF系统相结合、NetApp AIPod与DGX系统架构几乎可以在任何规模上实施。结合NetApp ONTAP卓越的云集成和软件定义的功能、AFF支持跨边缘、核心和云端的全套数据管道、助力深度学习项目取得成功。



== 追加信息

要详细了解本文档中所述的信息、请参阅以下文档和/或网站：

* NetApp ONTAP 数据管理软件—ONTAP 信息库
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* NetApp AFF A90存储系统-
+
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf"]

* NetApp ONTAP RDMA信息-
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* NetApp DataOps 工具包
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Trident
+
link:../containers/rh-os-n_overview_trident.html["概述"]

* NetApp GPUDirect存储博客-
+
https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/["https://www.netapp.com/blog/ontap-reaches-171-gpudirect-storage/"]

* NVIDIA DGX基本POD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* NVIDIA DGX H100系统
+
https://www.nvidia.com/en-us/data-center/dgx-h100/["https://www.nvidia.com/en-us/data-center/dgx-h100/"^]

* NVIDIA网络
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA麦格努姆io&#482；GPUDirect&#174；存储
+
https://docs.nvidia.com/gpudirect-storage["https://docs.nvidia.com/gpudirect-storage"]

* NVIDIA基本命令
+
https://www.nvidia.com/en-us/data-center/base-command/["https://www.nvidia.com/en-us/data-center/base-command/"]

* NVIDIA Base Command Manager
+
https://www.nvidia.com/en-us/data-center/base-command/manager["https://www.nvidia.com/en-us/data-center/base-command/manager"]

* NVIDIA AI Enterprise
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== 致谢

本文档介绍了NetApp解决方案和ONTAP工程团队的工作、这些团队包括David Arnette、Olga Kornievskaiaa、Dups fischer、Sriketh Kaligotla、MHIT Kumar和Raghuram Sudhaakar。作者还要感谢NVIDIA和NVIDIA DGX BasePOD工程团队的持续支持。
