---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: 采用NVIDIA DGX系统的NetApp AIPod—从何处查找追加信息 
---
= 采用NVIDIA DGX系统的NetApp AIPod—结论和追加信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_validation_sizing.html["上一页：采用NVIDIA DGX系统的NetApp AIPod—解决方案验证和大小指南"]



== 结论

DGX BasePOD架构是下一代深度学习平台、需要同等高级的存储和数据管理功能。通过将DGX BasePD与NetApp AFF系统相结合、NetApp AIPod架构几乎可以在任何规模上实施、从OEM服务器中的单个GPU与AFF A250存储系统配对、到在24节点AFF A900集群上的48个DGX H100系统。结合NetApp ONTAP卓越的云集成和软件定义的功能、AFF支持跨边缘、核心和云端的全套数据管道、助力深度学习项目取得成功。



== 追加信息

要详细了解本文档中所述的信息、请参阅以下文档和/或网站：

* NetApp ONTAP 数据管理软件—ONTAP 信息库
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* NetApp AFF A900存储系统-
+
https://www.netapp.com/data-storage/aff-a-series/aff-a900/["https://www.netapp.com/data-storage/aff-a-series/aff-a900/"]

* NetApp ONTAP RDMA信息-
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* NetApp DataOps 工具包
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Astra Trident
+
https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html["https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html"^]

* ONTAP AI- NetApp通过NVIDIA DGX A100系统验证的架构
+
https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html["https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html"^]

* NVIDIA BasePD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* NVIDIA DGX A100系统
+
https://www.nvidia.com/en-us/data-center/dgx-a100/["https://www.nvidia.com/en-us/data-center/dgx-a100/"^]

* NVIDIA网络
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA AI Enterprise
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== 致谢

本文档介绍了NetApp解决方案和ONTAP工程团队的工作：David Arnette、Olga Kornievskaie、Dups f舍 尔、Srithan Kaligotla、Motit Kumar和Rajeev Badrinath。作者还要感谢NVIDIA和BasePOD工程团队的持续支持。
