---
sidebar: sidebar 
permalink: ai/ddlnexus_initial_setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, Hybrid, Hybrid Cloud, Hybrid Multicloud, Cloud, AWS, Amazon, Amazon Web Services, FSx for NetApp ONTAP, FSx, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: 采用Domino数据实验室和NetApp的混合多云MLOps—初始设置 
---
= 初始设置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本节介绍在整合内部数据中心和AWS的混合环境中将Domino Nexus与NetApp数据服务结合使用所需执行的初始设置任务。



== 前提条件

在执行本节所述的步骤之前、我们假定您已执行以下任务：

* 您已部署和配置内部NetApp ONTAP存储平台。有关详细信息，请参见 link:https://www.netapp.com/support-and-training/documentation/["NetApp 产品文档"]。
* 您已在AWS中配置Amazon FSx for NetApp ONTAP实例。有关详细信息，请参见 link:https://aws.amazon.com/fsx/netapp-ontap/["Amazon FSx for NetApp ONTAP商品页面"]。
* 您已在内部数据中心中配置了Kubbernetes集群。有关详细信息，请参见 link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino管理指南"]。
* 您已在AWS中配置Amazon EKS集群。有关详细信息，请参见 link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino管理指南"]。
* 您已在内部Kubbernetes集群中安装NetApp Trident。此外、您还配置了此三项技术实例、以便在配置和管理存储资源时使用内部NetApp ONTAP存储平台。有关详细信息，请参阅link:https://docs.netapp.com/us-en/trident/index.html["NetApp Trident 文档"]。
* 您已在Amazon EKS集群中安装NetApp Trident。此外、您还配置了此TRIDent实例、以便在配置和管理存储资源时使用Amazon FSx for NetApp ONTAP实例。有关详细信息，请参阅link:https://docs.netapp.com/us-en/trident/index.html["NetApp Trident 文档"]。
* 您必须在内部数据中心和AWS中的虚拟私有云(Virtual Private Cloud、VPC)之间建立双向网络连接。有关实施此功能的各种选项的更多详细信息、请参见 link:https://docs.aws.amazon.com/vpc/latest/userguide/vpn-connections.html["Amazon虚拟专用网络(VPN)文档"]。




== 在AWS中安装Domino Enterprise AI Platform

要在AWS中安装Domino Enterprise MLOps平台，请按照中所述的说明link:https://docs.dominodatalab.com/en/latest/admin_guide/c1eec3/deploy-domino/["Domino管理指南"]进行操作。您必须在先前配置的同一个Amazon EKS集群中部署Domino。此外、必须已在此EKS集群中安装和配置NetApp Trident、并且必须在Domino/yml安装配置文件中指定Trident管理的存储类作为共享存储类。


NOTE: 请参见 link:https://docs.dominodatalab.com/en/latest/admin_guide/7f4331/install-configuration-reference/#storage-classes["Domino安装配置参考指南"] 有关如何在Domino/yml安装配置文件中指定共享存储类的详细信息。


NOTE: link:https://www.netapp.com/media/79922-tr-4952.pdf["技术报告TR-4952"] 介绍如何使用Amazon FSx for NetApp ONTAP在AWS中部署Domino、对于解决出现的任何问题、这可能是一个有用的参考。



== 启用Domino Nexus

接下来、您必须启用Domino Nexus。请参见 link:https://docs.dominodatalab.com/en/latest/admin_guide/c65074/nexus-hybrid-architecture/["Domino管理指南"] 了解详细信息。



== 在内部数据中心部署Domino数据平面

接下来、您必须在内部数据中心部署Domino数据平面。您必须将此数据平面部署在先前配置的内部Kubbernetes集群中。此外、必须已在此Kubnetes集群中安装和配置NetApp Trident。有关详细信息、请参见 link:https://docs.dominodatalab.com/en/latest/admin_guide/5781ea/data-planes/["Domino管理指南"] 。
