---
sidebar: sidebar 
permalink: ai/hciai_edge_use_cases.html 
keywords:  
summary:  
---
= 用例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
尽管当今所有应用程序都不是人工智能驱动的，但它们正在不断发展的功能，使其能够获得人工智能的巨大优势。为了支持采用 AI ，应用程序需要一个基础架构，以便为其提供最佳运行级别所需的资源，并支持其持续发展。

对于 AI 驱动的应用程序，边缘位置是主要的数据源。如果在一段时间内从多个边缘位置收集可用数据以构成培训数据集，则可以将这些数据用于培训。然后，可以将经过培训的模型部署回收集数据的边缘位置，从而加快推理速度，而无需将生产数据重复传输到专用推理平台。

NetApp HCI AI 推理解决方案由采用 NVIDIA T4 GPU 和 NetApp 云连接存储系统的 NetApp H615c 计算节点提供支持，由 NetApp 和 NVIDIA 开发并验证。NetApp HCI 通过解决不确定性问题，消除设计复杂性和结束猜测，简化了在边缘数据中心部署 AI 推理解决方案的过程。此解决方案为 IT 组织提供了一个规范化的架构，可以：

* 在边缘数据中心启用 AI 推理
* 优化 GPU 资源的使用
* 提供基于 Kubernetes 的推理平台，以提高灵活性和可扩展性
* 消除设计复杂性


边缘数据中心在非常接近生成点的位置管理和处理数据。这种接近性可提高处理数据时的效率并减少相关延迟。许多垂直市场已经实现了边缘数据中心的优势，并在很大程度上采用这种分布式数据处理方法。

下表列出了边缘垂直市场和应用程序。

|===
| 垂直 | 应用程序 


| 医疗 | 计算机辅助诊断可帮助医务人员进行早期疾病检测 


| 石油和天然气 | 对远程生产设施，视频和图像分析进行自主检查 


| 航空 | 空中交通控制辅助和实时视频源分析 


| 媒体和娱乐 | 音频 / 视频内容筛选功能，可提供适合家庭使用的内容 


| 业务分析 | 品牌认知度，用于分析在流式直播电视活动中的品牌表现 


| 电子商务 | 将供应商产品智能捆绑在一起，找到理想的商家和仓库组合 


| 零售 | 自动结账，用于识别客户放入购物车的物品，并便于进行数字支付 


| 智慧城市 | 改善交通，优化停车，增强人行和骑行者的安全 


| 制造 | 质量控制，装配线监控和缺陷识别 


| 客户服务 | 客户服务自动化，用于分析和鉴别咨询（电话，电子邮件和社交媒体） 


| 农业 | 智能的农场运营和活动规划，可优化肥料和除草剂应用 
|===


== 目标受众

解决方案的目标受众包括以下组：

* 数据科学家
* IT 架构师
* 现场顾问
* 专业服务
* IT 经理
* 需要在边缘位置提供 IT 创新和强大数据和应用程序服务的基础架构的任何其他人


link:hciai_edge_architecture.html["接下来：架构"]
