---
sidebar: sidebar 
permalink: ai/hciai_edge_virtual_infrastructure_with_automated_deployment.html 
keywords:  
summary:  
---
= 使用 NDE 在 NetApp HCI 上部署 VMware 虚拟基础架构（自动化部署）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== NDE 部署前提条件

请参见 https://["NetApp HCI 前提条件检查清单"^] 在开始部署之前查看 NetApp HCI 的要求和建议。

. 网络和交换机要求和配置
. 准备所需的 VLAN ID
. 交换机配置
. NetApp HCI 和 VMware 的 IP 地址要求
. DNS 和保留时间要求
. 最后准备工作




== NDE 执行

在执行 NDE 之前，您必须完成所有组件的机架和堆栈，网络交换机的配置以及所有前提条件的验证。如果您计划允许 NDE 自动配置所有地址，则可以通过连接到单个存储节点的管理地址来执行 NDE 。

NDE 执行以下任务以使 HCI 系统联机：

. 至少在两个存储节点上安装存储节点（ NetApp Element 软件）。
. 至少在两个计算节点上安装 VMware 虚拟机管理程序。
. 安装 VMware vCenter 以管理整个 NetApp HCI 堆栈。
. 安装和配置 NetApp 存储管理节点（ mNode ）和 NetApp 监控代理。
+

NOTE: 此验证使用 NDE 自动配置所有地址。您也可以在环境中设置 DHCP ，或者为每个存储节点和计算节点手动分配 IP 地址。本指南不会介绍这些步骤。

+
如前所述，此验证对计算节点使用双缆线配置。

+
本文档不介绍 NDE 的详细步骤。

+
有关完成基础 NetApp HCI 平台部署的分步指导，请参见 http://["部署指南"^]。

. 完成 NDE 后，登录到 vCenter 并创建一个分布式端口组 `NetApp HCI VDS 01-NFS_Network` ，以供 ONTAP Select 和应用程序使用。


link:hciai_edge_netapp_h615cmanual_deployment.html["下一步：配置 NetApp H615c （手动部署）"]
