---
sidebar: sidebar 
permalink: ai/vector-database-introduction.html 
keywords: vector database 
summary: Vector数据库解决方案for NetApp简介 
---
= 简介
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本节介绍NetApp的引导程序数据库解决方案。



== 简介

向量数据库可以有效地应对旨在处理大型语言模型(LLM)和生成式人工智能(AI)中复杂语义搜索的挑战。与传统的数据管理系统不同，矢量数据库能够处理和搜索各种类型的数据，包括图像、录像、文字、音频、 和其他形式的非结构化数据、使用数据本身的内容、而不是标签或标记。

关系数据库管理系统(Relational Database Management Systems、RDBMS)的局限性已有充分的记录、尤其是它们在处理AI应用程序中常见的高维度数据表示和非结构化数据方面的困难。RDBMS通常需要一个耗时且容易出错的过程、将数据合并为更易于管理的结构、从而导致搜索延迟和效率低下。然而、矢量数据库旨在规避这些问题、提供更高效、更准确的解决方案来管理和搜索复杂的高维度数据、从而促进AI应用程序的发展。

本文档为当前正在使用或计划使用向量数据库的客户提供了全面的指导、其中详细介绍了在NetApp ONTAP、NetApp StorageGRID、Amazon FSxN for NetApp ONTAP和SnapCenter等平台上使用向量数据库的最佳实践。本文档提供的内容涵盖一系列主题：

* NetApp存储通过NetApp ONTAP和StorageGRID对象存储提供的矢量数据库(如Milvus)基础架构准则。
* 通过文件和对象存储验证AWS FSx for NetApp ONTAP中的Milvus数据库。
* 深入了解NetApp的文件-对象双重性、展示其对矢量数据库以及其他应用程序中数据的实用程序。
* NetApp的数据保护管理产品SnapCenter如何为矢量数据库数据提供备份和还原功能。
* NetApp的混合云如何跨内部环境和云环境提供数据复制和保护。
* 深入了解NetApp ONTAP上的Milvus和pgvector等向量数据库的性能验证。
* 两个特定用例：使用大型语言模型(LLM)的检索增强型生成(RAG)和NetApp IT团队的ChatAI、从而提供所述概念和实践的实际示例。

