---
sidebar: sidebar 
permalink: ai/vector-database-conclusion.html 
keywords: vector database, conclusion 
summary: 结论-用于NetApp的向量数据库解决方案 
---
= 结论
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本节结束了用于NetApp的引导程序数据库解决方案。



== 结论

总之、本文档全面概述了如何在NetApp存储解决方案上部署和管理矢量数据库、例如Milvus和vgvector。我们讨论了利用NetApp ONTAP和StorageGRID对象存储的基础架构准则、并通过文件和对象存储在AWS FSx for NetApp ONTAP中验证了Milvus数据库。

我们探讨了NetApp的文件-对象双重性、展示了它不仅对矢量数据库中的数据有用、而且对其他应用程序有用。我们还重点介绍了NetApp的企业管理产品SnapCenter如何为矢量数据库数据提供备份、还原和克隆功能、从而确保数据完整性和可用性。

本文档还深入探讨了NetApp的混合云解决方案如何跨内部环境和云环境提供数据复制和保护、从而提供无缝、安全的数据管理体验。我们深入分析了NetApp ONTAP上的Milvus和pgvector等向量数据库的性能验证、并提供了有关其效率和可扩展性的宝贵信息。

最后、我们讨论了两种生成性AI用例：RAG with LLM和NetApp的内部ChatAI。这些实际示例强调了本文档所述概念和实践的实际应用和优势。总之、对于希望利用NetApp强大的存储解决方案来管理矢量数据库的任何人、本文档都是一个全面的指南。



=== 致谢

作者衷心感谢以下贡献者、以及为使本白皮书对NetApp客户和NetApp Fields更有价值而提供反馈和意见的其他人员。

. NetApp ONTAP AI和分析技术营销工程师Sathish Thyagarajan
. NetApp 技术营销工程师 Mike Oglesby
. NetApp高级主管，阿希·马哈詹
. NetApp工作负载性能工程经理Joe Scott
. NetApp FSx产品管理高级总监Puneet
. NetApp FSx产品团队高级产品经理YuVal Kalderon




=== 从何处查找追加信息

要了解有关本文档中所述信息的更多信息，请查看以下文档和 / 或网站：

* Milvus文档- https://milvus.io/docs/overview.md[]
* Milvus独立文档- https://milvus.io/docs/v2.0.x/install_standalone-docker.md[]
* NetApp 产品文档
https://www.netapp.com/support-and-training/documentation/[]
* instaclinst. link:https://www.instaclustr.com/support/documentation/?_bt=&_bk=&_bm=&_bn=x&_bg=&utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=1467100120&hsa_cam=20766399079&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAjw26KxBhBDEiwAu6KXtzOZhN0dl0H1smOMcj9nsC0qBQphdMqFR7IrVQqeG2Y4aHWydUMj2BoCdFwQAvD_BwE["instal佐证 文件"]




=== 版本历史记录

|===


| version | Date | 文档版本历史记录 


| 版本 1.0 | 2024年4月 | 初始版本。 
|===