---
sidebar: sidebar 
permalink: ai/vector-database-solution-verification-overview.html 
keywords: Solution Overview vector database 
summary: 解决方案验证概述—用于NetApp的向量数据库解决方案 
---
= 解决方案概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
我们已针对五个关键领域进行了全面的解决方案验证、详细信息如下。每个部分都深入探讨了客户面临的挑战、NetApp提供的解决方案以及后续为客户带来的优势。

. link:./vector-database-milvus-cluster-setup.html["在内部部署中使用Kubbernetes设置Milvus集群"]
客户在存储和计算、有效的基础架构管理和数据管理方面面临独立扩展的挑战。在本节中、我们将详细介绍在Kubbernetes上安装Milvus集群的过程、并利用NetApp存储控制器来存储集群数据和客户数据。
. link：./vector-database -milvus-with -AMAZON-FSx ONTAP for -AMAZON FSx ONTAP for NetApp NetApp ONTAP–file and object dusage]在本节中、我们为什么需要在云中部署向量数据库以及在ONTAP ONTAP for NetApp ONTAP中在Docker容器中部署向量数据库(milvus standalone)的步骤。
. link:./vector-database-protection-using-snapcenter.html["使用NetApp SnapCenter保护向量数据库。"]
在本节中、我们将深入探讨SnapCenter如何保护驻留在ONTAP中的向量数据库数据和Milvus数据。在本示例中、我们会使用从NFS ONTAP卷(vol1)派生的NAS存储分段(milvusdbvol1)存储客户数据、并使用单独的NFS卷(v/tordbpv)存储Milvus集群配置数据。
. link:./vector-database-disaster-recovery-using-netapp-snapmirror.html["使用NetApp SnapMirror进行灾难恢复"]
在本节中、我们将讨论向量数据库进行灾难恢复(Disaster Recovery、DR)的重要性、以及NetApp灾难恢复产品SnapMirror如何为向量数据库提供灾难恢复解决方案。
. link:./vector-database-performance-validation.html["性能验证"]
在本节中、我们将深入探讨Milvus和pgvector.rs等向量数据库的性能验证、重点介绍其存储性能特征、例如I/O配置文件和NetApp存储控制器在LLM生命周期内支持RAG和推导工作负载时的行为。我们将评估并确定将这些数据库与ONTAP存储解决方案结合使用时的任何性能差异。我们的分析将基于关键绩效指标、例如每秒处理的查询数量(QPS)。

