---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-powershell-considerations.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: 这是一款NetApp ONTAP解决方案、用于配置、强化和验证基于ONTAP的网络存储 
---
= 其他注意事项
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
在设计和部署基于ONTAP的网络存储时、还需要考虑一些其他注意事项。



== 容量规模估算注意事项

ONTAP网络存储目标卷所需的磁盘空间量取决于多种因素、其中最重要的因素是源卷中数据的更改率。目标卷上的备份计划和Snapshot计划都会影响目标卷上的磁盘使用量、源卷上的更改率不太可能保持不变。最好提供一个额外存储容量缓冲区、以满足将来最终用户或应用程序行为的变化所需的容量。

要估算ONTAP中1个月保留关系的规模、需要根据多个因素计算存储需求、包括主数据集的大小、数据更改率(每日更改率)以及重复数据删除和数据压缩节省的空间(如果适用)。

下面是分步方法：

第一步是了解您使用网络存储保护的源卷的大小。这是最初将复制到网络存储目标的基本数据量。接下来、估算数据集的每日变更率。这是每天更改的数据百分比。充分了解数据的动态性至关重要。

例如：

* 主数据集大小= 5 TB
* 每日变更率= 5%(0.05)
* 重复数据删除和数据压缩效率= 50%(0.50)


现在、让我们来了解一下计算结果：

* 计算每日数据变更率：
+
`Changed data per day = 5000 * 5% = 250GB`

* 计算30天内的总更改数据：
+
`Total changed data in 30 days = 250 GB * 14 = 3.5TB`

* 计算所需的总存储：
+
`TOTAL = 5TB + 3.5TB = 8.5TB`

* 应用重复数据删除和数据压缩节省量：
+
`EFFECTIVE = 8.5TB * 50% = 4.25TB`



*存储需求摘要*

* 如果没有效率：存储30天的网络存储数据需要* 8.5 TB*。
* 效率为50%：在执行重复数据删除和数据压缩后，需要*4.25TB*的存储。



NOTE: 由于元数据的原因、Snapshot副本可能会产生额外开销、但这种开销通常很小。


NOTE: 如果每天创建多个备份、请按每天创建的Snapshot副本数量调整计算结果。


NOTE: 请考虑数据随时间的增长、以确保规模估算适应未来需求。



== 对主/源的性能影响

由于数据传输是一种拉取操作、因此对主存储性能的影响可能会因工作负载、数据卷和备份频率而异。但是、对主系统的整体性能影响一般是中等的且可管理、因为数据传输旨在将数据保护和备份任务卸载到网络存储系统。在初始关系设置和首次完整备份期间、会将大量数据从主系统传输到网络存储系统(SnapLock Compliance卷)。这可能会导致主系统上的网络流量和I/O负载增加。初始完整备份完成后、ONTAP只需要跟踪和传输自上次备份以来发生更改的块。这样、与初始复制相比、I/O负载会小得多。增量更新非常高效、对主存储性能的影响微乎其微。存储进程在后台运行、这可减少干扰主系统生产工作负载的机会。

* 确保存储系统具有足够的资源(CPU、内存和IOPS)来处理额外的负载可缓解性能影响。

