---
sidebar: sidebar 
permalink: ehc/gcp/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= 适用于 Google Cloud Platform GCVE 的 NetApp 功能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
详细了解 NetApp 为 Google Cloud Platform （ GCP ） Google Cloud Virtualization Ending （ GCVE ）提供的功能—从 NetApp 作为来宾连接存储设备或原生数据存储库，到迁移工作流，扩展 / 突发到云，备份 / 还原和灾难恢复。

从以下选项中选择，跳至所需内容部分：

* link:#config["超大规模部署中的 VMware"]
* link:#datastore["NetApp 存储选项"]




== 在 Google Cloud 中配置 GCVE

与内部部署一样，规划基于云的虚拟化环境对于成功创建 VM 和迁移生产就绪环境至关重要。

与内部部署一样，规划 Google Cloud VMware Engine （ GCVE ）对于成功创建虚拟机和迁移可随时投入生产的环境至关重要。

本节介绍如何设置和管理 GCVE ，并将其与连接 NetApp 存储的可用选项结合使用。


NOTE: 来宾存储是将 Cloud Volumes ONTAP 和云卷服务连接到 GCVE 的唯一受支持方法。

设置过程可细分为以下步骤：

* link:gcp/gcp-setup.html#deploy["部署和配置 GCVE"]
* link:gcp/gcp-setup.html#enable-access["启用对 GCVE 的私有访问"]




== 适用于 GCVE 的 NetApp 存储选项

NetApp 存储可以通过多种方式在 GCP GCVE 中用作 guess connected 或原生数据存储库。

请访问 link:ehc-support-configs.html["支持的 NetApp 存储选项"] 有关详细信息 ...

Google Cloud 支持以下配置中的 NetApp 存储：

* 来宾连接存储 *

* link:gcp/gcp-guest.html#cvo["Cloud Volumes ONTAP （ CVO ）作为子系统连接的存储"]
* link:gcp/gcp-guest.html#cvs["Cloud Volumes Service （ CVS ）作为子系统连接的存储"]


* 原生数据存储库 *

* link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["Cloud Volumes Service （ CVS ）作为原生数据存储库^1."^]



NOTE: 1 —当前处于私有预览模式
